### ISSUE TITLE
`SchedulerName.HostName` should assign it's own name once

### ISSUE THREAD

**Issue by runeflobakk** [kagkarlsson/db-scheduler#1]
The implementation of `getName()` performs a call to `InetAddress.getLocalHost().getHostName();` on each invocation. This is unnecessary and each invocation _may_ in rare circumstances use 5 seconds, and in turn make the Scheduler use 20 seconds to start up as it does 4 invocations of `SchedulerName.getName()`. I have not managed to identify why it happens that `InetAddress.getLocalHost().getHostName()` blocks for 5 seconds, but the javadoc mentions something about:
> a reverse name lookup will be performed and the result will be returned based on the system configured name lookup service.
(https://docs.oracle.com/javase/8/docs/api/java/net/InetAddress.html#getHostName--)

So, another example of JDK classes suddenly reaching out to the Interwebz "for convenience". 🙄

I propose to assign the result from `InetAddress.getLocalHost().getHostName()` to a private final field in `SchedulerName.HostName`, and return the field value in `getName()`.

**Comment by kagkarlsson** [comment]
Added cashing as suggested to prevent unnecessary lookups.
