### ISSUE TITLE
How to create each task with different fixed cron-like schedule?

### ISSUE THREAD

**Issue by balent** [kagkarlsson/db-scheduler#104]
My first goal is to create tasks to run every minute and always at the same second.

I figured out that I can just use cron schedule like this `"0 * * * * ?"`. And create task instances with this task configuration.

However, it would trigger all task instances exactly at the same time. I would like to spread load through the whole minute. So I configured 60 recurring task configurations `"0 * * * * ?"`, `"1 * * * * ?"` ... `"59 * * * * ?"` and when creating new task instance I choose randomly from these 60 configurations.

Then I wanted the same thing for tasks running every 5 minutes. So I did the same, which is another 360 schedule configurations.

This approach works well for these 2 cases, but I would like to make it more generic.

What would be good way to do it dynamically? For example, create schedule which runs every 3 hours but always at the same minute and second?

It feels like I would need to implement new `Schedule` type. And in `getNextExecutionTime` I would use `executionTime` instead of `timeDone`?

Something like `return executionComplete.getExecution().getExecutionTime().plus(duration);`?

But what to do if the duration of execution is longer than the interval between schedules? Skip? Reschedule to past (would it work)? Should we have configuration option for this?

**Is my approach right? Or is it possible to achieve this in any easier way?**

Question 2: Maybe even more generic option would be to store schedule expression in database for each task instance instead of within app in task configuration? Scheduler would pick up task instance from DB, execute task with `taskName` and use schedule expression it found in DB to reschedule it? This way I would be able to create different cron schedule for each task instance instead of creating hundreds of configurations?

**Comment by kagkarlsson** [comment]
There are probably many ways to achieve what you are looking for, difficult to say what would be the best. If it is important that no schedule-times are skipped, you can also consider one recurring task that at midnight just spawns all the executions for the next day. Then you are guaranteed they will run

`return executionComplete.getExecution().getExecutionTime().plus(duration)` would work, would be a variant of `FixedDelay`, I think Spring or Java calls that `FixedRate`

**Comment by kagkarlsson** [comment]
Closing this question. Let me know if you have any follow-up questions.

**Comment by balent** [comment]
Thanks!

**Comment by kagkarlsson** [comment]
🎉 This issue has been resolved in `v16.0.0` ([Release Notes](https://github.com/kagkarlsson/db-scheduler/releases/tag/v16.0.0))
