### ISSUE TITLE
Make it possible to replace Clock in Scheduler

### ISSUE THREAD

**Issue by silmeth** [kagkarlsson/db-scheduler#11]
It would be nice to be able to provide another `Clock` implementation in the scheduler for testing purposes.

At the moment the `Scheduler.Builder` always passes `SystemClock` implementation which delegates `now()` to `Instant.now()`.

**Comment by kagkarlsson** [comment]
Yes, I think we can do that. However, I am curious about what type of tests you are thinking about? The Scheduler will probably be hard to control from a test, as there are no hooks for forcing a check for scheduled tasks etc. So you might have to do some `Thread.sleep` ...

**Comment by silmeth** [comment]
Actually I haven’t yet started writing tests involving things interacting with scheduler, so I do not have any concrete examples, and you might be right there aren’t any. I just saw that the `Scheduler` uses private `Clock`, and since we do use our own implementation where possible to be able to test time-sensitive things, I thought about putting it in the `Scheduler` too.

When / if I have anything particular on my mind, I’ll post examples here, probably somewhere in the next week.

**Comment by kagkarlsson** [comment]
Ok, sure. What I have done so far for integration tests is to just leave the scheduler out of it, and call the tasks the scheduler will call directly instead. But I see how it can be useful to have integration tests that uses the scheduler, for more complete tests..

**Comment by kagkarlsson** [comment]
A test-helper flavor of the scheduler, `ManualScheduler`, has been merged to master via PR #41 . It uses a clock that can be controlled from the outside.

**Comment by kagkarlsson** [comment]
Fix available in `4.1`
