### ISSUE TITLE
Runtime scheduling of task

### ISSUE THREAD

**Issue by anilganipineni** [kagkarlsson/db-scheduler#113]
Can you give me on clear example to schedule the job at runtime.

**Comment by kagkarlsson** [comment]
Have a look at [db-scheduler/src/test/java/com/github/kagkarlsson/scheduler/example/TasksMain.java#L65H](https://github.com/kagkarlsson/db-scheduler/blob/master/db-scheduler/src/test/java/com/github/kagkarlsson/scheduler/example/TasksMain.java#L65)

**Comment by anilganipineni** [comment]
here the one time task you are adding before the start of Scheduler, but my requirement is to start add the task at runtime and schedule it.

I have commented @ https://github.com/kagkarlsson/db-scheduler/issues/98#issuecomment-643724332

**Comment by kagkarlsson** [comment]
I am curious as to why the task cannot be added when the scheduler starts? (Even though actual instances of the task are added only at runtime)

**Comment by cbelizone2y** [comment]
> I am curious as to why the task cannot be added when the scheduler starts? (Even though actual instances of the task are added only at runtime)

Because sometimes you'll need to pass a parameter into your task that depends on live data check my issue question here:

https://github.com/kagkarlsson/db-scheduler/issues/145

**Comment by grossvater** [comment]
I would like to have this feature implemented, since it will allow me to separate in time the creation of the scheduler from the creation of the task.

**Comment by kagkarlsson** [comment]
The thing is, when you have multiple instances of the `Scheduler`, they really should have the same set of tasks. If not, you may have one `Scheduler` scheduling executions another cannot execute. If tasks are added after the `Scheduler` is started, how would you avoid such problems?

**Comment by avitkovskaya-syberry** [comment]
@kagkarlsson Hi, why do you not consider to add possibility to add recurring task at runtime? make TaskResolver class accessible from scheduler?
the use case: scheduler is supposed to runs 200.000 recurring task which are created upon a configurations from cassandra database. New configuration can be added via api to db.
To restart app every time to add/update one more configuration and make it know to scheduler is to long and inconvenient in prod...
Is the only reason to prevent adding tasks at runtime is that schedulers in cluster should know how to run all tasks? can it be responsibility of developer to make all schedulers to know it?

**Comment by kagkarlsson** [comment]
Can you describe these 200.000 recurring tasks? What is the difference between them?

It is most definitely possible to create 200.000 task-instances at runtime via the api (`SchedulerClient`). The only thing the `Scheduler` need to know beforehand is what to do with these instances, i.e. what code to run when they execute.

**Comment by avitkovskaya-syberry** [comment]
every task has it's own unique task_name(id) and cron pattern. execution for every task is to create message with task_name(id) and send it to kafka to trigger further execution  logic. 
new configurations (id and cron pattern) can be added at to db at any time and can't be configured to be known to scheduler before it is started

**Comment by kagkarlsson** [comment]
Ok, you actually have 200.000 recurring tasks with different cron-pattern? Then you need a more generic `Task` that utilizes `task_data` for the things that varies (cron-pattern etc). I recently created an example that persists its schedule in `task_data` (i.e. it can vary per task-instance/execution). You might find it helpful:

https://github.com/kagkarlsson/db-scheduler/blob/master/examples/features/src/main/java/com/github/kagkarlsson/examples/PersistentDynamicScheduleMain.java#L26

I think it should be possible to handle your use-case without changes to TaskResolver. You just need more generic Tasks.
