### ISSUE TITLE
[Question] Any concept of Quartz's StatefulJob / DisallowConcurrentExecution?

### ISSUE THREAD

**Issue by wezell** [kagkarlsson/db-scheduler#122]
I am really digging the simplicity of this library, though I think we have a quartz use case that I'm not seeing covered.  It's the idea of a `StatefulJob` - where only one instance of a job type can be run in a cluster at any one time.  It is something like a cluster wide job queue.

Here is the use case:
I have a cluster of 3 servers all connected to the same db.  When users perform specific actions in our UI, we need to do some db cleanup work in the background, let's call it `DBCleanupJob`.  This work can be heavy and involve multiple tables and cache flushes and we don't want multiple `DBCleanupJob`s happening simultaneously as this can overload the db, but we do want to be able to schedule multiple `DBCleanupJob`s - each cleaning something a bit different, which should execute ultimately.  When one `DBCleanupJob` ends, we want another one to be picked up and run - we don't care which server runs it.

In quartz, you have the concept of a `StatefulJob`, or the annotation `@DisallowConcurrentExecution`, which will prevent the simultaneous execution of our `DBCleanupJob` across the cluster.  I am wondering if db-scheduler has some concept like this- or if there is an elegant way to achieve the same thing without heavily rewriting our code?

**Comment by kagkarlsson** [comment]
Hi! 
There is currently no pretty way of achieving this. One hackish way of achieving it is, when the execution starts, check if a similar task (same task-name) is executing (via `SchedulerClient`). If it is, then reschedule with some delay, if not, run and remove execution. That approach does not give you any guarantees though.

**Comment by kagkarlsson** [comment]
Closing this question. Not seeing a good way to achieve this in db-scheduler in the immediate future other than the possibly "good enough" approach mentioned.
