### ISSUE TITLE
How to schedule one time tasks within recurring tasks.

### ISSUE THREAD

**Issue by attilapapai** [kagkarlsson/db-scheduler#126]
Let's say I have a recurring task which runs every hour which collects users that the service needs to send newsletters.

And for every user I would want to create a one time task for the actual email sending.

How would I do this in a Spring Boot app? Currently I'm getting circular dependencies, but i'm pretty sure it's easy to do I'm just missing something trivial. Could you share some code as well with @Configuration and @Service classes?

Thanks in advance 🙇

**Comment by kagkarlsson** [comment]
Yeah I know what you mean with circular dependencies. To solve it I have added an accessor for a `SchedulerClient` to the `ExecutionContext` in the `ExecutionHandler`. There is an example of it here: https://github.com/kagkarlsson/db-scheduler/blob/master/db-scheduler/src/test/java/com/github/kagkarlsson/scheduler/SchedulerClientTest.java#L145

So no additional Spring config should be necessary

Let me know how that works out.

**Comment by attilapapai** [comment]
Thanks for the reply!

I remember I even checked that class, don't know how I missed that test case...

Anyways I will try it out, let you know how it went.

Thanks, cool library btw! :)

**Comment by kagkarlsson** [comment]
👍 

If you use Spring you should be able to wrap it in @Transactional or use `TransactionTemplate` to get a transaction around the modifications the `SchedulerClient` does

**Comment by attilapapai** [comment]
And it worked, thanks again 🙇

**Comment by kagkarlsson** [comment]
Excellent! 👍
