### ISSUE TITLE
Run now function for recurring task

### ISSUE THREAD

**Issue by rafaelhofmann** [kagkarlsson/db-scheduler#140]
Hi,

We have many recurring tasks to import data into our database. We are building an admin frontend to display the status (information like last execution, etc) of each recurring task. The missing feature on that frontend is a button "Execute now". The button would trigger the task to be executed now. After the one time execution the task should be scheduled again according to the original schedule.

Something like `scheduler.runOnce(taskName : String)` would be really nice.

**Comment by kagkarlsson** [comment]
Hi! I like your use-case, building a UI. Some of the methods on `SchedulerClient` was intended for that purpose, but I never got around to implementing one myself. I think you should be able to achieve what you want using the existing method `scheduler.reschedule(TaskInstanceId.of(taskName, id), Instant.now())`? After it has run, it will evaluate the `Schedule` and set next execution time accordingly (which will likely be the same time as it had prior to you pressing the "Execute now" button).

**Comment by rafaelhofmann** [comment]
That was exactly what we were looking for. We managed to get the execute now function to work with the reschedule method.
Also, thank you very much for creating and maintaining this library! We were able to replace Quartz and your library is a lot easier to handle.

**Comment by kagkarlsson** [comment]
Excellent 👍 
Let me know if there is any other challenges with making a gui for db-scheduler

**Comment by cckmit** [comment]
认真学习 db-scheduler
  My English is not standard

**Comment by kagkarlsson** [comment]
> 认真学习

? :)

**Comment by archbobo** [comment]
> > 认真学习
> 
> ? :)

认真学习 means study hard :)

**Comment by cckmit** [comment]
买了好多 archbobo 在极客时间的视频课程啊
