### ISSUE TITLE
Move ManualScheduler (for tests) to separate test-artifact

### ISSUE THREAD

**Issue by kagkarlsson** [kagkarlsson/db-scheduler#141]
`ManualScheduler`, a scheduler used for testing that allows for manual triggering of activites, currently lives in the main maven artifact `db-scheduler`. It is a leftover from before db-scheduler was a multi-module maven project. We should move the package `com.github.kagkarlsson.scheduler.testhelper` into a new maven artifact `db-scheduler-test` so that it can be included  specifically for tests with `<scope>test</scope>`

Package: 
https://github.com/kagkarlsson/db-scheduler/blob/master/db-scheduler/src/main/java/com/github/kagkarlsson/scheduler/testhelper/

**Comment by cunhazera** [comment]
@kagkarlsson can you give more details about what you expect? Is the idea to create a new module inside the project containing this class?

**Comment by kagkarlsson** [comment]
I tried clarifying the description. Makes sense?

**Comment by cunhazera** [comment]
Hell yeah, it does. tnx

**Comment by cunhazera** [comment]
@kagkarlsson I just can not figure it out how to avoid cyclic dependency between `db-scheduler-test` and `db-scheduler`. Given the fact that I need to have the `db-scheduler` as a dependency inside `db-scheduler-test`, so them I can have `db-scheduler-test` inside `db-scheduler`.
Am I missing something?

**Comment by kagkarlsson** [comment]
Oh crap, yeah I had not anticipated that. It's because I would like it to use it in db-scheduler as a test-util, but also publish it for users of the library.
Normally I suppose you would extract a `Scheduler` interface into a third artifact that both can depend upon, but I don't want to do that here. 
I suppose we might duplicate and separate them...  a bit unsure atm

**Comment by kagkarlsson** [comment]
I wonder if it would be possible to avoid creating the extra maven module, but instead generate a jar from that testhelper package...  ideally with the package `testhelper` moved from main to test

**Comment by cunhazera** [comment]
Well, I thin it's worthy to open a new issue based on this discussion. It looks like a new artifact, considering how the project is structured today, would not be the best approach. What do you think?

**Comment by kagkarlsson** [comment]
Yeah I am thinking you discovered a weakness in this issue, the suggested solution is not possible. And to be honest, I am not sure how I want to proceed. Will close this issue. If you feel you have put in a lot of work, I could mark it as `hacktoberfest-accepted`
