### ISSUE TITLE
How to modify on run time values of my task?

### ISSUE THREAD

**Issue by cbelizone2y** [kagkarlsson/db-scheduler#145]
Hi,

I have a spring boot application and I have designed the following service:

```java
public interface ExtractingService {
    List<Individuals> extract(@Nullable Date delta);
}
```
And I have designed the following recurring task that is picked up on startup:

```java
@Slf4j
@Component
public class ExtractTask extends RecurringTask<Void> {

    @Resource
    private ExtractingService extractingService;

    public ExtractTask() {
        super("extracting-task", FixedDelay.ofSeconds(20), null);
    }

    @Override
    public void executeRecurringly(final TaskInstance<Void> taskInstance, final ExecutionContext executionContext) {
        log.info("Started [extracting-task] at {}", LocalDateTime.now());
        extractingService.extract(null);
        log.info("Finished [extracting-task] at {}", LocalDateTime.now());
    }
}
```

I have designed a controller endpoint that has an optional parameter the delta time:

```java
@Slf4j
@RequestMapping("/extracting")
@RestController
public class ExtractController {
    @Resource
    private Scheduler scheduler;

    @Resource(name = "ExtractTask")
    private ExtractTask extractTask;

    @ResponseBody
    @RequestMapping("/runJob")
    public List<CurrentlyExecuting> runJob(@RequestParam(required = false)
                                           @DateTimeFormat(iso = DateTimeFormat.ISO.DATE) final Date delta) {
        final List<CurrentlyExecuting> currentlyExecuting = scheduler.getCurrentlyExecuting();

        //Avoiding scheduling the task if it's already running
        if (currentlyExecuting.stream().noneMatch(task -> task.getTaskInstance().getTaskName().equals("extracting-task"))) {
            scheduler.reschedule(extractTask.instance("recurring"), Instant.now());
        }

        return currentlyExecuting;
    }
}
```

I would like to know what is the best approach for being able to pass the `delta` Date object into my recurring task.

The only solution I came up with was doing something like this but it's not thread-safe and error-prone:

Task bean:

```java
@Slf4j
@Component
public class ExtractTask extends RecurringTask<Void> {

    @Resource
    private ExtractingService extractingService;
    
    @Setter
    private Date delta;

    public ExtractTask() {
        super("extracting-task", FixedDelay.ofSeconds(20), null);
    }

    @Override
    public void executeRecurringly(final TaskInstance<Void> taskInstance, final ExecutionContext executionContext) {
        log.info("Started [extracting-task] at {}", LocalDateTime.now());
        //non thread-safe
        extractingService.extract(delta);
        delta = null
        log.info("Finished [extracting-task] at {}", LocalDateTime.now());
    }
}
```

Controller:

```java
@Slf4j
@RequestMapping("/extracting")
@RestController
public class ExtractController {
    @Resource
    private Scheduler scheduler;

    @Resource(name = "ExtractTask")
    private ExtractTask extractTask;

    @ResponseBody
    @RequestMapping("/runJob")
    public List<CurrentlyExecuting> runJob(@RequestParam(required = false)
                                           @DateTimeFormat(iso = DateTimeFormat.ISO.DATE) final Date delta) {
        extractTask.setDelta = deltal;
        final List<CurrentlyExecuting> currentlyExecuting = scheduler.getCurrentlyExecuting();

        //Avoiding scheduling the task if it's already running
        if (currentlyExecuting.stream().noneMatch(task -> task.getTaskInstance().getTaskName().equals("extracting-task"))) {

            scheduler.reschedule(extractTask.instance("recurring"), Instant.now());
        }

        return currentlyExecuting;
    }
}
```
 
Is there any way of modifying the execution part/parameters of a task once this one has been created?

Thanks!

**Comment by kagkarlsson** [comment]
How about a task like `RecurringTask<Date>` similar to:
https://github.com/kagkarlsson/db-scheduler/blob/master/db-scheduler/src/test/java/com/github/kagkarlsson/scheduler/example/SchedulerMain.java#L35

And you would change the data by calling:
```
scheduler.reschedule(extractTask.instance("recurring"), Instant.now(), delta);
```
(there is a `reschedule` method that also updates the task-data)

I thiiink that should work.

Also, relying on `scheduler.getCurrentlyExecuting()` does not work if you have multiple instances of the scheduler, it only returns those currently executing by the instance you call the method on. I can see that this is poorly documented, and the method should have a better name. 
You should be able to use `getScheduledExecution(TaskInstanceId taskInstanceId)` instead, and require that it is not picked (or that `execution_time` is a bit into the future).

**Comment by cbelizone2y** [comment]
Thank you so much, this has indeed worked as expected. I'll take your advice regarding how to check if a job is currently running.

**Comment by kagkarlsson** [comment]
Good to hear! 👍

**Comment by cbelizone2y** [comment]
Hi @kagkarlsson,

I was trying to follow your advice regarding how to know wether a task is being or not executed, so I did this:

```
final Optional<ScheduledExecution<Object>> scheduledExecution = schedulerClient.getScheduledExecution(
				TaskInstanceId.of(recurringTask.getName(), RecurringTask.INSTANCE));
scheduledExecution.get();
```

Problem is that `ScheduledExecution` has no member to know if the task is being or not picked up. Any thoughts?

**Comment by kagkarlsson** [comment]
Ah ok, sorry about that. I also see there are some inconsistencies between

```public Optional<ScheduledExecution<Object>> getScheduledExecution(TaskInstanceId taskInstanceId) {```

and 

```public <T> void getScheduledExecutionsForTask(String taskName, Class<T> dataClass, Consumer<ScheduledExecution<T>> consumer) {```

The latter filters out any executions that are "picked", the first one does not. But as you say, you have no accessor to check the picked status for the first variant anyway. So I need to rework the api a bit... 

For now, is it an acceptable workaround to use `getScheduledExecutionsForTask(String taskName, Class<T> dataClass, Consumer<ScheduledExecution<T>> consumer)` and find the correct instance in Java-code? It will not return the execution if it is picked, so you should be good..

**Comment by cbelizone2y** [comment]
```java
@Component
public class TaskRunnerService {

	@Resource
	private SchedulerClient schedulerClient;

	public TaskStatus runNowRecurringTask(final RecurringTask<?> recurringTask, final Object param) {
		AtomicReference<TaskStatus> status = new AtomicReference<>(TaskStatus.NOT_SCHEDULED);

		schedulerClient.getScheduledExecutionsForTask(recurringTask.getName(), recurringTask.getDataClass(), task -> {
			schedulerClient.reschedule(task.getTaskInstance(), Instant.now(), param);
			status.set(TaskStatus.SCHEDULED);
		});

		return status.get();
	}
}
```

We have adapted the code to do this and it's working as expected, thanks!

**Comment by kagkarlsson** [comment]
Good to hear, will try and get the `getScehduledExecution` api slightly more usable :)
