### ISSUE TITLE
Enrolling scheduling inside an already opened transaction

### ISSUE THREAD

**Issue by grossvater** [kagkarlsson/db-scheduler#146]
I think about using db-scheduler in my project, and would need to enroll the scheduling into an existing database transaction. The documentation says:

<The methods on SchedulerClient (schedule, cancel, reschedule) and the CompletionHandler will run using a new Connectionfrom the DataSourceprovided. To have the action be a part of a transaction, it must be taken care of by the DataSourceprovided, for example using something like Spring's TransactionAwareDataSourceProxy>

What I understand from here is that if the datasource will provide the right connection (with an active transaction), the scheduling will be part of that transaction. Is that true?

If this is true, how will work with the fix introduced by the PR 109 (explicit commit when datasource has autocommit = false)? I think this will actually commit the transaction the db-scheduler is supposed to enroll into? (I did't tested, just looked at the code)

**Comment by kagkarlsson** [comment]
After looking at the spring-jdbc code, I suspect you are correct. I thought the `commit()` call was swallowed by the ConnectionProxy (ie. not committing), but I find no such code. It seems it would delegate the `.commit()` to the underlying connection.

So in this would be a bug then, and I would need to find a better way to support people using datasources with autocommit=false .. 

Are you using Spring?

**Comment by grossvater** [comment]
No Spring.

**Comment by kagkarlsson** [comment]
Ok, how are you planning on externally manage the transaction?

**Comment by kagkarlsson** [comment]
I think we need to be able to instantiate the `SchedulerClient` with knowledge on how to determine if it should explicitly commit or not...

**Comment by grossvater** [comment]
I saw `TransactionManager` and I thought about using it. It keeps the connection in a thread local variable. I would like to use it, but I think it should be modified a little bit:
1. allow nested calls by keeping a thread local counter and increment / decrement it inside `inTransaction`
2. instruct the manager what to do when the counter goes to 0: COMMIT, ROLLBACK or NOTHING

Haven't think long about this idea, but maybe it would allow to wrap the call to scheduler in a transaction?

**Comment by kagkarlsson** [comment]
Yeah that was the intended purpose of the `TransactionManager`, to supply conventient transaction-support without Spring. I have not worked through the full use-case yet though, but given this issue, it appears it is time.

Currently considering changes:

* Make `JdbcRunner` aware of ongoing micro-jdbc `TransactionManager` transactions and reuse that Connection if present
* Allow for a short-lived SchedulerClient which can be instantiated with a `Connection` instead of a `DataSource`, to let users manage the Connection as they like
* A little bit down the road, create a SpringAwareSchedulerClient that is aware of spring-jdbc transactions

**Comment by sooty1892** [comment]
I have the same issue using Spring (Boot) transaction manager with SQL Server.

My use case is inserting large amounts of data in one transaction, and at the end of that insert (within the same transaction), scheduling multiple tasks. I need an all or nothing approach, however, once the first task is scheduled the transaction is commited. If the next task scheduling fails, no rollback can occur.

Why would `JdbcRunner` need to call `commitIfNecessary` at all?
If the connection is `autoCommit=false` then it is down to the user or transaction manager to handle the commit.
If the connection is `autoCommit=true` then as per Java documentation, the SQL statement will be commited after execution of the statement has finished.

**Comment by kagkarlsson** [comment]
This was a fix for issue #97, but it had some unintended consequences. I will look into fixing this asap.

**Comment by kagkarlsson** [comment]
I am reverting the change introduced in #109 , and rather providing a `SchedulerBuilder.commitWhenAutocommitDisabled(true)` override for the case in #109 .

Default behavior will be to never explicitly commit.

Releasing in 9.0

**Comment by sooty1892** [comment]
I've tested 9.0 with my scenario and works as expected.
Thank you for the quick fix.

**Comment by kagkarlsson** [comment]
Good 👍
Thank you for letting me know.

Will be closing this issue @grossvater . Will open a new one if you want, for transaction-management support using micro-jdbc, but I think your best option for now is to use spring-jdbc and spring-tx for the transaction-management. What do you think?

**Comment by kagkarlsson** [comment]
Opened new issue #160 for rest. Closing this one.
