### ISSUE TITLE
[ENHANCEMENT] get methods should not return void

### ISSUE THREAD

**Issue by cbelizone2y** [kagkarlsson/db-scheduler#148]
Hi,

Although this change will impact projects currently running I believe that methods like these ones:

`com.github.kagkarlsson.scheduler.SchedulerClient#getScheduledExecutions`
`com.github.kagkarlsson.scheduler.SchedulerClient#getScheduledExecutionsForTask`

should not start by get

**Comment by kagkarlsson** [comment]
The reason they are a bit quirky and take a `Consumer` rather than return a `List` is to enable guarding against holding more data in memory than necessary.  What do you think is a good name for such methods?

I probably should supply a couple of convenience-methods that do return a `List`..

**Comment by cbelizone2y** [comment]
> The reason they are a bit quirky and take a `Consumer` rather than return a `List` is to enable guarding against holding more data in memory than necessary. What do you think is a good name for such methods?
> 
> I probably should supply a couple of convenience-methods that do return a `List`..

I think that returning the list should suffice too.

**Comment by kagkarlsson** [comment]
This is being addressed in PR #155

**Comment by kagkarlsson** [comment]
Fixed in `v9.2`
