### ISSUE TITLE
declare(create beans) tasks in spring without starting them.

### ISSUE THREAD

**Issue by futurpc** [kagkarlsson/db-scheduler#150]
Hi Gustav Karlsson
Is there an option in spring using the auto-configured scheduler just to declare the tasks without starting them?
I want to start an instance of declared tasks dynamically.
Thank you

**Comment by futurpc** [comment]
I think I found the answer, using custom task (declare it as bean)  and schedule(scheduler.schedule) additional tasks dynamically

**Comment by kagkarlsson** [comment]
Glad you found a solution 👍 

Just to clarify, are we talking about a _recurring_ task that you do not want started when the scheduler starts?

**Comment by futurpc** [comment]
Yes, I want to have recurring tasks that running every x time and adding removing other recurring tasks by external configuration.
Thank you for your library, I will share more feedbacks with the time:)

**Comment by kagkarlsson** [comment]
Yeah, for Spring Boot you need a task that does not implement `OnStartup` since otherwise it will automagically start it for you. Let me know if there are further challenges in this area
