### ISSUE TITLE
Get all tasks (not only picked) from scheduler 

### ISSUE THREAD

**Issue by futurpc** [kagkarlsson/db-scheduler#151]
Is there plans to add a method for retrieving a list of tasks that scheduled or running by any of executors (not only by the executor that I'm checking from)?
I know its challenging to deserialize the data from multiple tasks, but I'm talking about a list of task names and tasks ids.

**Comment by kagkarlsson** [comment]
Have you had a look at `scheduler.getScheduledExecutions(Consumer<ScheduledExecution<Object>> consumer)`?

**Comment by kagkarlsson** [comment]
It will not include executions that are currently running. I will try and improve that api with some options to also let you fetch executions that is currently picked/running

**Comment by futurpc** [comment]
Yes @kagkarlsson, I looked at scheduler.getScheduledExecutions(Consumer<ScheduledExecution<Object>> consumer) , but as you mention its missing the running instances .

**Comment by kagkarlsson** [comment]
This is being addressed in #155

**Comment by kagkarlsson** [comment]
Fixed in `v9.2`

**Comment by futurpc** [comment]
@kagkarlsson , Thank you !
