### ISSUE TITLE
Found execution with unknown task-name 'scheduled_task'. Adding it to the list of known unresolved task-names.

### ISSUE THREAD

**Issue by Carmageddon** [kagkarlsson/db-scheduler#152]
I am trying to dynamically schedule an execution of a task in my REST controller.
I am building based on Spring Boot.

This is the error I get on execution:

> 020-11-11 22:53:22.159  INFO 54136 --- [pool-2-thread-1] c.g.kagkarlsson.scheduler.TaskResolver   : Found execution with unknown task-name 'scheduled_task'. Adding it to the list of known unresolved task-names.
> 2020-11-11 22:53:22.160  WARN 54136 --- [pool-2-thread-1] c.g.k.scheduler.JdbcTaskRepository       : Failed to find implementation for task with name 'scheduled_task'. Execution will be excluded from due. Either delete the execution from the database, or add an implementation for it. The scheduler may be configured to automatically delete unresolved t to automatically delete unresolved tasks after a certain period of time.

This is how my controller looks:
```
	@PostMapping("/schedules")
	public ResponseEntity<Schedule> createSchedule(@RequestBody Schedule schedule) {
		schedule.setId(UUID.randomUUID().toString());
		Instant timeToExecute = Instant.parse(schedule.getTimestamp());

		OneTimeTask<Schedule> myAdhocTask = Tasks.oneTime("scheduled_task", Schedule.class)
        .execute((inst, ctx) -> {
			System.out.println("Executed! Custom data, Id: " + inst.getId());
		});
		this.schedulingService.getScheduleExecutor().schedule(myAdhocTask.instance(schedule.getId(), schedule), timeToExecute);
		
		return ResponseEntity.status(HttpStatus.ACCEPTED).body(schedule);
	}
```

Thinking it may require some definition, I added the following in a file annotated @Configuration:
```
    /**
     * Define a one-time task which have to be manually scheduled.
     */
    @Bean
    Task<Schedule> scheduled_task() {
        return Tasks.oneTime("scheduled_message", Schedule.class)
            .execute((instance, ctx) -> {
                log.info(instance.getData().getMessage());
            });
    }
```

It does not affect the error.

The DB table has the task row with the same name

I am not sure, I may be misreading the documentation, on how to use this library.. any help would be appreciated!

**Comment by Carmageddon** [comment]
I've got it resovled - kind of, isntead of Tasks.oneTime("scheduled_task", it should match the name defined inside the bean - "scheduled_message", and then it works, it executes the code defined inside the bean!

However I am trying to understand the purpose of the code in .execute section, when creating the Tasks.oneTime in the controller, in the above example? This code is not being executed ever, as far as I can see.

How do I clean this up? what is the purpose of .execute?

**Comment by kagkarlsson** [comment]
```
OneTimeTask<Schedule> myAdhocTask = Tasks.oneTime("scheduled_task", Schedule.class)
        .execute((inst, ctx) -> {
			System.out.println("Executed! Custom data, Id: " + inst.getId());
		});
```

`myAdhocTask` need to be supplied to the `Scheduler` on startup. I think that will happen automatically in Spring Boot if you have declared a bean for it.

Try declaring a spring bean for:
`OneTimeTask<Schedule> myAdhocTask`

**Comment by kagkarlsson** [comment]
You schedule task-instances/executions here:
```
this.schedulingService.getScheduleExecutor().schedule(myAdhocTask.instance(schedule.getId(), schedule), timeToExecute);
```

`.execute(..) {...}` specifies what should happen when that execution run, at `timeToExecute`

**Comment by kagkarlsson** [comment]
Edit: I see you already have a bean for the Task, that is good.

In 
```public ResponseEntity<Schedule> createSchedule(@RequestBody Schedule schedule) {```

you should not create the task definition again, but you should inject a reference to the spring bean you create here:
```    @Bean
    Task<Schedule> scheduled_task() {```

**Comment by kagkarlsson** [comment]
Will be closing this issue unless you have any more related questions?

**Comment by punkratz312** [comment]
im having the same issue actually my code looks very similar to the demo one but does not work unfortunately


```
{"timestamp":"2022-06-30T11:37:15.448+02:00","sequence":2191,"loggerClassName":"org.slf4j.impl.Slf4jLogger","loggerName":"com.github.kagkarlsson.scheduler.jdbc.JdbcTaskRepository","level":"WARN","message":"Failed to find implementation for task with name 'callback-task'. Execution will be excluded from due. Either delete the execution from the database, or add an implementation for it. The scheduler may be configured to automatically delete unresolved tasks after a certain period of time.","threadName":"db-scheduler-execute-due-pool-11-thread-1","threadId":120,"mdc":{},"ndc":"","hostName":"macbook-pro-von-.local","processName":"scheduler-dev.jar","processId":4538}
```



![image](https://user-images.githubusercontent.com/8830888/176645547-18360e18-a833-48da-bb0b-3dcc1044ecc4.png)
