### ISSUE TITLE
Mark a scheduled task as dead

### ISSUE THREAD

**Issue by MaXeraph** [kagkarlsson/db-scheduler#156]
Im looking to persists tasks that failed in the database, one way that I'm planning to attempt this is to just mark it as Dead and do nothing upon dead executions. Is this feasible ?

**Comment by kagkarlsson** [comment]
The table `scheduled_tasks` is not really designed to hold old executions, everything is assumed to "executable" at some point in time. 

You might reschedule executions 1000 years into the future which will make the scheduler never pick them, but storing so many executions in the table might slow things down (it will be up to you to create necessary indices).


It would be much better to write the execution to a new table once it is done (in the completion-handler), some sort of history-table

**Comment by MaXeraph** [comment]
Sounds good, Thanks!
