### ISSUE TITLE
stop polling for some instances

### ISSUE THREAD

**Issue by bm46370** [kagkarlsson/db-scheduler#157]
Hi,
I have question regarding polling tasks on multiple instances. I have scheduler on multiple instances (locations) reading from same table. I would like to stop polling on some locations but still I would like to leave schedule option on all instances and locations. Is there a way to do that or am i missing something?
For example, i would like to set pollingInterval to null or something like that if instance is on particular location:
```
dbScheduler = Scheduler.create(dataSource, taskImplementations)
                .tableName("xxx.scheduled_tasks")
                .pollingInterval(null)
```
but still be able to do scheduling:
`dbScheduler.schedule(task, executionTime)`

thanks!

**Comment by kagkarlsson** [comment]
Yes! You can instantiate a `SchedulerClient` (will not poll and execute, but allow interaction with scheduled tasks etc):

https://github.com/kagkarlsson/db-scheduler/blob/master/db-scheduler/src/main/java/com/github/kagkarlsson/scheduler/SchedulerClient.java#L127

Also, see test:
https://github.com/kagkarlsson/db-scheduler/blob/master/db-scheduler/src/test/java/com/github/kagkarlsson/scheduler/SchedulerClientTest.java#L68

**Comment by adamalexandru4** [comment]
@kagkarlsson `SchedulerClient` bean with no poll only execute could be created using Spring auto configuration looking for a property like `db-scheduler.worker=false` maybe in the future.
