### ISSUE TITLE
Double execution of OneTimeTask

### ISSUE THREAD

**Issue by kochmap** [kagkarlsson/db-scheduler#162]
Hi,

We are successfully using your scheduler at version 6.0 together with Spring Boot. We have over a dozen instances of our app in production, with this scheduler. Unfortunately, we came across a case of double executing a task despite the fact that it was OneTimeTask. This task is entirely performed in a transaction managed by spring, in this case one transaction was committed, and then another attempt was made to execute this task, but this time the transaction failed due to the protection against duplication (unique index). Unfortunately, I don't have any logs from that time anymore :(

Our suspicion is that there was a timeout on CompleteHandler when removing the executed task. We have configured the datasource as TransactionAwareDataSourceProxy in our app, but from what I was looking at the code, it is not enough for CompleteHandler to take part in the transaction.

Therefore, I have two questions:
- Do you know any reason other than CompleteHandler timeout, which could cause double execution? The instance did not fall at that time.
- If I am right about CompleteHandler with TransactionAwareDataSourceProxy, do you know how to configure the scheduler so that the same transaction is both in the task and CompleteHandler?

Apart from that, this scheduler works perfectly well in our case, in peaks we handle about 2k tasks per second. Thanks for this great lib.

**Comment by kagkarlsson** [comment]
Hi!

If your application is sensitive to "double execution" of a task/execution I recommend being very explicit about what type of  `FailureHandler`  and `DeadExecutionHandler` you are using. The default for onetime-tasks are: 
```
        public OneTimeTaskBuilder(String name, Class<T> dataClass) {
            this.name = name;
            this.dataClass = dataClass;
            this.onDeadExecution = new DeadExecutionHandler.ReviveDeadExecution<>();
            this.onFailure = new FailureHandler.OnFailureRetryLater<>(DEFAULT_RETRY_INTERVAL);
        }
```
I suppose this an "at least once" default. 

Multiple executions can with this configuration happen if:
* your code (`ExecutionHandler`) throws an Exception, in which case the FailureHandler is triggered, i.e. the execution is retried in 5min
* The `CompletionHandler`, which in this case should remove the "picked/locked" row from the database table, fails. The execution will then remain as "picked" in the database. The `Scheduler` will not attempt to run it again. Eventually, it is detected as "dead", and the `DeadExecutionHandler` is called, which in this case would reschedule the execution to "now" (as per config)

Also, regarding transactions, there is no transaction spanning both your code (i.e. the `ExecutionHandler`) and the Scheduler's call to the completion/failure-handler. So your changes could be committed even if the CompletionHandler throws some Exception.

Does that answer your questions?

You have an interesting use-case, pretty high throughput. Good to hear that is working for you (apart from this issue) 👍 
You might want to upgrade to the latest version. Fixed a couple of bugs that potentially could limit throughput in v8.0 (detected in a couple of flaky concurrency tests)

**Comment by kagkarlsson** [comment]
I suppose if your code threw the Exception, your changes would have been rolled back, so it must be a case of failing when the Scheduler called the CompletionHandler. So the execution was eventually detected as dead and rescheduled.

You could protect against it by changing to another `DeadExecutionHandler`

**Comment by kochmap** [comment]
Thanks for the quick reply, I think we will move towards an external deduplication mechanism in case we need to complete the task exactly once, changing the `DeadExecutionHandler` is not enough for us because it is at most once.
