### ISSUE TITLE
[question] How to implement tasks?

### ISSUE THREAD

**Issue by mreiche** [kagkarlsson/db-scheduler#163]
I followed the documentation for `OneTimeTask` but get the following error message:
```
[db-scheduler-execute-due-pool-3-thread-1][INFO]: scheduler.TaskResolver - Found execution with unknown task-name 'my-typed-adhoc-task'. Adding it to the list of known unresolved task-names.
 [db-scheduler-execute-due-pool-3-thread-1][WARN]: scheduler.JdbcTaskRepository - Failed to find implementation for task with name 'my-typed-adhoc-task'. Execution will be excluded from due. Either delete the execution from the database, or add an implementation for it. The scheduler may be configured to automatically delete unresolved tasks after a certain period of time.
```

What I have to do?
I'm not using Spring Boot.

**Comment by kagkarlsson** [comment]
You have to provide the implementation to the `Scheduler` when it is built/created. 

`.create(dataSource, <my-typed-adhoc-task>)`

See example here:

https://github.com/kagkarlsson/db-scheduler/blob/master/db-scheduler/src/test/java/com/github/kagkarlsson/scheduler/example/TasksMain.java#L58

**Comment by mreiche** [comment]
Alright
