### ISSUE TITLE
Task polling using sequential scan instead of index scan

### ISSUE THREAD

**Issue by rafal-kowalski** [kagkarlsson/db-scheduler#164]
Hi, we are using db-scheduler under quite heavy load (millions of due tasks, executing 2.5k tasks per second) and overall this library is handling it pretty well :) but sometimes throughput drops significantly (from 2.5k tsp to ~100 tsp). After our investigation we came to conclusion that the cause lies in Postgres query planner.
Since `TaskRepository.getDue` executes following sql code
`"select * from " + tableName + " where picked = ? and execution_time <= ? " + unresolvedFilter.andCondition() + " order by execution_time asc"`
Postgres query planner does not know that we need only first N tasks matching this criteria it decides to use sequential scan and begins sorting whole table based on execution_time as it would be faster in case when we need to get all of the rows, but when only subset is needed it could use presorted index, sometimes it does use index scan (query planner works in mysterious ways 😄).
Query execution times in our case look something like that:
- when sequential scan is used getDue takes around 10 seconds
- when index scan is used getDue takes around 50 milliseconds

Based on https://www.postgresql.org/docs/current/indexes-ordering.html when this kind of query has explicit LIMIT statement added it would always use index scan, as then it would know that we need only small subset.
With `JDBC.setMaxRows` limiting works in different way, in case of PostgreSQL driver it does not append LIMIT to query but after fetching desired row number it stops getting rest of data.
Since your library supports all SQL servers it might be impossible to implement generic way to always enforce this behaviour, afaik LIMIT won't work eg. in Oracle DB.

What we could do for our case is to override `JdbcTaskRepository.getDue()` and implement this method to work for Postgres.
I would love to hear another solutions or suggestions. 😃

**Comment by kagkarlsson** [comment]
If it works as you describe I consider it a bug, and we need to find a way to solve it. (and your suggestion sounds good)

Though I am a bit surprised I haven't seen this before. I have run a load test against postgres and similarly had to create index etc, but in the end it achieved 2-5k executions/s. This was sometime ago, and I discovered some other bugs (race conditions) that could lead to the behavior you are describing (sudden drop in thoughput). Are you using the latest version?

Would you post your index here please?

(I also ran load tests using a new (unreleased) select-for-update strategy for postgres, which scales better, achieving 10k executions/s)

**Comment by kagkarlsson** [comment]
Should we need to tune the sql, I would consider adding a config-option `.sqlUseExplicitLimit(true)` or something like that, and customize default JdbcTaskRepository accordingly

**Comment by rafal-kowalski** [comment]
When we encountered this problems we were using v6.0, but updating to v9.2 did not help with this unfortunately.

Since we were trying to debug and fix this, currently we have 3 indexes on execution_time column:
`create index scheduled_picked_execution_time_asc
    on scheduled_tasks (picked, execution_time asc);`
`create index scheduled_tasks_execution_time
    on scheduled_tasks (execution_time);`
`create index scheduled_tasks_execution_time_picked
    on scheduled_tasks (execution_time, picked);`
I've run analyse on those two queries, here are results:
`explain analyse select * from scheduled_tasks where picked = false and execution_time <= now() order by execution_time asc;`
<pre>Sort  (cost=5677234.53..5706813.48 rows=11831581 width=328) (actual time=10024.741..12948.933 rows=10557745 loops=1)
  Sort Key: execution_time
  Sort Method: external merge  Disk: 2800384kB
  ->  Seq Scan on scheduled_tasks  (cost=0.00..2507890.63 rows=11831581 width=328) (actual time=0.011..5503.702 rows=10557745 loops=1)
        Filter: ((NOT picked) AND (execution_time <= now()))
        Rows Removed by Filter: 2046169
Planning time: 0.112 ms
Execution time: 13531.993 ms</pre>
and with limit:
`explain analyse select * from scheduled_tasks where picked = false and execution_time <= now() order by execution_time asc limit 100;`
<pre>Limit  (cost=0.56..89.84 rows=100 width=328) (actual time=27.692..27.746 rows=100 loops=1)
  ->  Index Scan using scheduled_tasks_execution_time on scheduled_tasks  (cost=0.56..10654312.96 rows=11933779 width=328) (actual time=27.690..27.739 rows=100 loops=1)
        Index Cond: (execution_time <= now())
        Filter: (NOT picked)
        Rows Removed by Filter: 45
Planning time: 0.205 ms
Execution time: 27.808 ms</pre>
Currently there are around 12 milion tasks scheduled.

**Comment by rafal-kowalski** [comment]
We have Postgres query time metrics, and it clearly shows that tasks per sec throughput is correlated or caused by execution time and also all the other evidence points that this is the cause, here are the stats:
~60 tasks per second
<img width="1129" alt="Zrzut ekranu 2021-01-12 o 16 40 27" src="https://user-images.githubusercontent.com/12628307/104337444-c8f2ad00-54f5-11eb-9135-85ca5d2c0d9b.png">
~2k tasks per second
<img width="1174" alt="Zrzut ekranu 2021-01-12 o 16 41 58" src="https://user-images.githubusercontent.com/12628307/104337453-cbed9d80-54f5-11eb-9995-d0775bbf55ae.png">

**Comment by kagkarlsson** [comment]
Interesting query-stats (btw, what tool are you using to track that?). They support what you are saying. 
Are posgres switching between the two plans during the same run?

**Comment by kagkarlsson** [comment]
Found this, though your results are saying something else:

https://stackoverflow.com/a/32777048

**Comment by kagkarlsson** [comment]
It would be very interesting to know if changing it to `LIMIT` solves your issue. Is it possible for you build a modified local version and test it?

**Comment by rafal-kowalski** [comment]
This is the tool https://www.percona.com/software/database-tools/percona-monitoring-and-management 

Yes, it looks like postgres is switching between index scan and sequential scan during processing
<img width="1629" alt="Zrzut ekranu 2021-01-14 o 10 22 04" src="https://user-images.githubusercontent.com/12628307/104570558-6236d600-5652-11eb-9a7c-781b5074ce6a.png">
16 milion tasks added to process around 1.11 14:40 (different colors distinct different task types), looks like it started with index scan then switched to sequential scan with some spikes during processing.

Here' s what I found https://stackoverflow.com/questions/32707682/sql-limit-vs-jdbc-statement-setmaxrows-which-one-is-better but some of the links are dead, mainly those referencing postgres driver's code.

As per your suggestion I will try to test locally if explicitly setting LIMIT will help.

**Comment by rafal-kowalski** [comment]
Also exact problem described in 2006 so it could've been changed already https://www.postgresql-archive.org/Limit-vs-setMaxRows-issue-td2170723.html

**Comment by kagkarlsson** [comment]
> As per your suggestion I will try to test locally if explicitly setting LIMIT will help.

Thank you, that is very helpful!

**Comment by rafal-kowalski** [comment]
I've managed to reproduce this behaviour locally. I've dumped our production `scheduled_tasks` data (around 5 milion rows at the moment) and imported it to my local Postgres instance with `auto_explain` enabled so I could see logs from query planner.
With unmodified db-scheduler query:
<pre>LOG:  duration: 94114.872 ms  plan:
	Query Text: select * from scheduled_tasks where picked = $1 and execution_time <= $2  order by execution_time asc
	Sort  (cost=3269807.11..3282304.96 rows=4999140 width=283) (actual time=94113.330..94113.928 rows=60 loops=1)
	  Sort Key: execution_time
	  Sort Method: external merge  Disk: 1215456kB
	  ->  Seq Scan on scheduled_tasks  (cost=0.00..714403.09 rows=4999140 width=283) (actual time=5640.474..46456.248 rows=5008311 loops=1)
	        Filter: ((NOT picked) AND (execution_time <= '2021-01-14 21:11:52.615412+01'::timestamp with time zone))
	        Rows Removed by Filter: 579589

LOG:  duration: 95575.271 ms  plan:
	Query Text: select * from scheduled_tasks where picked = $1 and execution_time <= $2  order by execution_time asc
	Sort  (cost=3270030.71..3282529.40 rows=4999473 width=283) (actual time=95571.879..95572.384 rows=60 loops=1)
	  Sort Key: execution_time
	  Sort Method: external merge  Disk: 1215448kB
	  ->  Seq Scan on scheduled_tasks  (cost=0.00..714450.74 rows=4999473 width=283) (actual time=7198.640..48740.775 rows=5008254 loops=1)
	        Filter: ((NOT picked) AND (execution_time <= '2021-01-14 21:13:28.442994+01'::timestamp with time zone))
	        Rows Removed by Filter: 579646
</pre>
these results were extremely slow - 10x times slower than production metrics (probably due to different hardware or postgres configuration, I not exactly sure but I don't think that its relevant).

With modified db-scheduler query (added `[...]execution_time asc LIMIT " + limit,` at the end of query):
<pre>
LOG:  duration: 9.860 ms  plan:
	Query Text: select * from scheduled_tasks where picked = $1 and execution_time <= $2  order by execution_time asc LIMIT 60
	Limit  (cost=0.43..72.59 rows=60 width=283) (actual time=5.035..8.627 rows=60 loops=1)
	  ->  Index Scan using scheduled_tasks_execution_time_picked on scheduled_tasks  (cost=0.43..6014156.55 rows=5000715 width=283) (actual time=5.018..6.490 rows=60 loops=1)
	        Index Cond: ((execution_time <= '2021-01-14 21:23:43.553454+01'::timestamp with time zone) AND (picked = false))
	        Filter: (NOT picked)

LOG:  duration: 14.381 ms  plan:
	Query Text: select * from scheduled_tasks where picked = $1 and execution_time <= $2  order by execution_time asc LIMIT 60
	Limit  (cost=0.43..72.59 rows=60 width=283) (actual time=6.305..12.186 rows=60 loops=1)
	  ->  Index Scan using scheduled_tasks_execution_time_picked on scheduled_tasks  (cost=0.43..6014179.53 rows=5000715 width=283) (actual time=6.278..8.688 rows=60 loops=1)
	        Index Cond: ((execution_time <= '2021-01-14 21:23:43.871864+01'::timestamp with time zone) AND (picked = false))
	        Filter: (NOT picked)
</pre>
In both cases scheduler was set to 20 threads, polling-interval to 10s, rest of properties were default.

Also I might know why you didn't encounter this issue when you were load testing. Before I used my actual production data I've generated 10 milion identical tasks scheduled to execute now but then query planner always used index scan. Probably this behaviour might depend on how many different task types there are currently scheduled and execution_time distribution.

**Comment by kagkarlsson** [comment]
Thanks a lot, great job! Yeah, might be testdata-distribution and luck that saved my load test. 

This is good evidence that setting LIMIT will improve performance for some cases so I agree that it should be possible using db-scheduler. Was this something you were willing to contribute to?

My suggestion is:

* Expand [JdbcCustomization](https://github.com/kagkarlsson/db-scheduler/blob/master/db-scheduler/src/main/java/com/github/kagkarlsson/scheduler/jdbc/JdbcCustomization.java) with something like `supportsExplicitQueryLimitPart(int limit)`, `getQueryLimitPart(int limit)`
* Make `AutodetectJdbcCustomization` detect postgres
* Create a customization for postgres overriding new method `getQueryLimitPart `
* Use explicit query-limit in `JdbcTaskRepository` if supported by JdbcCustomization

**Comment by rafal-kowalski** [comment]
Sure, I will make PR with Postgres customization

**Comment by kagkarlsson** [comment]
I have released your contribution in 9.3. Thanks!
https://github.com/kagkarlsson/db-scheduler/releases/tag/9.3
