### ISSUE TITLE
Dynamically create recurring tasks

### ISSUE THREAD

**Issue by matthjes** [kagkarlsson/db-scheduler#17]
Hi,

I'd like to dynamically create recurring tasks, e.g. for periodically updating some data after a user account has been created. However, I'm not sure how to do this with the current task types:

* It's not possible to provide task data to a `RecurringTask` because the generic parameter is set to `Void`.
* `OneTimeTask` is not recurring, but I can create different instances with individual task data.

I think what I would need is a mix of both: A recurring task for which I can create new instances with individual task data. So I would have one task (e.g. `UpdateAccountDataTask`) with one instance for each account.

Is this possible with the current state or do I need to create my own task implementation?

**Comment by kagkarlsson** [comment]
Hello! :)

Firstly, are you saying that you will have one RecurringTask for every user? What volume of users do you anticipate? Why would you not prefer having a single RecurringTask that updates all users?

Currently, it is not supported to schedule several new executions in the CompletionHandler, though I have considered adding it. I suppose a solution would be to define a custom CompletionHandler with access to the `SchedulerClient`? But yes, a custom task-implementation would be necessary.

**Comment by kagkarlsson** [comment]
Will the data change after every execution?

**Comment by matthjes** [comment]
I'd like to distribute the work of updating the data across multiple instances (that is why I'm looking into db-scheduler as a clustered solution). If I have only a single task that updates all users, then multiple instances do not make sense. So what I need is a list of task / task instances in a DB shared across multiple instances and the tasks / task instances are executed across these instances.

At the beginning there will be only about 500 users, however, this number can go up.

The data will not change after every execution. The task is to perform a REST call to some other service to get some information and update the local database accordingly.

For now I'm using a `Task` with the `CompletionHandler` from the `RecurringTask`...

**Comment by kagkarlsson** [comment]
Ok, I understand. Yeah, you are taking the correct approach using the `CompletionHandler` from `RecurringTask`. They are meant to be pluggable to get the behavior you want :)

**Comment by matthjes** [comment]
Ok, then the Problem is that the constructor for the `OnCompleteReschedule` `CompletionHanderl` is not public and I cannot access it (currently I just copied the code). Maybe this can be changed in a future update (the same goes for the implementations of the `DeadExecutionHandler`.

Thanks for the help :)

**Comment by kagkarlsson** [comment]
Ok, yeah I see that now. I fixed the `OnCompleteReschedule` constructor in version `2.2`, should be available soon. `DeadExecutionHandler` should be fine? (public static by default)

**Comment by matthjes** [comment]
Yes, you are right, it's only the constructors for the `CompletionHandler` implementations.

Thanks for the help! :) :+1:

**Comment by kagkarlsson** [comment]
No problem! Let me know if there are other features you are missing :)
