### ISSUE TITLE
Failure logging

### ISSUE THREAD

**Issue by dmoidl** [kagkarlsson/db-scheduler#170]
Hi @kagkarlsson 👋 

I'm currently looking for a scheduler lib to use within our project and so I decided to give `db-scheduler` a try. So far it looks good and seems to cover pretty much everything we need at the moment. 

There is, however, one thing that bothers me and that could be a possible blocker for us: it logs each task failure as an `ERROR` ([here](https://github.com/kagkarlsson/db-scheduler/blob/9.3/db-scheduler/src/main/java/com/github/kagkarlsson/scheduler/Scheduler.java#L359)). The way I see it, that doesn't make sense at all. I'd argue that from the perspective of the `Scheduler`, a task failure can hardly be an _error_, given the library itself provides a recovery mechanism (`FailureHandler`) used by the `Scheduler`.

I understand this may sound as a rather minor issue, but here's a real-life scenario to support my claim that it's not 🙂 : we plan to use the `db-scheduler` mainly for sending webhook notifications to registered third parties, each notification being a standard HTTP request to some URL. This means that such a task, i.e. a request, can easily fail and that's totally out of our control. Therefore we need to anticipate a failure and react accordingly - in our case by trying again later or disabling the webhook altogether if it failed for more than X times in a row.
Now, `db-scheduler` provides all the necessary tooling to achieve this, such as: 
 - the `CustomTask` type
 - the `FailureHandler` letting me reschedule the task or stop the execution based on the number of consecutive failures
 - the `Schedule` allowing me to easily implement type-task-agnostic exponential backoff mechanism for retries (nice 👍 )

However, if I do actually implement things in the way I described above, I simply _have to_ accept that on each task failure there will be an `ERROR` message in our logs. Taking into consideration that there may be rather high number of webhook notifications being sent each hour, day, etc. _and_ the failure likelihood of each is somewhat high, it would imply that our logs would be totally spammed by `ERROR`s produced by the `Scheduler`. This is obviously not acceptable.

I know I could work around this issue. I could disable logging for the `Scheduler` class for good, but then I wouldn't get even the real errors caused e.g. by misconfiguration. I could also _not_ use `FailureHandler` at all and basically duplicate the error-catching and handling mechanism directly in the `CompletionHandler`, but that kinda defeats the whole purpose of having the `FailureHandler` available 🙂 

Therefore, I propose changing the log level of log records in question to something like `DEBUG`. If users want or need to log each failure as an error, they still easily can by implementing a `FailureHandler` that does so. I feel like that should be the correct usage of the whole library. WDYT?

**Comment by kagkarlsson** [comment]
> Therefore, I propose changing the log level of log records in question to something like DEBUG. If users want or need to log each failure as an error, they still easily can by implementing a FailureHandler that does so. I feel like that should be the correct usage of the whole library. WDYT?

I agree. Thorough analysis 👍 . This has also been pointed out to me by another user of the library 😄 . Only thing I am uncertain about is how to accomodate the users that have the perspective that they _do_ want logging of unexpected exceptions. They might already rely on it. 

How about making it a bit easier to configure by providing a SchedulerBuilder-method for setting default level for failures, like `.failureLogging(Level, boolean logStacktrace)`? We can make it a "breaking change" and set the default to level=debug, logStacktrace=true, but provide an example in release-notes on how to get the old behavior.

**Comment by dmoidl** [comment]
Yeah, that's something I wasn't really sure how to handle. But making it configurable is likely the way to go. The only other solution that comes to my mind is the one I mentioned [here](https://github.com/kagkarlsson/db-scheduler/pull/171#discussion_r567678881), but I guess that just moves the problem to a different place after all 🙂 

I'll implement the configuration method you proposed and let's see how that works out 🙂  There is, however at least one small issue with that approach that I can see right away: SLF4J doesn't provide any Enum for its log levels so we'll have to create one ourselves... No big deal, but it's inconvenient 🤷‍♂️ 

I don't think I'll have time for it today so expect an update of the PR tomorrow 🙂

**Comment by kagkarlsson** [comment]
> The only other solution that comes to my mind is the one I mentioned here, but I guess that just moves the problem to a different place after all 🙂

Yeah, I was initially going for that, but it is sort of forcing users to override default FailureHandlers just to get this pretty basic feature, which didn't feel right. They might then miss out on future changes to the FailureHandler.

Yeah, unfortunately need to create our own enum.. 

Thanks alot, most appreciated!

**Comment by kagkarlsson** [comment]
Released in v9.4

**Comment by kagkarlsson** [comment]
🎉 This issue has been resolved in `v16.9.0` ([Release Notes](https://github.com/kagkarlsson/db-scheduler/releases/tag/v16.9.0))
