### ISSUE TITLE
Handling missed executions

### ISSUE THREAD

**Issue by spmistry** [kagkarlsson/db-scheduler#189]
Is there any special handling for missed executions?
Currently it seems like the the next schedule window will always be the nearest time in future.

What can be done in a situation where schedules were created and after a crash/restart (consider a delay) the app has a bunch of missed schedules that should be accounted for?

**Comment by kagkarlsson** [comment]
Yeah, there are no guarantees for RecurringTasks, sort of mentioned in the _Gotcha_ section here: https://github.com/kagkarlsson/db-scheduler#things-to-note--gotchas

If you want guarantees for an execution for every Instant in a `Schedule`, one way is to have a recurring task that simply spawns a number of executions, one for each Instant

**Comment by kagkarlsson** [comment]
Might be possible to have a CompletionHandler that inspects the last execution-time and select the next execution-time accordingly, but may be gotchas there aswell (have not checked)

**Comment by kagkarlsson** [comment]
It is also possible to track state in the task ala [TrackingProgressRecurringTaskMain.java](https://github.com/kagkarlsson/db-scheduler/blob/master/examples/features/src/main/java/com/github/kagkarlsson/examples/TrackingProgressRecurringTaskMain.java)
