### ISSUE TITLE
Feature request: have recurrent tasks with task_data

### ISSUE THREAD

**Issue by ruifscouto** [kagkarlsson/db-scheduler#19]
Hello,

The matter at hands is a feature request to be able to specify additional data on recurrent tasks.
Even though extending classes to add the task_data field appears to be possible, there is no way of actually specifying new data through the execute() method on the task itself. 
There should be a handle on the context through which you could set data manually.

At the moment, my alternative has been to use oneTimeTasks and re-schedule them with a new instance (with which I specify new data).

Would be great if you could add support for this in a future version.

Thanks

**Comment by kagkarlsson** [comment]
Thanks for the feature request. Working on this along with some redesign of the `CompletionHandler`.

**Comment by tomaszglinski** [comment]
Hi, any news to that? I am also interested...

**Comment by kagkarlsson** [comment]
I am working on a larger refactoring to enable this feature, unfortunately progressing a bit slowly due to time constraint. I plan on finishing within a couple of weeks.

**Comment by tomaszglinski** [comment]
Cool, will check it next week :-)

pt., 6 kwi 2018, 16:22 użytkownik Gustav Karlsson <notifications@github.com>
napisał:

**Comment by kagkarlsson** [comment]
Closing this issue as it was fixed in 3.0. Please let me know if this do not solve your requirement.
