### ISSUE TITLE
SchedulerClient context same as the Scheduler - Spring Boot

### ISSUE THREAD

**Issue by LeslieMurphy** [kagkarlsson/db-scheduler#193]
I tried to use SchedulerClient to remove a task - but it issues message:

c.g.k.scheduler.jdbc.JdbcTaskRepository  : Failed to find implementation for task with name 'my-cron-task'. Execution will be excluded from due. Either delete the execution from the database, or add an implementation for it. The scheduler may be configured to automatically delete unresolved tasks after a certain period of time.

I traced this down to the JdbcTaskRepository.this.taskResolver.resolve(taskName) code in JdbcTaskRepository method map.  The task hashmap for the scheduler instance has my task, however the context created for the SchedulerClient does not share in this context.  

What is the proper way to accomplish this?  I am using Spring Boot.  Is there a Scheduler.getClientContext() capability?

Sample code:

```
@Qualifier("dataSource")
@Autowired
DataSource dataSource;

var client = SchedulerClient.Builder.create(dataSource).build();

TaskInstanceId taskInstanceId = TaskInstanceId.of("my-cron-task", "recurring");
var myTask = client.getScheduledExecution(taskInstanceId);

// Even thought the task exists in the Scheduler, it is not found in the SchedulerClient

if (!myTask.isEmpty()) {
        client.cancel(taskInstanceId);
        // TODO create a new cron schedule
        }
```

It will work if I provide my bean as input to the constructor - but if I had multiple schedule beans I would obviously have to change this code.  Hopefully there is a way to get a SchedulerClient instance tied to the overall scheduler that is running.

```
 @Autowired
 ApplicationContext context;

RecurringTask<Void> schedBean = context.getBean(RecurringTask.class);
var client = SchedulerClient.Builder.create(dataSource, schedBean).build();


```

**Comment by kagkarlsson** [comment]
> Hopefully there is a way to get a SchedulerClient instance tied to the overall scheduler that is running.

Yes, the `Scheduler` (which is in your Spring context) also implements the `SchedulerClient` interface, so for Spring Boot you should not have to create it via `SchedulerClient.Builder`. I can see that is not mentioned in the doc, will make a note of improving it 👍

**Comment by kagkarlsson** [comment]
So a question first, why are you trying to cancel `my-cron-task`?

The problem you see is caused by the task having been removed from the Scheduler configuration, i.e. it is not known to the current Scheduler (it likely was at some point). That is an expected scenario when you have some recurring-task that you just do not need anymore, and remove the mapping and code for it. Is this case, the execution will still be in the database, but it will be removed after 14 days (configurable) if no mapping is set up during that time. Until that happens, you will see this warning on every startup of a Scheduler-instance: 

```
c.g.k.scheduler.jdbc.JdbcTaskRepository : Failed to find implementation for task with name 'my-cron-task'. Execution will be excluded from due. Either delete the execution from the database, or add an implementation for it. The scheduler may be configured to automatically delete unresolved tasks after a certain period of time
```

Currently there is no good way to remove the execution via the `SchedulerClient` if it does not also have a mapping. I can see that is a slight weakness. We might add a feature where you could give the `Scheduler` knowledge of obsolete tasks, that that it can quietly remove them..

**Comment by kagkarlsson** [comment]
See also doc:

> ⚙️ .deleteUnresolvedAfter(Duration)
> The time after which executions with unknown tasks are automatically deleted. These can typically be old recurring tasks that are not in use anymore. This is non-zero to prevent accidental removal of tasks through a configuration error (missing known-tasks) and problems during rolling upgrades. Default 14d.

**Comment by LeslieMurphy** [comment]
> > Hopefully there is a way to get a SchedulerClient instance tied to the overall scheduler that is running.
> 
> Yes, the `Scheduler` (which is in your Spring context) also implements the `SchedulerClient` interface, so for Spring Boot you should not have to create it via `SchedulerClient.Builder`. I can see that is not mentioned in the doc, will make a note of improving it 👍
> 
> It is also possible to get a `SchedulerClient` from inside an ExecutionHandler, see for example this example: https://github.com/kagkarlsson/db-scheduler/blob/master/examples/features/src/main/java/com/github/kagkarlsson/examples/SpawningOtherTasksMain.java#L32

That works perfectly.  In Spring Boot:

 ```
import com.github.kagkarlsson.scheduler.Scheduler;
@Autowired
Scheduler dbScheduler;

// use dbScheduler as client
List<ScheduledExecution<Object>> schedExecs = dbScheduler.getScheduledExecutions();
// do something with list
 TaskInstanceId taskInstanceId = TaskInstanceId.of("my-cron-taskBEAN", "recurring");
 var myTask = dbScheduler.getScheduledExecution(taskInstanceId);
if (!myTask.isEmpty()) {
           // do something with  a single specific execution 
           dbScheduler.cancel(taskInstanceId);  // for example we can cancel the task
        }

```

**Comment by LeslieMurphy** [comment]
> So a question first, why are you trying to cancel `my-cron-task`?
> 
> The problem you see is caused by the task having been removed from the Scheduler configuration, i.e. it is not known to the current Scheduler (it likely was at some point). That is an expected scenario when you have some recurring-task that you just do not need anymore, and remove the mapping and code for it. Is this case, the execution will still be in the database, but it will be removed after 14 days (configurable) if no mapping is set up during that time. Until that happens, you will see this warning on every startup of a Scheduler-instance:
> 
> ```
> c.g.k.scheduler.jdbc.JdbcTaskRepository : Failed to find implementation for task with name 'my-cron-task'. Execution will be excluded from due. Either delete the execution from the database, or add an implementation for it. The scheduler may be configured to automatically delete unresolved tasks after a certain period of time
> ```
> 
> Currently there is no good way to remove the execution via the `SchedulerClient` if it does not also have a mapping. I can see that is a slight weakness. We might add a feature where you could give the `Scheduler` knowledge of obsolete tasks, that that it can quietly remove them..

What I would like to be able to do is allow end users to alter the cron schedule on a task (via a web service / controller interaction). This change would happen without requiring an application restart. 

I don't want to remove the task.  I was thinking perhaps I would need to have logic that would remove the task and immediately add it back in as a workaround if there is not an API to change the schedule on an existing cron task.

As a nice to have it would be helpful to allow a task to be suspended temporarily, then re-enabled.  That is not something I really need at this time.

Does my usee case make sense?

**Comment by kagkarlsson** [comment]
> As a nice to have it would be helpful to allow a task to be suspended temporarily, then re-enabled. That is not something I really need at this time.

There is a feature-request for adding the ability to pause a recurring-task. For now, a hacky workaround is to reschedule it way into the future 

> What I would like to be able to do is allow end users to alter the cron schedule on a task (via a web service / controller interaction). This change would happen without requiring an application restart.
> 
> I don't want to remove the task. I was thinking perhaps I would need to have logic that would remove the task and immediately add it back in as a workaround if there is not an API to change the schedule on an existing cron task.

Ok, I understand. The approach of db-scheduler, unlike Quartz I think, is that schedules are not persistent, they live in the application config (the `Schedule`). The next execution-time will be determined given the `Schedule` the `Task` is associated with.

If you want to provide runtime user-triggered changes to the schedule, I think you would need to persist the `Schedule` in the `task_data`. Write a custom CompletionHandler that selects the next execution-time given the Schedule in the task_data. When the user selects a new Schedule, reschedule the task according to the new Schedule and persist the new Schedule in serialized form as task_data

There is currently no example of this, but I could try and add one. It should be possible, but it will not be via a standard `RecurringTask`

**Comment by LeslieMurphy** [comment]
THANKS!  If you can provide an example that would be greatly appreciated.  The ability to change the schedule without an app restart is not an immediate blocker for me, so there is not a huge sense of urgency.

I love that db-scheduler "just worked" right out of the box.  Kudos!

**Comment by kagkarlsson** [comment]
An example:

https://github.com/kagkarlsson/db-scheduler/blob/persistent_schedule/examples/features/src/main/java/com/github/kagkarlsson/examples/PersistentDynamicScheduleMain.java#L33

There are some room for improvement, but that is the general idea. Will try and get some examples for json-serialization as well, I think that is a bit more robust serialization-strategy.

> I love that db-scheduler "just worked" right out of the box. Kudos!

Thanks! :)

**Comment by LeslieMurphy** [comment]
Great news. That worked for me! Thank you again.

The one thing that I was not expecting is that the schedule persists in the DB (serialized into column TASK_DATA), such that at application restart the value in the DB takes precedent over the value provided in the code.

This will not be a problem for me in the actual application, as I would always be setting the cron schedule to the same value during initialization as it was set  to the last time the app was shutdown.

However, is this the expected behavior?


```
// At startup, ConfigurationProperties attribute cronFileImportSchedule used to define the recurring task schedule
// HOWEVER if the task already exists, the value from the DB is used - the cronPattern value provided here is ignored

@Autowired
ScheduleConfiguration cfg;

@Autowired
Scheduler dbScheduler;

@Bean
CustomTask<SerializableCronSchedule> scheduled_task() {

String cronPattern = cfg.getCronFileImportSchedule(); 
final CustomTask<SerializableCronSchedule> cronTask = Tasks.custom("dynamic-recurring-task", SerializableCronSchedule.class)

                .scheduleOnStartup(RecurringTask.INSTANCE, new SerializableCronSchedule(cronPattern), identity()) 
                
                .onFailure((executionComplete, executionOperations) -> {
                    final SerializableCronSchedule persistedSchedule = (SerializableCronSchedule) (executionComplete.getExecution().taskInstance.getData());
                    executionOperations.reschedule(executionComplete, persistedSchedule.getNextExecutionTime(executionComplete));
                })
                .execute((taskInstance, executionContext) -> {
                    final SerializableCronSchedule persistentSchedule = taskInstance.getData();
                    
                    String ts = LocalDateTime.now()
                           .format(DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss.SSS"));
                    System.out.println(ts + " Ran using persistent cron schedule: " + persistentSchedule.getCronPattern());

                    return (executionComplete, executionOperations) -> {
                        executionOperations.reschedule(
                                executionComplete,
                                persistentSchedule.getNextExecutionTime(executionComplete)
                        );
                    };
                });

        return cronTask;

```

Sample log files for the scheduler

cronPattern from cfg: */20 * * * * *
2021-04-06 19:17:41.110 Ran using persistent cron schedule: */20 * * * * *
2021-04-06 19:18:01.146 Ran using persistent cron schedule: */20 * * * * *
2021-04-06 19:18:21.173 Ran using persistent cron schedule: */20 * * * * *

Changing cron schedule to 12 * * * * ?
2021-04-06 19:20:12.308 Ran using persistent cron schedule: 12 * * * * ?
2021-04-06 19:21:12.414 Ran using persistent cron schedule: 12 * * * * ?

After restart

cronPattern from cfg: */20 * * * * *
2021-04-07 06:02:12.374 Ran using persistent cron schedule: 12 * * * * ?
2021-04-07 06:03:12.502 Ran using persistent cron schedule: 12 * * * * ?

**Comment by kagkarlsson** [comment]
> The one thing that I was not expecting is that the schedule persists in the DB (serialized into column TASK_DATA), such that at application restart the value in the DB takes precedent over the value provided in the code.

This was intentional but could be changed I think. If a user(?) updates the schedule runtime, would you still want an app-restart to reset to the original schedule? Then I did not fully understand your use-case..

**Comment by LeslieMurphy** [comment]
You understand my use case correctly :-)  I would never need to change an existing schedule at application startup.

It struck me that perhaps the API should somehow make the schedule portion (initialData) optional?  Since the implementation loads the serialization from the DB and ignores what was passed in, it seems providing a schedule as part of defining the task is only needed the when the cron task is initially created.

This is pretty nuanced, I realize. Thankfully, it's working for what I need to accomplish.  Maybe there is a way to simply this in the future.
