### ISSUE TITLE
Ability to decorate task execution

### ISSUE THREAD

**Issue by reda-alaoui** [kagkarlsson/db-scheduler#194]
Thank you for this wonderful library.

We need to decorate all of our task executions for miscellaneous things:
* setup some ThreadLocal values
* trigger specific processes on failure
* define transactions

`SchedulerBuilder` only accepts the abstract class `Task` as the task type. Since it is an abstract class, I had to rely on `byte-buddy` to create a proxy of this type to perform delegation.

Would you accept a pull request turning `Task` into an interface?
In the PR we would:
* rename `Task` into `AbstractTask`
* create an interface named `Task`
* make `AbstractTask` implement `Task`

If we want to avoid breaking change, we can let `Task` being an abstract class and maybe name the new interface `TaskDefinition`?

**Comment by kagkarlsson** [comment]
Hi! It probably would be a good direction to evolve the `Task` into an interface. Not sure how easy/hard it is to do though. On first glance it looks rather straight-forward.

Question though: is it not possible to decorate the underlying `ExecutionHandler`? https://github.com/kagkarlsson/db-scheduler/blob/master/db-scheduler/src/main/java/com/github/kagkarlsson/scheduler/task/ExecutionHandler.java

**Comment by reda-alaoui** [comment]
In my case, ability to decorate the ExecutionHandler is not enough.

In our application, people define tasks from different spots. To they declare `Task` instances with `Tasks` factories. Those instances are then injected in a scheduler provider wrapping `db-scheduler`. The provider is responsible for creating a `SchedulerBuilder` and add the collected `Task`. It is also responsible for making sure each task is executed in the correct conditions. But at this point, the provider can't dissociate easily the `Task` from the `ExecutionHandler`. And there is no facility allowing to create a `Task` from an existing `Task`.

I opened #195 that turns `Task` into an interface.

**Comment by kagkarlsson** [comment]
Released this in 10.2.

**Comment by kagkarlsson** [comment]
Thank you for contributing :)
