### ISSUE TITLE
Try to execute tasks due now() really now

### ISSUE THREAD

**Issue by tomaszglinski** [kagkarlsson/db-scheduler#20]
A little related to #16 yet different: when I schedule a new task with due time now(), scheduler could check if it is capable of starting the job immediately, to avoid unnecessary waiting.

**Comment by kagkarlsson** [comment]
Yeah I see what you mean. It is sort of a special case for #16 . I agree this would be a nice feature to have.

**Comment by kagkarlsson** [comment]
I think I will prioritize adding this feature.

**Comment by tomaszglinski** [comment]
Couldnt you store it already as started and immediately add to execution
queue? I mean do things separately from the background job that looks for
things to do

sob., 14 kwi 2018, 13:23 użytkownik Gustav Karlsson <
notifications@github.com> napisał:

**Comment by kagkarlsson** [comment]
Am not super-happy about that approach as it complicates things, and introduces too much of a special case. As long as you are not calling `scheduleExecution` in a transaction you are alright though..

**Comment by kagkarlsson** [comment]
Am considering implementing this again, but change it into a method on the `SchedulerClient`, where you could give the `Scheduler` a "hint" about there being pending executions. The `Scheduler`can then trigger its normal check now, instead of its regular interval.

**Comment by kagkarlsson** [comment]
Merging a solution for this (PR #37 ) into `master´.  

Must be explicitly enabled on the builder with `.enableImmediateExecution()`. 

And alternative is also exposed through the method `Scheduler.triggerCheckForDueExecutions()` which will cause the Scheduler to wake-up.

**Comment by kagkarlsson** [comment]
Fix in `4.1`

**Comment by kagkarlsson** [comment]
🎉 This issue has been resolved in `v15.2.0` ([Release Notes](https://github.com/kagkarlsson/db-scheduler/releases/tag/v15.2.0))
