### ISSUE TITLE
Why fetchScheduledExecutions does not return running executions?

### ISSUE THREAD

**Issue by reda-alaoui** [kagkarlsson/db-scheduler#210]
Hello,

I need to create a screen to monitor the scheduler. In the screen, we want to list all informations we have about the scheduled tasks.
The query methods that look like the most interesting for this task are `SchedulerClient.fetchScheduledExecutions`. But their javadocs specify `Currently running executions are not returned`.
What is the rationale behind this? Is there something preventing us from doing that? Or is that only a missing feature that I could easily add with a contribution?

**Comment by reda-alaoui** [comment]
Oh sorry didn't see there was an overloading allowing to specify the ScheduledExecutionsFilter !

**Comment by kagkarlsson** [comment]
The best type of bugs/enhancements are the ones that are already fixed 😄
