### ISSUE TITLE
Query about recurringTask that take longer than expected

### ISSUE THREAD

**Issue by bdhaliwalvl** [kagkarlsson/db-scheduler#212]
Hello,

I am considering using db-scheduler for a use case where there will be a recurringTask that executes every second. I assume if the task takes longer than its allocated time period, then the next task will wait until it the previous completion time + 1 second? Are there any options available to take action on longer than expected recurring tasks - such as cancel the task, log the task has exceeded a time period, etc. If a task fails, will the next task still run?

Thanks,
B

**Comment by kagkarlsson** [comment]
> I assume if the task takes longer than its allocated time period, then the next task will wait until it the previous completion time + 1 second? 

Correct, that what the normal `FixedDelay`schedule does. I suppose you could create a `Schedule` that also uses `executionComplete.getExecution().executionTime` for calculating the next execution-time. Then I don't think you would miss any executions. Though should the task take longer than 1s it would get more and more delayed.

> Are there any options available to take action on longer than expected recurring tasks - such as cancel the task, log the task has exceeded a time period, etc

The scheduler cannot stop threads that is taking long than expected to execute. You would have to implement that yourself, by checking how long it has run for in you loop... or set appropriate timeouts. 

I have considered adding a helper thread that regularly checks if any executions has been running for a long time and for example logging a warn or something.. nothing in place currently, but you could implement it yourself if you need it

> If a task fails, will the next task still run?

That is determined by the `FailureHandler` so you have control over that. Typically for `RecurringTasks`, they are re-scheduled to the next time according to the `Schedule` but that is customizable


* You could also consider having a `RecurringTask` that every minute created 60 `OneTimeTasks` for the next minute. Those will be able to be run in parallell though, so might not be what you want. 
* Currently I think the scheduler polls every 10s, so you might need to tune that for 1s recurring tasks (possibly enable immediate execution)
