### ISSUE TITLE
How can I see history of all task execution

### ISSUE THREAD

**Issue by denis-samodurov** [kagkarlsson/db-scheduler#213]
I tried to find the way to store info about all task execution and didn't some way. Is there a way to do this?

**Comment by kagkarlsson** [comment]
Hi! Could you elaborate on what you are trying to do here? It is possible to store data with an execution

```
scheduler.schedule(mytask.instance("instance-id", mydata), Instant.now());
```

**Comment by kagkarlsson** [comment]
Oh now I see. db-scheduler does not keep a record of previously executed tasks. You might add a custom CompletionHandler that, in addition to removing the execution, records it in some history-table or similar.

**Comment by denis-samodurov** [comment]
> Oh now I see. db-scheduler does not keep a record of previously executed tasks. You might add a custom CompletionHandler that, in addition to removing the execution, records it in some history-table or similar.

I got the idea, thank you!

I think this is useful and it would be great if this feature will be a part of the library. I understand that it can hit the performance (extra insert), so it can be as an optional part that switches on only after a developer configure it (_application.properties_ for spring boot or _Scheduler configuration_).

If it seems ok for you, I want to design a solution to share with you for discussion and after that, I will implement it.

**Comment by kagkarlsson** [comment]
On vacation, will answer in detail later. Might be possible to add via some sort of module approach, but worried about complexiry
