### ISSUE TITLE
A way to share scheduled tasks table between different services

### ISSUE THREAD

**Issue by virtual-machinist** [kagkarlsson/db-scheduler#214]
I have a case when there's several clustered services sharing a single database. They have different one-time and recurring tasks that must be synchronized between nodes.
Is there a way to make use of a single table for all services without them removing tasks that they cannot resolve? My current workaround is setting `delete-unresolved-after` config variable to something very long and doing a restart before that time passes. Obviously this is not very elegant and leads to mandatory downtime (not even sure it works as the default 14 days haven't passed yet :smile:).
I wouldn't want to start making a table for each service and doubt it's even a sustainable solution as the number of services increases.
Can there be an option to either disable unresolved task removal or add some column such as `cluster_id`/`scheduler_id` so that task resolution is restricted to tasks of a single cluster? This might even help with #200.

**Comment by kagkarlsson** [comment]
Yeah, currently the recommended approach for this use-case is to have multiple tables, one for each service. We might have a look at disabling the auto-removal (at your own peril) though..
