### ISSUE TITLE
`ExecutorService` for each Task

### ISSUE THREAD

**Issue by ahilmer** [kagkarlsson/db-scheduler#215]
Hi,

is it possible to specify for each task an own `ExecutorService` or some similar functionality?

I want to prevent that one task is eating all the threads of the `ExecutorService`.

**Comment by kagkarlsson** [comment]
Currently this is not something that is easily achieved. The best way currently is to use two separate schedulers backed by two different tables.

That have been suggestions for supporting task-priority to solve this. Is this something that would solve your use-case as well?

**Comment by ahilmer** [comment]
Thanks for your response. 

The idea with the different tables sounds great. This would also then be more meaningful.

**Comment by kagkarlsson** [comment]
Ok, great!
