### ISSUE TITLE
Support R2DBC Spring boot 

### ISSUE THREAD

**Issue by Tuanpm31** [kagkarlsson/db-scheduler#218]
Currently, DataSource is provided by spring jpa or jdbc, with spring web flux, it should support r2dbc.

**Comment by kagkarlsson** [comment]
Thank you for your suggestion. I do not know much about `r2dbc`, could you give an example on what changes need to be made?

**Comment by Ameerjafar** [comment]
can i work on this enhancement?

**Comment by kagkarlsson** [comment]
I am worried this will be quite an invasive change, hence my initial comment (which still stands): 

> Thank you for your suggestion. I do not know much about r2dbc, could you give an example on what changes need to be made?

**Comment by kagkarlsson** [comment]
Unlikely to support
