### ISSUE TITLE
Configuring spring-boot polling strategy

### ISSUE THREAD

**Issue by mixnix** [kagkarlsson/db-scheduler#222]
How to configure Scheduler polling strategy in a project which doesn't explicitly create Scheduler? Sorry if this is stupid question, I couldn't solve this issue on my own.

**Comment by mixnix** [comment]
Found it by reading library code but maybe I can create pull request to add this to README list of properties for Spring boot?

**Comment by kagkarlsson** [comment]
Hi and sorry for the late reply! PRs are much appreciated, please do :)
