### ISSUE TITLE
Bad-looking ExecutePicked logging

### ISSUE THREAD

**Issue by adam-handke** [kagkarlsson/db-scheduler#223]
`com.github.kagkarlsson.scheduler.ExecutePicked` [logs](https://github.com/kagkarlsson/db-scheduler/blob/master/db-scheduler/src/main/java/com/github/kagkarlsson/scheduler/ExecutePicked.java#L82) the start of an execution like this:
> Executing Execution: task=example-task-name, id= ...

As you can see, there are 2 issues:
* Duplicated **_Executi___**
* Redundant capital letter in **_Execution_**

I suggest changing it to one of two opitions:

1. >  Starting execution: task=example-task-name, id= ...

2. > Executing: task=example-task-name, id= ...

The change would require modifying the [toString()](https://github.com/kagkarlsson/db-scheduler/blob/master/db-scheduler/src/main/java/com/github/kagkarlsson/scheduler/task/Execution.java#L75) method of `com.github.kagkarlsson.scheduler.task.Execution` or altering what it returns before a log message is created.

I use the `ExecutePicked` logs frequently while debugging db-scheduler so it would be nice to make the log message look better.

**Comment by kagkarlsson** [comment]
Hehe, this was rather a nitpick 😄 . Not sure I want to change the toString-method, I like it saying it is an `Execution`. So if it is a specific log-message we are looking to improve, I suppose it needs to be customized without using toString

**Comment by adam-handke** [comment]
Another thing that could be improved in `ExecutePicked` logs is logging which execution is "done" after the execution is finished.
[Currently](https://github.com/kagkarlsson/db-scheduler/blob/master/db-scheduler/src/main/java/com/github/kagkarlsson/scheduler/ExecutePicked.java#L84), it's just "Execution done" and that's not very informative when you have many executions running at once.

I'll create a PR which tries to fix these issues.

**Comment by kagkarlsson** [comment]
I am a bit curious as to why you need to debug the scheduler so often, what behavior are you seeing?

**Comment by adam-handke** [comment]
I scheduled many tasks at once, some of which were [custom](https://github.com/kagkarlsson/db-scheduler/blob/master/db-scheduler/src/main/java/com/github/kagkarlsson/scheduler/task/helper/CustomTask.java) or utilized custom failure handlers and wanted to check if all of them are executed correctly. Improved logs are especially useful when browsing through past logs or investigating an execution failure.
