### ISSUE TITLE
Scheduling does not work for periods of 1 minute

### ISSUE THREAD

**Issue by alfr3dosv** [kagkarlsson/db-scheduler#224]
As the title says, I have problems with task programs that run every minute.
At the end of the task it is executed again almost immediately

```
    @Bean
    Task enviarCadaMinuto() {
        Task task = Tasks.recurring("noticarVencimientoSuite1Minuto", fixedDelay(Duration.ofMinutes(1)))
                .execute(this);
        return task;
    }
```

log
**2021-08-24 13:18:51.834  INFO 32871** --- [pool-2-thread-1] c.b.i.c.t.NotificarVencimientoSuiteTask  : Iniciando tarea para notifcar los vencimientos: noticarVencimientoSuite1Minuto_fe07f451-9f82-4c5d-b096-652fefee2cf7
**2021-08-24 13:18:56.840  INFO 32871** --- [pool-2-thread-1] c.b.i.c.t.NotificarVencimientoSuiteTask  : Iniciando tarea para notifcar los vencimientos: noticarVencimientoSuite1Minuto_fe07f451-9f82-4c5d-b096-652fefee2cf7
**2021-08-24 13:19:01.862  INFO 32871** --- [pool-2-thread-1] c.b.i.c.t.NotificarVencimientoSuiteTask  : Iniciando tarea para notifcar los vencimientos: noticarVencimientoSuite1Minuto_fe07f451-9f82-4c5d-b096-652fefee2cf7
**2021-08-24 13:19:06.866  INFO 32871** --- [pool-2-thread-1] c.b.i.c.t.NotificarVencimientoSuiteTask  : Iniciando tarea para notifcar los vencimientos: noticarVencimientoSuite1Minuto_fe07f451-9f82-4c5d-b096-652fefee2cf7
**2021-08-24 13:19:11.871  INFO 32871** --- [pool-2-thread-1] c.b.i.c.t.NotificarVencimientoSuiteTask  : Iniciando tarea para notifcar los vencimientos: noticarVencimientoSuite1Minuto_fe07f451-9f82-4c5d-b096-652fefee2cf7

**Comment by alfr3dosv** [comment]
I realized that it was because I was using **date** and not **timestap** or **datetime** in the table scheduled_tasks

**Comment by kagkarlsson** [comment]
Ok, good 👍
