### ISSUE TITLE
Using Scheduler as java.util.concurrent.Executor

### ISSUE THREAD

**Issue by plamentotev** [kagkarlsson/db-scheduler#227]
The ability to schedule a on-time task is quite useful and I'm looking into how can I use `Scheduler` as a drop-in replacement for `java.util.concurrent.Executor`. Any input or suggestion would be greatly appreciated. What I'm not sure how to do is to create a task from the runnable. And if that is feasible at all. Thanks.

**Comment by plamentotev** [comment]
Actually I gave the matter a bit of thought. If the `Runnable` implements `Serializable` as well, then  we can have a task with data class that wraps the runnable we wish to execute.

Something like
```
public class PersistentScheduler implements Executor {

    private final Scheduler scheduler;
    private final Task<RunnableWrapper> task;

    public PersistentScheduler(Scheduler scheduler, Task<RunnableWrapper> task) {
        this.scheduler = scheduler;
        this.task = task;
    }

    @Override
    public void execute(Runnable command) {
        RunnableWrapper runnableWrapper = new RunnableWrapper(command);

        scheduler.schedule(task.instance(UUID.randomUUID().toString(), runnableWrapper), Instant.now());
    }

    public static class RunnableWrapper implements Runnable, Serializable {

        private final Runnable runnable;

        RunnableWrapper(Runnable runnable) {
            this.runnable = runnable;
        }

        @Override
        public void run() {
            runnable.run();
        }
    }
```

And for the `Task`:
```
Tasks.oneTime("runnableWrapperTask", RunnableWrapper.class)
    .execute((taskInstance, executionContext) -> taskInstance.getData().run());
```

I wonder if this approach is good.

**Comment by kagkarlsson** [comment]
I am a bit unsure how this would work if you have many different types of tasks. 

The `Executor` needs a `Runnable`, but the scheduler needs a specific task. Not sure how this could be done without inspecting the Runnable class and casting it to the specific Task..?

**Comment by kagkarlsson** [comment]
Also curious about what are you gaining by using the `Executor` interface?

**Comment by plamentotev** [comment]
> I am a bit unsure how this would work if you have many different types of tasks.
> 
> The `Executor` needs a `Runnable`, but the scheduler needs a specific task. Not sure how this could be done without inspecting the Runnable class and casting it to the specific Task..?

I'm not sure too. Wouldn't just using the same task with different instances work? 



> Also curious about what are you gaining by using the `Executor` interface?

I'm also not sure, just evaluating the options. The idea is that `Executor` could be used with frameworks that schedule `Runnable` (Spring and `@Async`). Alternative is to do the scheduling on my own and not use Spring for it.
