### ISSUE TITLE
What happens with recurring tasks when you restart your server?

### ISSUE THREAD

**Issue by fatso83** [kagkarlsson/db-scheduler#229]
I have tried looking at the docs in the README for insight here, but I am not sure if they answer this or not. AFAI understand, this library makes it possible to say "Do Job X at a given time (or interval)" without losing the task should the server crash and restart. So through this, I would assume that on startup, this lib checks the tasks in the database and runs the tasks that should have run or are due (unsure if all tasks are run or just those within a certain time delta in close proximity).

Say we have a server that initiates a recurring task X and this is saved to the database. If the server crashes and is restarted, this task will be created and saved to the database. To me, this looks like it will then have two recurring tasks scheduled, and 3 if it should crash again, etc. How is this handled?

**Comment by kagkarlsson** [comment]
There is a uniqueness constraint for `task_name,task_instance`. For recurring tasks, the task_instance is typically `RECURRING`. If the execution already exists when the scheduler starts, no new execution is scheduled. However, if an execution exists, but the `Schedule` for the recurring task has been updated, the execution-time for the existing execution is modify to match the new `Schedule`.

It is described somewhat here: https://github.com/kagkarlsson/db-scheduler#recurring-tasks

Regarding crashes, you might want to read about dead executions: https://github.com/kagkarlsson/db-scheduler#dead-executions

**Comment by kagkarlsson** [comment]
> unsure if all tasks are run or just those within a certain time delta in close proximity

The scheduler will attempt to run all executions with a execution-time in the past

Also, regarding recurring tasks

> There are no guarantees that all instants in a schedule for a RecurringTask will be executed. The Schedule is consulted after the previous task-execution finishes, and the closest time in the future will be selected for next execution-time. A new type of task may be added in the future to provide such functionality.

**Comment by fatso83** [comment]
Perfekt!

**Comment by kagkarlsson** [comment]
🎉 This issue has been resolved in `v16.9.0` ([Release Notes](https://github.com/kagkarlsson/db-scheduler/releases/tag/v16.9.0))

**Comment by fatso83** [comment]
There is an error in your releases script, @kagkarlsson . I checked the release and it refers to this issue, `#229`, being closed by two different commits, and yet neither has anything to do with it.

**Comment by kagkarlsson** [comment]
Interesting, will look into that! Thank you!
