### ISSUE TITLE
Schedule job pipeline, Job chaining and FT

### ISSUE THREAD

**Issue by thranasingha** [kagkarlsson/db-scheduler#235]
We have a requirement of multiple pipelines with several dependent steps/jobs that needs to complete within one schedule. 
Have set of questions
1. Does it support step/job pipelines within one schedule?
2. If it is supporting does it track status of each step/job?
3. Does it support job chaining?
4. How does it recover failures if the application crashed or killed in middle of a schedule? 
5. What about the recovery when the schedule has several steps and crashed in the middle?
6. If job chaining supported does it has FT?

**Comment by kagkarlsson** [comment]
No, db-scheduler does not support multiple steps etc, you need to code that yourself. You could at the end of a job schedule the next step to run using the `SchedulerClient` (instantly if you wish)

**Comment by kagkarlsson** [comment]
Actually, this is possible if you do a bit of coding yourself. See my comment here: https://github.com/kagkarlsson/db-scheduler/issues/243#issuecomment-976342444

I will try and add an example for this and possibly some helper classes to make it a bit easier..
