### ISSUE TITLE
shutdownMaxWait not used by DbSchedulerAutoConfiguration

### ISSUE THREAD

**Issue by whatu1tme2b** [kagkarlsson/db-scheduler#236]
I am using the Spring Boot starter and noticed that the shutdownMaxWait property (DbSchedulerProperties) is not picked up by DbSchedulerAutoConfiguration. I have it defined in my application.yml, but is never used. It continues to use the default 30 minutes.

This seems to be a bug or did I miss someting?

**Comment by kagkarlsson** [comment]
I think you are right, thank you for reporting!

**Comment by kagkarlsson** [comment]
Released in 10.4

**Comment by whatu1tme2b** [comment]
Thanks a million for the quick fix.

**Comment by whatu1tme2b** [comment]
I do n't see version 10.4 in the maven central repository. Am I missing something?

**Comment by kagkarlsson** [comment]
Sorry, I forgot to release it in sonatype 🤦 . Done now, should be available very soon
