### ISSUE TITLE
`picked` and `pickedBy` are not updated in the table

### ISSUE THREAD

**Issue by sakina13789** [kagkarlsson/db-scheduler#239]
I am using db-scheduler:10.3, When the scheduler picks up the recurring task `picked` and `pickedBy` are not updated in the table.

**Comment by kagkarlsson** [comment]
Hi! 
I think this is a case where the execution is picked and executed so fast that you are not catching it while it is in a picked state. Could that be the case?

**Comment by kagkarlsson** [comment]
Closing this issue.
