### ISSUE TITLE
[Feature] A way to get all executions via the Scheduler

### ISSUE THREAD

**Issue by MarkvV** [kagkarlsson/db-scheduler#24]
It would be nice to get all scheduled executions via the `Scheduler` from the `TaskRepository`. Currently there is already a `Scheduler#getCurrentlyExecuting` but this returns the **_currently_** executing tasks. I propose  the `TaskRepository` to have a `public List<Execution> getExecutions()`. This could be helpful when a bunch of executions are scheduled and you want to cancel them at a later time with the use of `scheduler.cancel(taskInstanceId)` without keeping the `taskInstanceId` in memory / in a different storage. The thing is that the `taskInstanceId` is a random generated id and the handle I have to the task is in the data of the task itself. Not something I can query or cancel the task on.

Tell me if you have any questions / remarks. Thank you!

**Comment by kagkarlsson** [comment]
Sounds like a neat feature, as long as the total number of executions is not too big. Pull requests are welcome :)

**Comment by MarkvV** [comment]
[PR](https://github.com/kagkarlsson/db-scheduler/pull/25) is open :-).

**Comment by kagkarlsson** [comment]
Merged to master.

**Comment by kagkarlsson** [comment]
Released in 3.1, closing.

**Comment by kagkarlsson** [comment]
🎉 This issue has been resolved in `v16.9.0` ([Release Notes](https://github.com/kagkarlsson/db-scheduler/releases/tag/v16.9.0))
