### ISSUE TITLE
How to do job chaining in db-scheduler

### ISSUE THREAD

**Issue by dario-condori-ar** [kagkarlsson/db-scheduler#243]
I have the need to chain jobs. that is, I need to run a main job first. when this main job completes successfully. I need to launch a second job immediately. Is it currently possible to do it with db-scheduler?

**Comment by kagkarlsson** [comment]
Currently, what you can do is at the very end of the execution of your first task, schedule an instance of the second task to execute immediately. If you do not want to wait for `pollingInterval` for the second execution to start, enable immediate execution on the scheduler (`.enableImmediateExecution()`)

**Comment by kagkarlsson** [comment]
In the future we may add support for putting this logic (scheduling av second task) in the `CompletionHandler` to make it atomic (remove task1+schedule task2)

**Comment by kagkarlsson** [comment]
Created a feature for it: https://github.com/kagkarlsson/db-scheduler/issues/244

**Comment by kagkarlsson** [comment]
There is also the possibility to maintain the state (in `task_data`) about what the next step in the chain is and have a `Task` that checks the state and determines what code should be run.

You will need to create a custom task. The `CompletionHandler` checks the previous data and updates it with results from this run and sets what step should be next.

I think I will create an example for this..

**Comment by frederikb** [comment]
> There is also the possibility to maintain the state (in `task_data`) about what the next step in the chain is and have a `Task` that checks the state and determines what code should be run.
> 
> You will need to create a custom task. The `CompletionHandler` checks the previous data and updates it with results from this run and sets what step should be next.
> 
> I think I will create an example for this..

Did you manage to find the time to create that example or any other examples on how to best implement job chains with the current feature set?

**Comment by kagkarlsson** [comment]
I have not yet no. What is your requirement for the chaining?
