### ISSUE TITLE
Is it possible to use HikariCP to get connections?

### ISSUE THREAD

**Issue by vivekkothari** [kagkarlsson/db-scheduler#247]
Right now, it seems we are directly using the connection obtained from `DataSource`.
It would be nice to use a connection polling library (preferably HikariCP).

**Comment by vivekkothari** [comment]
Never mind.. I can use the `HikariDataSource` to use the connection pool.

**Comment by kagkarlsson** [comment]
Yes you can :)

**Comment by kagkarlsson** [comment]
🎉 This issue has been resolved in `v16.9.0` ([Release Notes](https://github.com/kagkarlsson/db-scheduler/releases/tag/v16.9.0))
