### ISSUE TITLE
Question: Any mechanism to update the scheduler trigger time without restarting the app?.

### ISSUE THREAD

**Issue by ziaulsid** [kagkarlsson/db-scheduler#253]

**Comment by kagkarlsson** [comment]
This is becoming a frequently requested feature. You can achieve this by putting the schedule in the `task_data` field, as done here: https://github.com/kagkarlsson/db-scheduler/blob/master/examples/features/src/main/java/com/github/kagkarlsson/examples/PersistentDynamicScheduleMain.java

You have to write some boilerplate code yourself for it, it is not as smoothly supported as recurring tasks where the schedule is constant and supplied at compile time.

I may add better support for these types of tasks. Something like `RecurringTaskWithPersistentSchedule`.. (a bit of a mouthful...)

**Comment by kagkarlsson** [comment]
Also, API is improved in PR #257

**Comment by kagkarlsson** [comment]
Closing.

**Comment by kagkarlsson** [comment]
Improved API released in v11.0
