### ISSUE TITLE
execution_time is automatically updated by Mariadb on pick execution

### ISSUE THREAD

**Issue by ggaborg** [kagkarlsson/db-scheduler#258]
MariaDB has special behavior for the first column that uses the TIMESTAMP data type in a specific table. For the first column that uses the TIMESTAMP data type in a specific table, MariaDB automatically assigns the following properties to the column:
DEFAULT CURRENT_TIMESTAMP
ON UPDATE CURRENT_TIMESTAMP 
This means that if the column is not explicitly assigned a value in an INSERT or UPDATE query, then MariaDB will automatically initialize the column's value with the current date and time.

The issue is that if the Mariadb server is on a different timezone than UTC, it will update the execution_time with a non UTC timestamp instead of UTC on pick execution.

The workaround was to define the execution_time column as null instead of not null.

Another solution would be to include the execution_time in any update statement but it makes less sense to do that.

**Comment by kagkarlsson** [comment]
> This means that if the column is not explicitly assigned a value in an INSERT or UPDATE query, then MariaDB will automatically initialize the column's value with the current date and time.

Wow, that sounds insane... 

Would you please post the schema definition that is working for you?

**Comment by ggaborg** [comment]
The important part is the "execution_time timestamp(6) null,"

create table dbscheduler_tasks (
  task_name varchar(255) not null,
  task_instance varchar(255) not null,
  task_data mediumblob,
  execution_time timestamp(6) null,
  picked BOOLEAN not null,
  picked_by varchar(255),
  last_success timestamp(6) null,
  last_failure timestamp(6) null,
  consecutive_failures INT,
  last_heartbeat timestamp(6) null,
  version BIGINT not null,
  PRIMARY KEY (task_name, task_instance)
);

**Comment by kagkarlsson** [comment]
Thank you 👍 

Looks like you might also be able to tune the setting `explicit_defaults_for_timestamp` on the database-level. Some more details here: https://www.meshcloud.io/2019/01/14/mysql-timestamp-inizialization/
