### ISSUE TITLE
Dynamic scheduling & failover

### ISSUE THREAD

**Issue by iliuta** [kagkarlsson/db-scheduler#272]
Hi, 

I need to dynamically schedule job executions depending on user needs. 
I only know job behaviour (what the job exactly does, the same for everybody) but I don't know how many jobs I want to schedule and at what time each. That depends of the number of users and of their needs.

Also, if my application crashes, when it restarts, I would like it to reschedule all jobs stored in the database.

So, I wonder if all that is possible out of the box with db-scheduler.

Sorry it looks obvious to you, but I checked the documentation and it appears that we need to register all tasks before starting the scheduler. But I don't exactly know all tasks when my application starts...

Thanks for your answer.

**Comment by kagkarlsson** [comment]
Hi!

Yes this is possible. I recently made it a bit easier, see for example https://github.com/kagkarlsson/db-scheduler/blob/master/examples/features/src/main/java/com/github/kagkarlsson/examples/RecurringTaskWithPersistentScheduleMain.java

Restarts and crashes are handled automatically. The jobs do not need to be rescheduled after a restart, they are persistent and live in the database

**Comment by kagkarlsson** [comment]
Wrote some about it here as well: https://github.com/kagkarlsson/db-scheduler#dynamic-recurring-task
