### ISSUE TITLE
read/write replica data source

### ISSUE THREAD

**Issue by amit-handda** [kagkarlsson/db-scheduler#274]
Hi,

Thanks for maintaining the project. We are trying to adopt it into our internal services. One query is if the scheduler can be configured with two datasources (one for reading from replicas, other for regular read/write usage).
On initial thoughts, it doesnt make sense to me. since the scheduler is primarily using the table in read/write mode. but still wanted to run it by you.

Thanks,

**Comment by kagkarlsson** [comment]
Hi! It currently cannot and I think there might be some gotchas with stale data etc, so I do not think it is worth it..  (and as you say, it's not that much reading)

**Comment by amit-handda** [comment]
thanks for the prompt response ! appreciate it.
