### ISSUE TITLE
Infinite wait because of JDBC Communications link failure

### ISSUE THREAD

**Issue by FinishEverythi** [kagkarlsson/db-scheduler#279]
When connection to SQL database is temporarily lost, we get 
`com.mysql.cj.exceptions.CJCommunicationsException: Communications link failure` exception
when executing [this](https://github.com/kagkarlsson/db-scheduler/blob/ff34915fe478537480a21837d2fa62ed4a43623a/db-scheduler/src/main/java/com/github/kagkarlsson/scheduler/FetchCandidates.java#L71) line.

The problem is that in this case scheduler will wait forever [here](https://github.com/kagkarlsson/db-scheduler/blob/ff34915fe478537480a21837d2fa62ed4a43623a/db-scheduler/src/main/java/com/github/kagkarlsson/scheduler/RunUntilShutdown.java#L47) , because callback in this [line](https://github.com/kagkarlsson/db-scheduler/blob/ff34915fe478537480a21837d2fa62ed4a43623a/db-scheduler/src/main/java/com/github/kagkarlsson/scheduler/FetchCandidates.java#L90) will never be called.

Is there any way to correctly handle such case?

**Comment by kagkarlsson** [comment]
I am not sure your analysis is correct.

```
waitBetweenRuns.doWait();
```

This is not an infinite wait, it defaults to 10s, but can be shortened for certain scenarios by calling 

```
    public void triggerCheckForDueExecutions() {
        executeDueWaiter.wakeOrSkipNextWait();
    }
    ```

**Comment by FinishEverythi** [comment]
Yes, I see. My mistake. Thank you
