### ISSUE TITLE
multiple schedulers per table

### ISSUE THREAD

**Issue by amit-handda** [kagkarlsson/db-scheduler#280]
is there a way such that multiple schedulers (diff environment: prod, sandbox1, sandbox2 etc.) could co-exist atop single `scheduled_tasks` table ? eg,
* prodScheduler ll process tasks: name1
* sandboxScheduler ll process tasks: name1sandbox

it ll allow us to test out the changes safely before pushing into production. 

current behaviour is that there is no isolation. any scheduler ll pick up the task and try to execute, but since prodScheduler lacks the mapping from name to task implementation for non-prod tasks, it ll error out for name1sandbox tasks and vice-versa.

**Comment by vivekkothari** [comment]
I'd rather do it by configuring different tables, so for staging the table could be `staging_scheduled_tasks`. If you can have a different DB altogether, nothing like it.

**Comment by amit-handda** [comment]
Thanks @vivekkothari, totally agree here. its a bit like queues. We should ideally, have, different queues for different environments.

I was in a hurry, so posted the query.

**Comment by kagkarlsson** [comment]
Yeah, agree with @vivekkothari 👍 . Different tables is already supported

I think this is a feature that will not be a priority so I will close this issue
