### ISSUE TITLE
How to schedule new instance of a same task within task execution in Spring Boot?

### ISSUE THREAD

**Issue by attilapapai** [kagkarlsson/db-scheduler#281]
Hi!

I'm experimenting with your library in a Spring Boot application. What I'm trying to do is the following:

I have a polling task which is responsible for querying the status of a task on a website. If the status is `in_progress` it should retry later (possibly with some logic regarding the exact execution time).

I'm unsure how to do this without getting some circular exceptions when trying to define the beans.

Logic simplified:

```
@Service
class Service {

  fun export(schedulerClient: SchedulerClient) {
     // some business logic
     schedulerClient.schedule(pollTaskStatus.instance(UUID.randomUUID().toString(), taskId), Instant.now().plus(1, ChronoUnit.MINUTES))
  }

  fun pollStatus(schedulerClient: SchedulerClient) {
    val status = // getStatusFromWeb
    if (status == "in_progress") {
      // schedule the same poll status task later time but with different id
    }
  }
}
```

The problem with the above is that in the configuration the `Task` which calls `pollStatus` have a dependency on `Service`.
```
@Bean
fun pollStatusTask(service: Service) {...}
```

 However if I want to trigger this task from `Service` there will be a circular dependency now...
```
@Service
class Service {
  @Autowired
  private final PollStatusTask: Task<String> // this will cause the circular dependency
}
```

I saw this example (https://github.com/kagkarlsson/db-scheduler/blob/master/examples/features/src/main/java/com/github/kagkarlsson/examples/MaxRetriesMain.java) with the max retries settings for a task but that assumes something bad (exception) happened during execution which is not the case here.

Is there a way to trigger a one time task within the context of a same-type one time task?

Thank you

**Comment by kagkarlsson** [comment]
Does this example help you? 
https://github.com/kagkarlsson/db-scheduler/blob/master/examples/features/src/main/java/com/github/kagkarlsson/examples/SpawningOtherTasksMain.java#L47

You can use the `SchedulerClient` from the `ExecutionContext` to avoid some circular dependencies

**Comment by attilapapai** [comment]
From the example you linked - would it be possible for the type `printer` task to create another `printer` but with an execution time in the future (basically my question boils down to tasks spawning other tasks with the same type)?

**Comment by kagkarlsson** [comment]
Ok, I understand. It should be possible to create the `TaskInstance` without a reference to the `Task`, like so: 

```
                    client.schedule(
                        new TaskInstance<>("printer", "" + id + i, i),
                        Instant.now());
                        ```

**Comment by attilapapai** [comment]
Thanks weren’t aware we could do like this :)

**Comment by kagkarlsson** [comment]
It is a bit poorly documented. Got an enhancement for it, but not sure when there will be time to look at it: https://github.com/kagkarlsson/db-scheduler/issues/26

**Comment by kagkarlsson** [comment]
Glad that worked out for you 👍
