### ISSUE TITLE
Execute one-time task in Spring application

### ISSUE THREAD

**Issue by tacerus** [kagkarlsson/db-scheduler#283]
Hi,

apologies in advance for the rookie question - whilst I was able to implement recurring schedules very easily (Kudos!), I am failing to implement the sample one-time/ad-hoc code:

```
    OneTimeTask<Void> myAdhocTask = Tasks.oneTime(null)
            .execute((inst, ctx) -> {
                System.out.println("Executed!");
            });    
    
    scheduler.schedule(myAdhocTask.instance("1045"), Instant.now().plusSeconds(5));
```

If I understood correctly, if used within Spring Boot it is not necessary to "build" and start the scheduler. Is this correct? If so, how do I get an instance of `scheduler` to perform the `scheduler.schedule` operation? As of now, `scheduler` does not seem to resolve to anything.

The Spring example application shows how to perform a one-time task at startup using `CommandLineRunner`, but I assume this should not be necessary for ordinary tasks during runtime?

Thanks for any help!

**Comment by kagkarlsson** [comment]
Yeah, that can be a bit of a catch-22. There is an example of it here: https://github.com/kagkarlsson/db-scheduler/blob/master/examples/features/src/main/java/com/github/kagkarlsson/examples/SpawningOtherTasksMain.java#L47
Basically, a SchedulerClient is exposed via `executionContext.getSchedulerClient()`. 
Does that resolve your questions?

**Comment by kagkarlsson** [comment]
Hmm I think I may have misunderstood. My answer is for when adhoc tasks are scheduled from _another task_.

In your case I believe your should be able to get Spring to inject a `Scheduler` bean for you no?

**Comment by tacerus** [comment]
Thanks for the fast response!
I noticed that reference in another issue while searching here, but couldn't quite figure out how to access the `executionContext` from other classes? It seems like it's only available from within a task execution, and not there "beforehand" to schedule it?

**Comment by kagkarlsson** [comment]
> Thanks for the fast response! I noticed that reference in another issue while searching here, but couldn't quite figure out how to access the `executionContext` from other classes? It seems like it's only available from within a task execution, and not there "beforehand" to schedule it?

Correct, I answered a bit too quickly there. That is not your case

**Comment by kagkarlsson** [comment]
> Oh, do I use native Spring scheduling and it will hand it to `db-scheduler` for me?

There is unfortunately no integration with Spring scheduling. But I believe the `Scheduler` is a registered bean in the Spring context that you can get injected where you need a `SchedulerClient`

**Comment by kagkarlsson** [comment]
The bean is created here: https://github.com/kagkarlsson/db-scheduler/blob/master/db-scheduler-boot-starter/src/main/java/com/github/kagkarlsson/scheduler/boot/autoconfigure/DbSchedulerAutoConfiguration.java#L102

**Comment by tacerus** [comment]
> There is unfortunately no integration with Spring scheduling.

That's quite fine with me, as I wanted to schedule some tasks from methods where I might not be able to place a Bean easily.

> But I believe the Scheduler is a registered bean in the Spring context that you can get injected where you need a SchedulerClient

If you mean `Scheduler` (with the capital `S`), that tells me it is a non-static method which I cannot call. I think that comes from the one you linked.
I additionally tried to preface my method with `@Scheduled` but it does not seem to change the unavailability of `scheduler`.
Mind though that I am not very experienced - so possibly I miss some way of "activating" the `SchedulerClient` using Spring tools?

**Comment by tacerus** [comment]
Upon some more trying, it seems the only way to reach it is like this:

```
    public static void runTestTask(Scheduler scheduler) {
    
    OneTimeTask<Void> myAdhocTask = Tasks.oneTime(null)
            .execute((inst, ctx) -> {
                System.out.println("Executed!");
            });
    
    
    scheduler.schedule(myAdhocTask.instance("1045"), Instant.now().plusSeconds(5));
    
    }
```

But that doesn't seem quite right - as `runTestTask()` now requires a bogus argument and can't be called from elsewhere.

**Comment by kagkarlsson** [comment]
> If you mean Scheduler (with the capital S), that tells me it is a non-static method which I cannot call. I think that comes from the one you linked.

No, you need the instance Spring is managing for you. It is true you cannot call the method statically.

You can have a reference to the `Scheduler` injected by Spring. For constructor auto-wiring, just add the scheduler as a parameter in the constructor

```@RestController
@RequestMapping("/counter")
public class CounterController {
    private final CounterService counter;
    private final Scheduler scheduler;

    public CounterController(CounterService counter, Scheduler scheduler) {
        this.counter = counter;
        this.scheduler = scheduler;
    }
    
    ....
    ```

**Comment by kagkarlsson** [comment]
Sure, would be neat to have that example as well. I have some comments on the code, but can do some of that on the PR as well. 
This method looks odd to me: 

```
public static String addShell(RedirectAttributes redirectAttributes, Scheduler scheduler) {
```

Should not need to be static, and I wonder if we need any `Scheduler` parameter, it is stored in a private field already.

Also, something feels off here, I think it may just be the method name, it looks like a constructor, but is in reality a setter if I read the code correctly.  `setScheduler` is better I think.

```
	@Autowired
	public void Scheduler(Scheduler scheduler) {
	```

**Comment by tacerus** [comment]
I think my example here was a bit messy due to tampering around with it too often. I hope the PR is cleaner!

The only thing left in it from your comment is 
> Should not need to be static

I think it needs to be in order for me to call it from the controller class. But maybe I am missing something obvious? Feel free to comment on the PR, I submitted it as #285.
