### ISSUE TITLE
Instance fails if ID > 40 characters

### ISSUE THREAD

**Issue by tacerus** [kagkarlsson/db-scheduler#284]
Hi,

this:
```
$ printf "J3uuSL2fc4sdI1TBp95u0bPVzWKyddu0bPVzWKyd" | wc -m
40

String instanceid = "J3uuSL2fc4sdI1TBp95u0bPVzWKyddu0bPVzWKyd";
scheduler.schedule(SchedulerBean.shellRemovalTask().instance(instanceid), Instant.now().plusSeconds(30));
```

creates an instance just fine.

However adding one more character to the ID, making it exceed 40 characters:
```
$ printf "J3uuSL2fc4sdI1TBp95u0bPVzWKyddu0bPVzWKydd" | wc -m
41

String containerid2 = "J3uuSL2fc4sdI1TBp95u0bPVzWKyddu0bPVzWKydd";
scheduler.schedule(SchedulerBean.shellRemovalTask().instance(containerid2), Instant.now().plusSeconds(30));
```
results in:
`com.github.kagkarlsson.scheduler.exceptions.TaskInstanceException: Failed to add new execution. (task name: shell-removal, instance id: J3uuSL2fc4sdI1TBp95u0bPVzWKyddu0bPVzWKydd)`

Presumably not a big issue for most, but I noticed it upon trying to create instances with Docker container IDs.... :-)

Best,
Georg

**Comment by tacerus** [comment]
This was an issue with my database schema.

**Comment by kagkarlsson** [comment]
Ok, yeah I suppose there is no upper bound enforced by the code, so it will be whatever you specify in the schema. Probably should set a maximum in the code and validate that..
