### ISSUE TITLE
Use GoogleJavaFormat for code formatting

### ISSUE THREAD

**Issue by vivekkothari** [kagkarlsson/db-scheduler#291]
I know code formatting is very subjective, but is it possible to use [GoogleJavaFormat](https://github.com/google/google-java-format) to format the code in this repo?
A lot of open source projects use the same formatter and its also easier to read.

**Comment by kagkarlsson** [comment]
Good suggestion, I will think about it. I have seen PRs with variations in code-format

**Comment by vivekkothari** [comment]
If you are okay, I can raise a PR which formats entire codebase using GoogleJavaFormat.

**Comment by kagkarlsson** [comment]
I had a look at it but was not convinced due to the short max-length of lines in the google-java-format.

What plugin do you recommend? Is there one with configurable max-length? (Say if I want 120)

**Comment by kagkarlsson** [comment]
I did a trial run using spotless and the palantir code format, which is google-based with some tweaks. I tried google format which has 2 indents. I mostly liked it, but it some cases the indents were really hard to see..

**Comment by vivekkothari** [comment]
you can always customize the format and put in the repo in such a way that intellij 
like what [armeria](https://github.com/line/armeria) does.
https://github.com/line/armeria/tree/main/settings/intellij_idea
So that any new developer automatically get those settings.

**Comment by kagkarlsson** [comment]
I am going to go with the google format. It just seem cleaner to me, and it was a better IntelliJ experience than the others.

**Comment by kagkarlsson** [comment]
Merged to master via PR #375
