### ISSUE TITLE
Add `created_at` to the schema

### ISSUE THREAD

**Issue by vivekkothari** [kagkarlsson/db-scheduler#293]
It would be great to add this column, it will help to know when was the task created/scheduled.

Optionally we can also add `updated_at` if needed.

**Comment by kagkarlsson** [comment]
Thanks for the suggestion, I will have to consider that. 
What are your use-cases where this is valuable?

**Comment by vivekkothari** [comment]
Once use case is by queuing the table (`scheduled_tasks`),  table I can easily know when was the task created.
I started using `SerializerWithFallbackDeserializers` and now we have tasks in our DB where some have `task_data` serialised with old Java serialiser and some using the new json once. If I had `created_at` I would quickly know when did the new serialiser started getting used in prod.

**Comment by kagkarlsson** [comment]
I understand. I am hesitant to add it based on this single case. 

Maybe you can write a query that tries to parse the data as json to discover what rows are on the old format?

**Comment by vivekkothari** [comment]
Yeah. That too works.
