### ISSUE TITLE
Question regarding execution of recurring tasks

### ISSUE THREAD

**Issue by fredva** [kagkarlsson/db-scheduler#3]
What happens if a recurring task takes longer to execute than the scheduled interval? Will the task run according to the schedule regardless so that two invocations of the same task runs in parallell, or will the scheduler delay the next invocation until the previous is complete?

I have a case where a recurring task is scheduled to run every minute. It is important that this task never runs in parallel with itself, but at the same time, there is a risk that one invocation of the task may run for more than 1 minute. Will the scheduler take care of this for me?

**Comment by kagkarlsson** [comment]
No, a recurring task will never be executed in parallell, so you should be fine :). Using FixedDelay of 1 minute schedules the next execution 1 minute after the current execution finishes.

**Comment by kagkarlsson** [comment]
Added a note about this in the documentation :)
