### ISSUE TITLE
Define column names in the configuration 

### ISSUE THREAD

**Issue by Cesaario** [kagkarlsson/db-scheduler#300]
Hi, I was wondering if there is a way to change the name of the columns of the task_scheduler table. I looked into the docs and didn't find a way. Also, looking into [JdbcTaskRepository.java](https://github.com/kagkarlsson/db-scheduler/blob/master/db-scheduler/src/main/java/com/github/kagkarlsson/scheduler/jdbc/JdbcTaskRepository.java) it looks like the names are hard coded
Is there a way or it hasn't been implemented yet?

**Comment by kagkarlsson** [comment]
There is no way to do that no. What would be the reason for doing it? It feels like a low priority thing to me

**Comment by kagkarlsson** [comment]
Hope this was resolved in another way
