### ISSUE TITLE
FixedDelay Schedule with InitialExecutionTime in the future.

### ISSUE THREAD

**Issue by michaelmcguirk** [kagkarlsson/db-scheduler#306]
Hi there,

Is it possible to define a recurring task on a FixedDelay with a specific start time? For example I want to be able to schedule a task to run weekly, with the first execution being some date in the future.

**Comment by kagkarlsson** [comment]
Yes, you should be able to create a Schedule based on `FixedDelay`, but override the method `getInitialExecutionTime(...)`.
There are other ways as well, if that solution does not work for you.
