### ISSUE TITLE
Tracking task statuses

### ISSUE THREAD

**Issue by slukasiewicz** [kagkarlsson/db-scheduler#307]
I have to make a mechanism for storing OneTimeTask task statuses in the database. Now I can handle only failures task by FailureHandler. Is it possbile to handling new created, in progress, canceled and processed in the current implementation? Maybe it is worth adding handlers for these statuses.

**Comment by kagkarlsson** [comment]
You might add some code to the Completion and FailureHandler, or you might create a custom `StatsRegistry` (it will get callbacks to `void registerSingleCompletedExecution(ExecutionComplete completeEvent);`)
