### ISSUE TITLE
.onFailure() with recurringWithPersistentSchedule

### ISSUE THREAD

**Issue by VasiliZas** [kagkarlsson/db-scheduler#308]
Hi!! I would like to know if I can configure the behavior of the scheduler if I use recurringWithPersistentSchedule.  I didn't find a method  .onFailure() for it.  Is there any way to configure the behavior in case of an exception?

**Comment by kagkarlsson** [comment]
The builder currently does not support setting a `FailureHandler` for those, but I think we could add something like this to that builder etc:

```java
        public RecurringTaskWithPersistentSchedule<T> onFailure(FailureHandler<T> failureHandler) {
            this.onFailure = failureHandler;
            return this;
        }
```

.. and propagate that inwards. Pull-requests are welcome! :) 

You might also try and bypass the builder and create a class similar to `RecurringTaskWithPersistentSchedule` with a modified FailureHandler.

**Comment by VasiliZas** [comment]
Hi!! I inherited from AbstractTask class. And set everything up there. Create your own class with data. And used it. Now everything works as it should!! Have a good day! Very cool library.

**Comment by kagkarlsson** [comment]
Good to hear 👍
