### ISSUE TITLE
Scheduler Breakers JDBC connection 

### ISSUE THREAD

**Issue by mcelrojb58** [kagkarlsson/db-scheduler#31]
Hello,

We are using the db_scheduler to prevent dead_locks and race conditions in our Cloud application. However, it seems that somewhere whether it is due to load or a piece of code the JDBC connection is closed or broken and it disrupts our connection pool that our JPA elements utilize. We initialize the scheduler using 5 threads, so we feel it should handle the load. So is there a place in the code that calls a connection close after execution?

**Comment by kagkarlsson** [comment]
Hi,

Not sure I understand 100%, but connections are always closed, but this is typically handled by the connection pool (the `DataSource`), which normally "swallows" the close and returns the connection to the pool. What connection pool are you using?
Would you please also describe the steps involved in scenarios where you experience problems?

**Comment by mcelrojb58** [comment]
Sorry for the late reply i am not sure we are using a connection pool such like Hikari or even the much older Bones. Our Data connection is built by spring-boot-starter-data-jpa. And our Application maintains persistence thorugh JPA repositories in our code. Could db scheduler conflict with this db connection method?

**Comment by kagkarlsson** [comment]
There should not be any problem, I think I need more details (actual problem, stack traces etc) or I have to close this issue.

**Comment by mcelrojb58** [comment]
I am working on getting up to date stack traces

**Comment by kagkarlsson** [comment]
Closing this issue. We can consider re-opening if you have more details.
