### ISSUE TITLE
Custom micrometer metrics in a recurring task not showing up

### ISSUE THREAD

**Issue by mityakoval** [kagkarlsson/db-scheduler#312]
Hello! 

I'm trying to emit some custom metrics to Prometheus from a recurring task in the following fashion: 
```java
Metrics.counter("expired.consent.archivations", "status", "success").increment(successfullArchivationCount.get());
```

But the metrics is not available at the actuator endpoint. Feels like I am missing some config but can't figure out what it is exactly. 

It's a Spring Boot application and this approach works as expected everywhere else in the app.

**Comment by kagkarlsson** [comment]
You are saying that other metrics work, just not this one? If that is the case then I do not think it has something to do with db-scheduler

**Comment by mityakoval** [comment]
Yes, this approach works everywhere else in the app, but not in the scheduled task.

**Comment by mityakoval** [comment]
@kagkarlsson 
Hi again. Just to clarify, none of the custom metrics emitted from the db-scheduler task is available anywhere. What I meant by "everywhere else" was the rest of the application outside of the scheduled task. To me it seems that the issue might be with the task itself or some configuration that's missing. Would appreciate some help

**Comment by kagkarlsson** [comment]
I do not think this is something caused by the task or db-scheduler, it must be something with the way metrics are being registered. Things to consider:

* Are you certain the code actually runs, reaches and passes the line where you are registering the metric? (i.e. not hanging before that)
* Is the code running at a point in time where the metrics-registry is properly configured?

**Comment by kagkarlsson** [comment]
I would try the debugger and step through the code. Check what metrics-registry is being used etc.

**Comment by mityakoval** [comment]
* I'm sure the code runs, as there is logging done on the next line, that I can see.
* That was kind of my question. It is obviously configured for the rest of the app as we have several dashboards in Grafana for this app. This task is recurring and runs at night. Does it need any additional configuration?

We have several applications with micrometer and prometheus metrics and all of them work fine. The only place, where the metrics doesn't show up, is this task.

**Comment by kagkarlsson** [comment]
I tried adding some custom-metrics the way you did in my spring-boot example and it seems to be working fine.

```java
    @Bean
    Task<Void> recurringSampleTask(CounterService counter) {
        return Tasks
            .recurring("recurring-sample-task", fixedDelay(Duration.ofSeconds(5)))
            .execute((instance, ctx) -> {
                log.info("Running recurring-simple-task. Instance: {}, ctx: {}", instance, ctx);
                counter.increase();
                Metrics.counter("mymetric.recurring", "status", "success").increment(1);
            });
    }
```
    
```
❯ curl localhost:8080/actuator/prometheus | grep mymetric

# HELP mymetric_recurring_total
# TYPE mymetric_recurring_total counter
mymetric_recurring_total{status="success",} 4.0
# HELP mymetric_onetime_total
# TYPE mymetric_onetime_total counter
mymetric_onetime_total{status="success",} 1.0
```

**Comment by kagkarlsson** [comment]
I think you need to take out the debugger and try to find out what is going on.

**Comment by mityakoval** [comment]
Alright, debugger it is then. Thanks!
