### ISSUE TITLE
simplify task creation with Spring

### ISSUE THREAD

**Issue by gpicavet** [kagkarlsson/db-scheduler#322]
Hello,

I'm looking for a more resilient way than SpringBoot @Async to execute tasks , while keeping task definition and execution easy.

My understanding is i  have to create a Task Bean for each Async Job, but it's quite verbose and task must be configured in a separate class.

I think defining one task and executing arbitrary lambda, passing it as data, would come with Serialization problems .

Do you think it would be possible to scan annotations (here @MyAsync), creating one Task for each occurence , and passing them when initializing the scheduler ?

@MyAsync
public void myTask() {
   ...
}

...
myTask() -> trigger the task scheduling

**Comment by kagkarlsson** [comment]
That sounds like a good feature. Scanning for annotations and setting up recurring jobs for them automatically. And as a side-note, also interested in how easy it is to hook into the Spring @Scheduled annotation.

> I think defining one task and executing arbitrary lambda, passing it as data, would come with Serialization problems .

Yeah I am not a big fan of that approach if it can be avoided. (if there is a fixed set of tasks)

**Comment by kagkarlsson** [comment]
If this is the feature-request, the title should change :)

**Comment by kagkarlsson** [comment]
Moved to issue #509
