### ISSUE TITLE
SQL db load on recurring tasks in cluster mode

### ISSUE THREAD

**Issue by FrolovOlegVladimirovich** [kagkarlsson/db-scheduler#333]
Hello!
Thanks for your library. But there are some questions.

Our service uses 2 recurring tasks with a fixed delay of 1 second each, and it's running on 4 nodes.
The following property in application.yml:
db-scheduler:
  polling-interval: 0s
  
When we first deployed the service with the library included, we saw an increase in the number of database requests to 5-5.7k req/s.

After reducing the number of threads from the default 10 to 4 (added threads: 4 to the application.yml), the number of database requests increased to 9-9.5k req/s.

1) Is this number of requests to database normal for 2 tasks and 4 service instances?
2) Is it possible to reduce the load on the database? How?
3) Why did the number of requests to database increased when the number of threads decreased?

**Comment by kagkarlsson** [comment]
That sounds a bit crazy. Suspecting it is because of `polling-interval: 0s`, you poll for new executions as fast as possible, no delay.

**Comment by kagkarlsson** [comment]
Yeah. TBH, there probably should be a validation error for `polling-interval: 0s`, the scheduler is not built for that. Put `1s` at least.

**Comment by a1ekseev** [comment]
> Yeah. TBH, there probably should be a validation error for `polling-interval: 0s`, the scheduler is not built for that. Put `1s` at least.

In milliseconds can it be set?

**Comment by kagkarlsson** [comment]
Did you try milliseconds?

**Comment by FrolovOlegVladimirovich** [comment]
Yes. It helped us. Thank you!
