### ISSUE TITLE
More Spring Boot examples

### ISSUE THREAD

**Issue by kagkarlsson** [kagkarlsson/db-scheduler#336]
There are a lot of confusion around how different features should be used when using the spring boot starter. Need some more examples for advanced use-cases with spring

**Comment by dipeshsingh253** [comment]
Hey @kagkarlsson , I would like to contribute. I am good with spring, spring boot and other related tools.

**Comment by kagkarlsson** [comment]
This issue is a bit out-dated, it was mostly fixed by introducing more examples here: https://github.com/kagkarlsson/db-scheduler/tree/master/examples/spring-boot-example

Appreciate the offer to contribute though 🙏. Do you see any other interesting candidates for contribution?

**Comment by dipeshsingh253** [comment]
Thanks for the update @kagkarlsson, I will create an issue in case I find one or see any room for improvement.

**Comment by kagkarlsson** [comment]
🎉 This issue has been resolved in `v15.1.2` ([Release Notes](https://github.com/kagkarlsson/db-scheduler/releases/tag/v15.1.2))
