### ISSUE TITLE
Track the number of times a task ran for use in failure handler

### ISSUE THREAD

**Issue by bgooren** [kagkarlsson/db-scheduler#34]
Hi!

Thanks for providing this library! It's the only one of its kind I have found after a lot of searching. We don't have enough background jobs to warrant something heavyweight like quartz and don't want to introduce a new external service for this (redis, if we use jesque).

Having said that, there is one thing that I am missing. Currently, a failing job with a OnFailureRetryLater failure handler will loop "forever": that is, until an operator intervenes.

If the library would track the number of executions per task instance and provide that number to the failure handler, I could easily rewrite a retry policy which retries X times and then escalates by taking the job out of the queue and storing it in a "failed tasks" list somewhere.

I guess that what I am looking for is more like https://github.com/jhalterman/failsafe (another great library!) and their RetryPolicy.

**Comment by kagkarlsson** [comment]
Had some free time and got a candidate PR (#35 ) for this feature. Would you please verify that this satisfies you use-case before I finalize it?

**Comment by bgooren** [comment]
Looks good to me - thanks! I was planning on creating a PR for this, but you beat me to it :-)

**Comment by kagkarlsson** [comment]
Appreciate that! Should you write a generic FailureHandler that uses the number of retries, maybe you can contribute that?

**Comment by bgooren** [comment]
Will do! That's the beauty of open source :-)

**Comment by bgooren** [comment]
PS Since this is a breaking change for existing installations (table format change), are you planning to do a 4.0 release for this?

**Comment by kagkarlsson** [comment]
Yes, it is released as 4.0 already

fre. 19. okt. 2018 kl. 15:49 skrev Sebastian Gooren <
notifications@github.com>:
