### ISSUE TITLE
Ability to pause/resume scheduler

### ISSUE THREAD

**Issue by tkosgrabar** [kagkarlsson/db-scheduler#353]
## Expected Behavior

When Scheduler is paused :
- no new scheduled tasks are fetched from database
- currently executing tasks are executed

When Scheduler is resumed : 
- scheduled tasks are fetched from database and executed

## Current Behavior

Scheduler can be only started and then stopped. 
During redeployment of service, our practise is that instance being redeployed stops accepting any new tasks ( it is removed from service discovery so that instance is not invoked by clients, it stops processing any new background jobs ), and once all currently executing tasks ( clients invocations, async jobs ) are finished, only then service is stopped ( there is no fixed time window when tasks have to finish, but deployment automation waits until service is in ready_to_shutdown state ). 
In such use case it would be really nice feature to be able to pause scheduler so instance processes scheduled task, but doesn't fetch new from database. 

## Proposal
- introduce new paused state
- RunUntilShutdown
  - if state is paused toRun.run() is not invoked

**Comment by kagkarlsson** [comment]
I am not sure how this differs from calling `stop()` on the Scheduler?

**Comment by kagkarlsson** [comment]
> and once all currently executing tasks ( clients invocations, async jobs ) are finished, only then service is stopped 

From the above, I got the impression the service would also be shutdown? (then there would be no need to resume scheduler-operations) Are you saying the scheduler and service will at some point just be re-enabled without having being stopped?

**Comment by tkosgrabar** [comment]
yes, service and scheduler will in this case at some point just be re-enabled ( without being stopped ).

**Comment by kagkarlsson** [comment]
I see. This will probably not be a high priority feature, so we might be reliant on pull-requests here

**Comment by tkosgrabar** [comment]
OK, 
I can work on PR if you agree on proposed approach ?

alternative approach :
* https://github.com/kagkarlsson/db-scheduler/issues/173 if support for custom task repository is added, service using scheduler can solve this by customizing task repository ( eg. return emptyList() when fetchingTasks from DB )

**Comment by kagkarlsson** [comment]
I do not think the alternative suggestion is a good way to handle it. 

We probably need to add a check in the runnable fetching new executions, if paused, it should just skip and go straight to sleep

**Comment by kagkarlsson** [comment]
Closing as fixed.
