### ISSUE TITLE
Recurring job resheduling

### ISSUE THREAD

**Issue by anon-software** [kagkarlsson/db-scheduler#358]
My application sets up a recurring job running every 15 minutes. However, I sometimes need to "rush" the next run and I use `scheduler.reschedule(taskInstanceId, Instant.now())` method call for that purpose. That mostly works, but I think that on occasion the call coincides with the regularly scheduled run because I see this exception in the log:

`com.github.kagkarlsson.scheduler.exceptions.TaskInstanceCurrentlyExecutingException: Cannot use SchedulerClient to modify a task-instance that is currently executing. If this occurs often, consider only modifying executions not picked that has the next execution-time a certain time into the future. (task name: base.db.email.Emailer, instance id: krc)`

I could follow the advice and check if the next execution is at least 15 seconds (for example) away as a condition to reschedule to avoid the collision, but hard-coding such a value really looks like a poor programming practice to me. Is there a better way?

While not really relevant, the task in question bulk transmits the email accumulated for the last 15 minutes. But occasionally a more important email is generated and I want to run the job "now".

**Comment by meggarr** [comment]
You can design a customized task, with customized data, upon every execution, you can do the rescheduling in the `CompletionHandler`
E.g.
```
    @Bean
    Task<Void> yourTask(YourTaskService taskService) {
        Schedule delay7sec = FixedDelay.of(Duration.ofSeconds(7));
        return Tasks.custom("YOUR_TASK_NAME", Void.class)
            .scheduleOnStartup(RecurringTask.INSTANCE, null, delay7sec::getInitialExecutionTime)
            .onFailureReschedule(delay7sec)
            .onDeadExecutionRevive()
            .execute((ti, ctx) -> {
                //execution handler
                long nextInterval = taskService.run(); //run
                return (executionComplete, executionOperations) -> {
                    //completion handler
                    Instant nextExecTime = executionComplete.getTimeDone().plusMillis(nextInterval );
                    executionOperations.reschedule(executionComplete, nextExecTime, null);
                };
            });
    }
```
Upon `taskService.run()`, you can suite your self to generate the next scheduling interval. If you want to stop, return a `CompletionHandler.OnCompleteRemove<>()` in the execution handler.

**Comment by anon-software** [comment]
Sorry, I do not understand this solution. For example, the job finished its run and the completion handler schedules the next run in 15 minutes so the job "went to sleep". While it was sleeping, and urgent email was generated and something needs to "wake it up" - that is the purpose of the reschedule method. When it had finished the regular run earlier, it had not know that the urgent email would appear to schedule an early wake up call.

The solution suggested by the exception message works, it is just that I have a personal problem with finding the "correct" minimum early wake up call that won't delay the email unnecessary and yet still guarantee that the conflict would not occur.

**Comment by meggarr** [comment]
In your case of "urgent-email", you should call method `Scheduler.cancel(..)` to do `Shceduler.schedule(..)` . Hope this helps.

**Comment by anon-software** [comment]
While I have not tried it, I am certain I shall run into the same problem because both reschedule and cancel use the exact same condition to raise the exception:

```
        public void cancel(TaskInstanceId taskInstanceId) {
            String taskName = taskInstanceId.getTaskName();
            String instanceId = taskInstanceId.getId();
            Optional<Execution> execution = taskRepository.getExecution(taskName, instanceId);
            if (execution.isPresent()) {
                if (execution.get().isPicked()) {
                    throw new TaskInstanceCurrentlyExecutingException(taskName, instanceId);
                }
```
```
        public <T> void reschedule(TaskInstanceId taskInstanceId, Instant newExecutionTime, T newData) {
            String taskName = taskInstanceId.getTaskName();
            String instanceId = taskInstanceId.getId();
            Optional<Execution> execution = taskRepository.getExecution(taskName, instanceId);
            if (execution.isPresent()) {
                if (execution.get().isPicked()) {
                    throw new TaskInstanceCurrentlyExecutingException(taskName, instanceId);
                }
```

**Comment by kagkarlsson** [comment]
> I could follow the advice and check if the next execution is at least 15 seconds (for example) away as a condition to reschedule to avoid the collision, but hard-coding such a value really looks like a poor programming practice to me. Is there a better way?

Not sure there is a better way. You could use a one-time task in addition to the recurring one, though you will risk them executing at the same time, which is most likely not something you want. 
You could probably get away with 1 second. You want to have time to do the reschedule and commit before the execution is due.

Let me know if there is a `SchedulerClient` api-method that would help this use-case. Maybe a `tryReschedule(..)` that does not throw..

**Comment by anon-software** [comment]
Thanks for the reply and offer to modify the code. However, even I do not think it is worth the effort. I only asked if there was a better way that I had missed, but the workaround is totally acceptable.

I do not think "tryReshedule" buys us anything, I can just as well catch the exception myself. But without querying my DB I do not know if the current run has already picked it in which case I should just do nothing or the run had already started before the email was generated so I would need to run it again. The extra query just seems too much complication compared to the workaround. What might work is "rescheduleOrRerun" where instead of throwing an exception it would override the predefined schedule and make another run immediately after the completion of the current one. However, it is not that simple in my case because I also define the minimum sleep time. For example, the normal sleep time in the email job I use is 15 minutes, but I do not want to have it constantly executing and interfering with the normal operations so I impose a minimum of three minutes sleep time. I do not see this scenario being a common use case to deserve anybody devoting their time to its development.

I am closing the issue with another suggestion - try adding more Javadoc method comments. I have rewrote my ad-hoc job management which worked only with a single server using your library, but I found it took me more time that it should have because I needed to walk through the code to understand how to use it.

**Comment by kagkarlsson** [comment]
Would you suggest some specific areas you think the javadoc could be improved?

**Comment by meggarr** [comment]
I think this is a matter of how it design the recurring task, then the task of sending email is scheduled to next 15min, and it has a requirement to be possible to send an urgent email before the normal 15min schedule, it probably needs to design the task to check pending email tasks every 1 or 2 seconds - with the assumption that the email object is tied to a sending timestamp. Then, it can dynamically add any urgent emails, but keep a simple recurring email-sending task to check any emails to sent every 1 or 2 sec..

my 2c.

**Comment by anon-software** [comment]
Hi Gustav, just pick any class, most of its methods lack Javadoc. One thing that I remember would have helped me would be a comment on the Scheduler class itself stating that there should be only one instance of it. I later noticed a "fuzzy" reference to it in the readme file which I found only after experiencing errors with multiple instances - I initially created one for each job not understanding the basic concepts. And while speaking of that class, none of its method are commented either except for a few that get the comment from the SchedulerClient interface.

Of course, it would be too much now to go back and comment everything. I am sorry if I sound "demanding", that was not my intention. I am only suggesting you add a comment here or there as you edit a file and over time you will eventually catch up.

**Comment by anon-software** [comment]
I have remembered one more thing that still puzzles me. I implemented a custom "Schedule", but I could not find anywhere what the purpose of its "isDeterministic" method is. If you are going to add any comments, please do this one first.
