### ISSUE TITLE
Implementations of FailureHandler do not use Clock

### ISSUE THREAD

**Issue by asergiyenko4screen** [kagkarlsson/db-scheduler#359]
# Prerequisites
We are using `ManualScheduler` and `SettableClock` in our tests to control the task lifecycle and everything was working as expected before we started to use `MaxRetriesFailureHandler` and `ExponentialBackoffFailureHandler`.

`ExponentialBackoffFailureHandler` does not use `Clock` to get the current timestamp, but uses `Instant.now()` instead. This leads to a mixed behaviour in the tests and contradicts with the happy path execution timestamps which provided by `SettableClock`.

## Expected Behavior
Expected that `FailureHandlers` would use `Clock` (SettableClock) to schedule the next execution.

## Current Behavior

Currently the `Instant.now()` is used to calculate the next execution time.
https://github.com/kagkarlsson/db-scheduler/blob/8ffe82547ad7c81db02a82547e5f0477d0580e6a/db-scheduler/src/main/java/com/github/kagkarlsson/scheduler/task/FailureHandler.java#L91

## Context
- DB-Scheduler Version : 1.16
- Java Version : 17
- Spring Boot (check for Yes) : [X]
- Database and Version :

**Comment by kagkarlsson** [comment]
Should be fixed in `v12.0.1`
