### ISSUE TITLE
no json in task_data?

### ISSUE THREAD

**Issue by m7yJpNXY** [kagkarlsson/db-scheduler#362]
I've registered a JacksonSerializer and was kind of expecting to see json when looking at the task_data in scheduled_tasks in DbVisualizer. That is not the case though. I just see strange characters as if using the standard serializer. The datatype of task_data is nvarchar(max) and the serialized result is written down as bytes. Shouldn't it be written down as a string?

**Comment by kagkarlsson** [comment]
What database? The field might be of binary type, so you might need to decode it to a string

**Comment by m7yJpNXY** [comment]
SQL Server

**Comment by m7yJpNXY** [comment]
Ops! Closed it

**Comment by kagkarlsson** [comment]
`task_data` potentially holds binary data, e.g. serialized Java objects, so I think it needs to be written as bytes. You could try some conversion on the data to try and render it as a string

**Comment by meggarr** [comment]
Not relates to this topic, but for PostgreSQL, this column ```task_data``` can be ```json``` or ```jsonb```

**Comment by kagkarlsson** [comment]
Well the thing is that the default serialization is Java serialization which is not represented as json

**Comment by kagkarlsson** [comment]
We might add some schema and `JdbcCustomization` to let people use `json` though..

**Comment by mumubin** [comment]
@kagkarlsson I think JsonSerializer is a better default choice. 
My project is going through the change of TaskData. 

For example
```java
class XXTaskData{
  String sessionId;
  String token;
}
```
For security requirement. we should change the token to SecureString
```java
class XXTaskData{
  String sessionId;
  SecureString token;
}
```
How to handle old task data (String token in database)
So I handle to write a custom ObjectInputStream to handle this.
It is binary, it is hard to develop and maintain.

If it is a Json string in database, I only need to objectmapper.register(new SecurityStringModule())

**Comment by kagkarlsson** [comment]
Yeah thats a valid workaround. Unfortunately, Java serialization was not really made for our use-case. I might have chosen json as default if I made it from scratch now, but at this moment we also need to take into account the ones already using Java serialization.

Possibly at one point we can make json first-class and Java serialization a fallback alternative (need to be reflected in schemas and `JdbcCustomizations`
