### ISSUE TITLE
tash can’t picked after instance crashed ( lockAndFetch )

### ISSUE THREAD

**Issue by GithubRyze** [kagkarlsson/db-scheduler#363]
# Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [ ] I am running the latest version
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed

## Expected Behavior

task can be picked and execute again after instance restart

## Current Behavior

task can‘t be picked and execute

--------
# For bug reports
**YOU MAY DELETE THE `For bug reports` SECTION IF A NEW FEATURE REQUEST.**

## Steps to Reproduce the bug
1.    new RecurringTaskWithPersistentSchedule 
2.    stop the instance when task executing
3.    restart instance
4.    the task will never picked again (picked=true in step 2)

## Context
- DB-Scheduler Version : 11.6
- Java Version : 8
- Spring Boot (check for Yes) : [ ]
- Database and Version :

**Comment by kagkarlsson** [comment]
I do not believe you :). Doesn't the `DeadExecutionHandler` trigger?

**Comment by GithubRyze** [comment]
thanks . i  have checked again and  It's my wrong.
