### ISSUE TITLE
Scheduler.exists(TaskInstanceId)

### ISSUE THREAD

**Issue by zeitwesen** [kagkarlsson/db-scheduler#38]
I'm using your library to fulfill a timeout-watchdog. So basicly I use OneTimeTasks that timeout unless reset (canceled and rescheduled) before. 
Currently I'm catching the RuntimeException of scheduler.cancel and schedule the task again  as follows:
```
try {
	scheduler.cancel(TaskInstanceId.of(tasktype.getTaskName(), watchdogId.getId()));
} catch (RuntimeException e) {
	if (e.getMessage().startsWith("Could not cancel schedule")) {
		LOG.debug("Exception:", e);
		return;
	}
	throw e;
}
// and afterwards schedule the task again
```

What I'm looking for is an exists-Method to get rid of this ugly exception handling, e.g.:
```	TaskInstanceId instanceId = TaskInstanceId.of("taskName", "id");
	if(scheduler.exists(instanceId)){
		scheduler.cancel(instanceId);
	}
	scheduler.schedule(...);
```

**Comment by kagkarlsson** [comment]
Hi! 
I think you can use this existing method on the scheduler/scheduler-client:

```getScheduledExecutionsForTask(String taskName, Class<T> dataClass, Consumer<ScheduledExecution<T>> consumer)```

It will not fetch a specific instance of the task, but if there is only one instance of the task scheduled, you can check it in your code.

Let me know if this does not solve your use-case :)

**Comment by kagkarlsson** [comment]
Hah, good catch, that indeed looks like a bug! In practise, `String taskName` is never used. 

The other one seems ok though? (See [test](https://github.com/kagkarlsson/db-scheduler/blob/master/src/test/java/com/github/kagkarlsson/scheduler/JdbcTaskRepositoryTest.java#L235))

I have never used this functionality myself, it was PR-ed in. I will fix the bug though.

**Comment by kagkarlsson** [comment]
So yeah, the method `getScheduledExecutionsForTask(String taskName, Class<T> dataClass, Consumer<ScheduledExecution<T>> consumer)` is broken, but

`getScheduledExecutions(Consumer<ScheduledExecution<Object>> consumer)` should work

**Comment by zeitwesen** [comment]
yep, just checked it again, in SchedulerClient, Line 118 (see snipped above) the consumer is also not passed on or called - so it is basicly unused. Your mentioned test seems to just cover the underlying TaskRepository. 

I will stay with my Exception-Handler by now and see if you manage to provide a bugfix some time. Thanks again for providing this marvellous library :)

**Comment by kagkarlsson** [comment]
Thanks for the feedback. Will get this issue fixed asap :)

**Comment by zeitwesen** [comment]
No hurry. 

Maybe you could also provide the `exists(instanceId)` feature  :)

**Comment by kagkarlsson** [comment]
Btw, what about the reschedule-method
```reschedule(TaskInstanceId taskInstanceId, Instant newExecutionTime)```

**Comment by kagkarlsson** [comment]
Ah, no, you must handle exceptions in that case aswell.

**Comment by zeitwesen** [comment]
yep, just gave it a try: 
`java.lang.RuntimeException: Could not reschedule - no task with name 'XXXXXXXX' and id 'XXXXXXXXXXXX' was found.`

But no hurry - so far I can live with my handled `.cancel()`method.

**Comment by kagkarlsson** [comment]
PR #42 has a fix for the `getScheduledExecutionsForTask()`

Will probably implement a method `Optional<ScheduledExecution> Scheduler.get(TaskInstanceId)` instead of an exists method.

**Comment by kagkarlsson** [comment]
The fix is now available in version `4.1`

**Comment by zeitwesen** [comment]
Just tried it -> works like a charme! Thanks for the quick fix!

```
TaskInstanceId taskInstanceId = TaskInstanceId.of(taskName, id);
		scheduler.getScheduledExecutionsForTask(taskName, String.class, e -> {
			if (e.getTaskInstance().getId().equals(taskInstanceId.getId())) {
				scheduler.cancel(taskInstanceId);
			}
		});
```

One improvement still: Could you also implement StandardTaskInstanceId.equals(..) and .hashCode() so I do not explicitly have to compare `getTaskInstance().getId()` to check if it is the same TaskInstance? Now this comparison would yield false.

**Comment by kagkarlsson** [comment]
PR #53 provides a method `getScheduledExecution(instanceId)` which will be slightly better for you. Have also added `equals` and `hashCode` to `StandardTaskInstanceId`. To be released soon.
If you have the time, would you take a quick look at the PR and confirm?
