### ISSUE TITLE
Add ability to use alternate CRON types in CronSchedule

### ISSUE THREAD

**Issue by tom-mckenzie-nuix** [kagkarlsson/db-scheduler#384]
# Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

## Expected Behavior

I want to be able to use a Quartz-style cron expression which includes a field for year. This would allow me to use recurring tasks which stop recurring after a set time. CronDefinitionBuilder already seems to support this, along with all the other styles listed in the CronType enum. 

## Current Behavior

CronSchedule is hard-coded to use spring-style cron expressions which do not support a year. 

--------
# For bug reports
**YOU MAY DELETE THE `For bug reports` SECTION IF A NEW FEATURE REQUEST.**

## Steps to Reproduce the bug
1.
1.
1.

## Context
- DB-Scheduler Version :
- Java Version :
- Spring Boot (check for Yes) : [ ]
- Database and Version :

**Comment by tom-mckenzie-nuix** [comment]
I'm happy to submit a PR for this if I can get permission to push a branch.

**Comment by kagkarlsson** [comment]
This sounds like a neat addition to the CronSchedule, feel free to create a PR. You can fork the repo and create the new branch in your fork and then create the PR from there.

`CronSchedule` is Serializable, so there might exist peristed schedules. This means that when deserialized, the field for crontype will be null, so the class must handle those cases. We probably need to test that as well before release.

**Comment by kagkarlsson** [comment]
Fixed in v12.2.0. Thanks for contributing!
