### ISSUE TITLE
Add task log

### ISSUE THREAD

**Issue by good-vi** [kagkarlsson/db-scheduler#391]
Hi. Can we made second table scheduled_tasks_history similar scheduled_tasks where we can store history log?:

```sql
create table scheduled_tasks_history (
  task_name text not null,
  task_instance text not null,
  task_data bytea,
  execution_time timestamp with time zone not null,
  picked BOOLEAN not null,
  picked_by text,
  last_success timestamp with time zone,
  last_failure timestamp with time zone,
  consecutive_failures INT,
  version BIGINT not null
);

CREATE INDEX execution_time_idx ON scheduled_tasks (execution_time);
```

I found StatsRegistry where i can probably inject self-written logger, but i need additional info:

```java
void register(ExecutionStatsEvent e, TaskInstance additionalInfo)
// or
void register(ExecutionStatsEvent e, Execution additionalInfo)
```

Also i found that debug loggers in ExecutePicked not present any info about task.

**Comment by kagkarlsson** [comment]
A log-table would need to be added as an extension or addon and maintained outside the core project. I think this is similar to what @melistik and rocketbase-io needed. See their project [db-scheduler-log](https://github.com/rocketbase-io/db-scheduler-log)

**Comment by good-vi** [comment]
@kagkarlsson thx. You can add the project to the readme so you don't have to worry about it again. Its funny how they solve my problem using injection in custom serializer)
