### ISSUE TITLE
Feature: Provide housekeeperExecutor and dueExecutor in Scheduler construction

### ISSUE THREAD

**Issue by adamranderson** [kagkarlsson/db-scheduler#392]
Both the `housekeeperExecutor` and `dueExecutor` are created within the Scheduler. This feature would add them to the constructor as an optional parameter and to the SchedulerBuilder. This would allow clients of the library the ability to configure these executors in the same way the current executor can be provided.

If either of these executors are not provided in the Scheduler constructor the current instantiation of them would happen.

**Comment by kagkarlsson** [comment]
What is the reason you want to configure these?

**Comment by kagkarlsson** [comment]
This issue has been resolved in v12.4.0
