### ISSUE TITLE
Cron syntax

### ISSUE THREAD

**Issue by decebals** [kagkarlsson/db-scheduler#40]
First of all, congratulations for this library.
I want to ask if it's a possibility to use a Cron syntax when I schedule a task/job.

**Comment by kagkarlsson** [comment]
Thanks! I want to be able to support cron-patterns, and ideally we would use some existing cron-library for it, but my problem is that I do not want to add a dependency for it. So there are a few options, but I am currently undecided:

* Write our own cron-parser
* Depend on an existing library, but do so via a `db-scheduler-contrib` or `db-scheduler-addons` artifact
* Depend on an existing library, and add it to the db-scheduler jar via shading

For now you can come reasonably close using `Schedules.daily(LocalTime... times)`. 

May I ask what type of cron-pattern do you have need for?

**Comment by decebals** [comment]
> ... my problem is that I do not want to add a dependency for it.

Very good. This is also my approach in my projects.

> ... there are a few options, but I am currently undecided:
> - Write our own cron-parser
> - Depend on an existing library, but do so via a db-scheduler-contrib or db-scheduler-addons artifact
> - Depend on an existing library, and add it to the db-scheduler jar via shading
> 

Personal, I think that variant three (3) is the best (no need to invest time in cron parser). You can mark the dependency to cron-parser library as optional. When you need cron syntax you must include the cron-parser dependency.

> May I ask what type of cron-pattern do you have need for?

For the moment I need to run at a time, only on workday (from Monday to Friday).

I think that add support for cron syntax is a nice feature. In the same time I like to preserve minimalist aspect (very few dependency and small size) of library. In this context it's necessary a cron-parser library with the same profile like this (minimalist and active maintained) .

**Comment by kagkarlsson** [comment]
Do you know of any good cron-libraries?

**Comment by kagkarlsson** [comment]
Ok, will look into it.

Instead of checking in the execution-handler method for workday, you could just write your own implementation of the `Schedule` interface.

**Comment by decebals** [comment]
> Instead of checking in the execution-handler method for workday, you could just write your own implementation of the Schedule interface.

I will try. I want to schedule some tasks from Monday to Friday between 9 AM and 17 PM with a period of 10 minutes (eventually with small delay). I hope that is possible.

**Comment by kagkarlsson** [comment]
Implemented in PR #56
