### ISSUE TITLE
CronSchedule and CompletionHandler when using RecurringTaskWithPersistentSchedule

### ISSUE THREAD

**Issue by codelizrd** [kagkarlsson/db-scheduler#414]
I have a RecurringTaskWithPersistentSchedule task with a ScheduledCron of every 15 minutes (* */15 * * * *), but that depends on the task itself and as such I use the RecurringTaskWithPersistentSchedule task type, which extends AbstractTask, which implements Task, which extends ExecutionHandler requiring a execute() method returning a CompletionHandler.

The task gets selected right on :15, :30, :45 or :00. 

As the task must be considered again using the same context data, I use the CompletionHandler.OnCompleteReschedule with as argument the same CronSchedule.

This however will schedule the task immediately; as long as the current time matches the cron-expression it is re-executed - and as a single run takes around 250msec the task is executed 4 * 60 = 240 times (depending on scheduler configuration).

I assume that if the Task is run because of a match on the cron expression, it should not run again for the same match. So, a */15 run should not be rescheduled immediately at :15 but wait for the :30.

**Comment by codelizrd** [comment]
I altered the CRON to `0 */15 * * * *` so it won't be considered immediately as after running the time is past "0" seconds within the /15: this is however different than people using are used to.

**Comment by kagkarlsson** [comment]
I am not a cron expert, but I would say that setting second=0 as you did in your fix is the correct way to express that. Thank you for reporting a potential issue though 👍

**Comment by yassenb** [comment]
I think a lot of people would trip up over this, I know I spent some time investigating why jobs were scheduled several times instead of once every X minutes. The "*/X" is a very common approach when using CRON and this is definitely different than all implementations of CRON I've come across
