### ISSUE TITLE
Question not an issue

### ISSUE THREAD

**Issue by mcelrojb58** [kagkarlsson/db-scheduler#44]
I am doing some research to re-trigger scheduled tasks without manipulating the database data (manually changing the execution time). I have found the onFailure() function but we may need another way to retry. 

Is there any hidden built in functionality that we can use? 

If not, is it possible to utilize the scheduler object to destroy a task then recreate it?

**Comment by kagkarlsson** [comment]
Hi!

Is this re-triggering due to a failure of the task (i.e. it throws some exception), or is it just that you are waiting for a condition to be fulfilled before it can execute?

To get full control, you could implement your own task similar to this [example](https://github.com/kagkarlsson/db-scheduler/blob/master/src/test/java/com/github/kagkarlsson/scheduler/example/RecurringTaskWithData.java).

or use the builder and create a [custom task](https://github.com/kagkarlsson/db-scheduler/blob/master/src/test/java/com/github/kagkarlsson/scheduler/example/SchedulerMain.java#L46)

Let me know if this was helpful for your case or not :)

**Comment by kagkarlsson** [comment]
To clarify, if you reschedule the task in the CompletionHandler without specifying any new task data, it will keep the old data.

**Comment by mcelrojb58** [comment]
This probably is what I am looking for. Overall, the original idea is that we just have an external API that forces a scheduled task (one-time or recurring ) that is provided by user arguments to instantly trigger again without waiting for the next retry/execution time. 

Example one-time task fails, we have it retry a max of 10 times, all failures. It will continue to sit in our database as a failed task, So our support analysts would like this api to trigger another attempt. I think I can see the design for it with the information provided but any additional input would be helpful. The the big snag i currently see without testing an implementation would be that the tasks unique complex ids include the image object data which could make identifying it difficult; although it just may be a minor naming standard change in our application to resolve that concern.

**Comment by kagkarlsson** [comment]
You can implement your own and set it via the builder. What customization
did you have in mind?

tir. 27. nov. 2018 kl. 21:26 skrev mcelrojb58 <notifications@github.com>:

**Comment by mcelrojb58** [comment]
I was thinking about setting custom number of times to retry and intervals to wait with retry in the reschedule on failure. And/or define the actions that take place in the onDeadExecutionRevice(), such as before  built in functionality of reviving the execution such as call an api that creates a support ticket for my team.

Stuff like that?

**Comment by kagkarlsson** [comment]
> Example one-time task fails, we have it retry a max of 10 times, all failures. It will continue to sit in our database as a failed task,

Currently there is no such thing as a failed task/execution. All executions in the table are expected to run at some point. But you could probably achieve what you want by, after the 10th retry, setting the next execution time to some time in the far future. 

> This probably is what I am looking for. Overall, the original idea is that we just have an external API that forces a scheduled task (one-time or recurring ) that is provided by user arguments to instantly trigger again without waiting for the next retry/execution time.

To force a re-execution via an external api, you use the scheduler to find the execution, and reschedule it to `now()`

Also, there is currently not a way to define new task-data via your external api call, but that should be a fairly easy feature to add to the library

**Comment by kagkarlsson** [comment]
Closing this. Let me know if you still need assistance :)
