### ISSUE TITLE
MSSQL schema uses deprecated column type

### ISSUE THREAD

**Issue by aukevanleeuwen** [kagkarlsson/db-scheduler#454]
## Expected Behavior

I expect the MSSQL database schema to not have deprecated column types.

## Current Behavior

The MSSQL database schema has a deprecated column type: My IDE flags this as:

> Since SQL Server 2016 the 'text' type is deprecated. Use 'varchar(max)' instead

**Comment by kagkarlsson** [comment]
🎉 This issue has been resolved in `v14.0.0` ([Release Notes](https://github.com/kagkarlsson/db-scheduler/releases/tag/v14.0.0))
