### ISSUE TITLE
Flag to keep scheduler busy when there are many small one-time tasks?

### ISSUE THREAD

**Issue by bgooren** [kagkarlsson/db-scheduler#46]
Hi!

I'm running into an issue with low throughput of tasks when we have many one-time tasks.

My use-case is as follows: every morning we want to send a certain set of users an e-mail. As an experiment with this library, I now schedule a new one-time task instance with the user id. This is a nice design as it makes retries possible in case of temporary failure (e.g. transactional e-mail provider has temporary outage), also across restarts of the application.

In testing we now learned that (with 2 threads and a 10 second polling interval), we can send 2 emails every 10 seconds.

What I expected was that the scheduler would keep processing tasks and only start polling at 10 second intervals once there was no job to process right away.
Now it essentially runs two one-time tasks within a second and then sits there waiting for 9+ seconds.

It would make sense (to me) from a throughput perspective to poll the queue for new work when we complete, and if there is none, then we wait for the configured poll duration.
E.g. a flag like ```.pollAfterCompletion(boolean)```.

Alternatively I can lower the polling duration (e.g. to 250ms), but that means we are polling very frequently when there is nothing to be done.
Increasing the number of threads is not a solution for us as this leads to other issues (max number of simultaneous connections we can make to third party providers).

What are your thoughts on this?

**Comment by kagkarlsson** [comment]
Will have to check the code, will get back to you

**Comment by kagkarlsson** [comment]
Yes you are correct. I agree that the ideal behavior is for the scheduler to keep executing until there are no executions left. The current implementation is a bit naive.

Probably no quick-fix, but needs to be fixed..

**Comment by bgooren** [comment]
PS Another topic when having a queue full of one-time tasks is that it's a bit wasteful to pull down up to 10.000 tasks from the database every time we poll (JdbcTaskRepository.MAX_RESULTS).
For our workload a much lower number would work as well (due to limited concurrency/competition between schedulers). Are you open to making this configurable with a builder method as well? E.g. ```pollingLimit``` (with a default of ```10000```).

**Comment by bgooren** [comment]
If you are open to it, I can create pull requests.

**Comment by kagkarlsson** [comment]
Please do :)

tir. 18. des. 2018 kl. 16:56 skrev Sebastian Gooren <
notifications@github.com>:

**Comment by bgooren** [comment]
I have created pull requests for both; Please note I did not write additional tests to verify the behavior of the new functionality (yet).

Please have a look and provide feedback.

Thank you!

**Comment by kagkarlsson** [comment]
> Well, of course it depends on how others are using this library (including you).
> 
> We are testing it as a simple work queue, as we don't have workloads which warrant external work queues and this library is nice and lightweight 👍

Yeah, the reason you are finding these quirks is that I am primarily using it for recurring tasks, so a very low volume of executions, hence I have never bumped into these issues :)

However, the use-case you have is definitely one I would like db-scheduler to solve for low to medium volumes. So I am very glad for your contributions 👍
