### ISSUE TITLE
Keeping scheduled task in database after exhausting all retries 

### ISSUE THREAD

**Issue by hamid646m** [kagkarlsson/db-scheduler#480]
I would like to recommend an enhancement: using a configuration to store failed tasks in the database. Here's a use-case I've encountered: for a task, I employ short retries, typically due to incorrect data. Once all retry attempts are exhausted, I receive a notification. At that point, I rectify the data and update the `execution_time` so the task can be reattempted. What do you think?

**Comment by adamalexandru4** [comment]
I've managed by doing a custom FailureHandler called `MaxRetriesNoDeleteFailureHandler` without `executionOperations.stop();`. I can contribute if you want to implement in this way @kagkarlsson. 

Another idea could be to implement the `pause` method on `ExecutionOperations` (I can help with this too)

**Comment by kagkarlsson** [comment]
> I've managed by doing a custom FailureHandler called MaxRetriesNoDeleteFailureHandler without executionOperations.stop();

I don't think that will work. It will be considered dead at some point

You are welcome to try implementing #27. I am not sure how straight-forward it will be, there is a bit of exploration to it..

**Comment by kagkarlsson** [comment]
Closing since duplicate of #27
