### ISSUE TITLE
Optionally export micrometer metrics

### ISSUE THREAD

**Issue by kagkarlsson** [kagkarlsson/db-scheduler#49]
Add optional dependency on micrometer and include some basic metrics from the scheduler.

**Counters:**
* Sucesses
* Failures
* Durations
* Active executors
* Total executors
* Errors

**Gauges:**
* Currently running
* Executions in failing state

**Comment by poberbichler** [comment]
Hey,

first of all thanks for your work on db-scheduler :)

I am currently about to create a simple StatsRegistry impementation using micrometer (https://micrometer.io/). By using micrometer the registry would be vendor-neutral, meaning people could plug in whatever monitoring system of their choice, and not only prometheus. 

If you want I can create a PR later on when it's working, with an optional dependency to micrometer itself.

Cheers

**Comment by kagkarlsson** [comment]
Hi! That would be very helpful! I agree micrometer is a good choice for db-scheduler since it should be monitoring-vendor agnostic :)

I have created something similar in a private repo for an app that also uses db-scheduler, if you want I could dump some of that code here?

**Comment by kagkarlsson** [comment]
I had limited time to make something more official for db-scheduler, so if you want to help with that that would be awesome :)

**Comment by kagkarlsson** [comment]
Added micrometer metrics in v7.2

**Comment by kagkarlsson** [comment]
🎉 This issue has been resolved in `v16.9.0` ([Release Notes](https://github.com/kagkarlsson/db-scheduler/releases/tag/v16.9.0))
