### ISSUE TITLE
How tasks are being re-scheduled when re-launching the application

### ISSUE THREAD

**Issue by aparraga** [kagkarlsson/db-scheduler#50]
Hi,

I have created a task with the code of your example:

```
OneTimeTask<MyTaskData> myAdhocTask = Tasks.oneTime("my-typed-adhoc-task", MyTaskData.class)
        .execute((inst, ctx) -> {
            System.out.println("Executed! Custom data, Id: " + inst.getData().id);
        });

final Scheduler scheduler = Scheduler
        .create(dataSource, myAdhocTask)
        .threads(5)
        .build();

scheduler.start();
```

This code has created an entry in the database and so. Everything works as expected.

My doubt is, if I relaunch the application, do I have to execute again this code to re-schedule the same task again, or is enough to execute another different code just to start the scheduler?
For example, if I execute this other code:

```
final Scheduler scheduler = Scheduler
        .build();

scheduler.start();
```

This code will read all the scheduled tasks from database and re-schedule them again? Or how it works to re-schedule existing tasks?

thank you in advance

**Comment by kagkarlsson** [comment]
Hi!

In the first example you also would need to call `scheduler.scheduler(<the-instance>, <time>)` to make it run, but I suppose you have done that since you say it is working as expected. :)

The database-table is the state, the scheduler does not hold any in-memory state for upcoming scheduled tasks. So if you schedule a task-instance to `tomorrow`, you can stop that application start another one with a similarly configured scheduler and it will run your scheduled task as expected. You must however provide it with the knowledge to map task-name to task-implementation, which is done here `.create(dataSource, myAdhocTask)`. If not provided with `myAdhocTask` here, it will not know what to do with those tasks it finds in the database.

(`.create(dataSource, myAdhocTask)` does nothing more than provide a string -> task-implementation mapping for the scheduler, it does not actually schedule anything to run)

**Comment by kagkarlsson** [comment]
The database is polled every X seconds for due executions btw.

**Comment by aparraga** [comment]
Yes, I forgot to mention the line you are talking about, but yes, otherwise it won't run.

So, coming back to your explanation, what I need to execute everything is the ```.create(dataSource, myAdhocTask)``` but not the scheduler.scheduler, which is a one-time execution just to create the entry in the database, right?

What about recurring tasks? for example:

```
RecurringTask<Void> hourlyTask = Tasks.recurring("my-hourly-task", FixedDelay.ofHours(1))
        .execute((inst, ctx) -> {
            System.out.println("Executed!");
        });

final Scheduler scheduler = Scheduler
        .create(dataSource)
        .startTasks(hourlyTask)
        .threads(5)
        .build();

// hourlyTask is automatically scheduled on startup if not already started (i.e. exists in the db)
scheduler.start();
```

This code need to be executed again and again everytime I startup the application?

Last question is: Can I have multiple instances of the scheduler? Is it a good idea?

**Comment by aparraga** [comment]
btw, thank you for supporting my questions :)

**Comment by kagkarlsson** [comment]
> So, coming back to your explanation, what I need to execute everything is the `.create(dataSource, myAdhocTask)` but not the scheduler.scheduler, which is a one-time execution just to create the entry in the database, right?

Yes

> What about recurring tasks?

Strictly speaking `.startTasks(hourlyTask)` is only needed the first time, when there is no scheduled task record for it in the database. Though it also provides the task-name -> implementation mapping for the scheduler, making it unecessary to provide that in `create(...)` (for recurring tasks where you use `startTasks(..)`)

When an instance of a recurring task has run, it is simply rescheduled according to the provided `Schedule`, so the record in the database will just get a new, future, time for execution.

> Last question is: Can I have multiple instances of the scheduler? Is it a good idea?

Yes, `db-scheduler` is built specifically to handle multiple instances using the same database-table for persistence. Only a single scheduler-instance is allowed to execute a scheduled task (uses a form for locking). (All of my projects using `db-scheduler` have multiple instances of the scheduler)

**Comment by aparraga** [comment]
Hi,

I have noticed that, if the application is terminated while executing the task, the row in the database representing the task has been deleted and there is no way to restart again the task when the application is launched again. Is that correct? How can I prevent that?

thank you in advance

**Comment by kagkarlsson** [comment]
First of all, you need to call `scheduler.stop()` when shutting down your application. That lets currently executing tasks finish. See https://github.com/kagkarlsson/db-scheduler/#proper-shutdown-of-the-scheduler

If the scheduler should be "ungracefully" stopped/killed, any executions it ran still have a record in the database, but they have been marked `picked=true` which indicates that some scheduler instance has picked it for execution. If that scheduler is killed, the execution will eventually be detected as _dead_, and rescheduled (also `picked->false`). 
See https://github.com/kagkarlsson/db-scheduler/#dead-executions

**Comment by aparraga** [comment]
awesome, thank you!

**Comment by kagkarlsson** [comment]
Closing this question :)
