### ISSUE TITLE
Ability to provide ExecutorService

### ISSUE THREAD

**Issue by Gee2113** [kagkarlsson/db-scheduler#51]
In An EE managed environment such as thorntail, ideally youd use a provided managed executor so that the container can manage the creation of threads. Add the ability to provide executorservice/scheduledexceturservice in the Scheduler builder.

**Comment by kagkarlsson** [comment]
Thank you for your suggestion!

Am not very familiar with "EE-environments". What is the benfit of letting for example thorntail supply the executorservice?

**Comment by Gee2113** [comment]
Thanks for the quick reply

The container will provide instances of [ManagedExecutorService](https://docs.oracle.com/javaee/7/api/javax/enterprise/concurrent/ManagedExecutorService.html) and [ManagedScheduledExecutorService](https://docs.oracle.com/javaee/7/api/javax/enterprise/concurrent/ManagedScheduledExecutorService.html) which means the tasks will be run in managed threads created by the containers threadfactory. This allows the continer to add hooks and pas contextual information to these threads etc. it also means that global settings such as thread pool size are adhered to for example. More info here if required: https://jcp.org/aboutJava/communityprocess/final/jsr236/index.html

**Comment by kagkarlsson** [comment]
Will add this in the upcoming release.
