### ISSUE TITLE
Db-Scheduler Additions

### ISSUE THREAD

**Issue by osoykan** [kagkarlsson/db-scheduler#526]
Hi, 

Thanks for the great library! 

I have been developing some additions to the library, for Kotlin.

- Ktor plugin for [db-scheduler-ui](https://github.com/bekk/db-scheduler-ui)
- Couchbase integration _released_
- MongoDB integration _released_

My project can be found: https://github.com/osoykan/db-scheduler-additions

I've started using the Ktor plugin, I was wondering if I should add it to the 3rd party list in this repo for those who want to use/contribute?

**Comment by osoykan** [comment]
I have released Mongo and Couchbase support, FYI:

- https://central.sonatype.com/artifact/io.github.osoykan/db-scheduler-mongo
- https://central.sonatype.com/artifact/io.github.osoykan/db-scheduler-couchbase

I didn't do a battle test in production, though. Feedbacks are welcomed!

**Comment by kagkarlsson** [comment]
Very cool! Yeah we can definately add it to the list of 3rd-party extensions. Will you open a PR?

**Comment by osoykan** [comment]
Thanks for the response! Yes, I am going to open a PR.

**Comment by osoykan** [comment]
In case you've missed it, opened a PR: https://github.com/kagkarlsson/db-scheduler/pull/534 :)

**Comment by osoykan** [comment]
Added to the list, thanks @kagkarlsson, cheers!

**Comment by kagkarlsson** [comment]
🎉 This issue has been resolved in `v15.0.0` ([Release Notes](https://github.com/kagkarlsson/db-scheduler/releases/tag/v15.0.0))
