### ISSUE TITLE
Question: Maximum Number of executions

### ISSUE THREAD

**Issue by mcelrojb58** [kagkarlsson/db-scheduler#57]
Hi again,

Just a simple question is there a maximum number of tasks that a scheduler can complete in an interval?  We are looking at excecuting ~3700 tasks every heartbeat interval and none ever seem to be executed. So we are wondering if we are overloading the wait queue.

**Comment by kagkarlsson** [comment]
What version are you using? There was a bug in versions < 5.0 which limited throughput

**Comment by kagkarlsson** [comment]
I have not tested the upper limit of throughput. What will your per-second rate be do you think?

**Comment by mcelrojb58** [comment]
We are on version 3.3 and in am not sure. But we will update the dependency and see how it performs.

**Comment by kagkarlsson** [comment]
Ok, yeah, then you should definately upgrade. Should solve your problem.

**Comment by kagkarlsson** [comment]
Let me know how that works out

**Comment by kagkarlsson** [comment]
Are you still having problems or did the upgrade to version 5 solve them?

**Comment by kagkarlsson** [comment]
Closing this question due to inactivity. Reopen if you are still having problems.

**Comment by kagkarlsson** [comment]
🎉 This issue has been resolved in `v16.9.0` ([Release Notes](https://github.com/kagkarlsson/db-scheduler/releases/tag/v16.9.0))
