### ISSUE TITLE
Question: First execution time of cron based recurring task is when?

### ISSUE THREAD

**Issue by adamvelo** [kagkarlsson/db-scheduler#59]
Project looks great! Very keen to use it for upcoming clusterable scheduler service.. so thanks!

From the readme:

> To create the initial execution for a RecurringTask, the scheduler has a method startTasks(...) that takes a list of tasks that should be "started" if they do not already have a future execution. Note: The first execution-time will not be according to the schedule, but simply now().

So does this hold for CRON style recurring tasks?

i.e. My cron says do this every day at 11:25am but my service starts up for the first time and the recurring task doesn't exist in the DB yet (task id presumably?) so would this run immediately now?

**Comment by kagkarlsson** [comment]
Yes, that is correct. A pretty bad default behavior for cron schedule I agree. Will see if I can fix that!

**Comment by kagkarlsson** [comment]
Sorry I didn't get back to you earlier. The current workaround is to define your own `Task` type, for example based on [CustomTask](https://github.com/kagkarlsson/db-scheduler/blob/master/src/main/java/com/github/kagkarlsson/scheduler/task/helper/CustomTask.java), but make the `OnStartup` implementation schedule it to the first Instant in the schedule.

I think I will change the default for all recurring tasks to the first instant in the schedule, but make it overridable via the builders.

**Comment by kagkarlsson** [comment]
PR #60

**Comment by kagkarlsson** [comment]
Fixed and released in version `5.2`

**Comment by kagkarlsson** [comment]
Let me know if things are not working as expected :)
