### ISSUE TITLE
Task removal if there is no more implementation

### ISSUE THREAD

**Issue by ystarikovich** [kagkarlsson/db-scheduler#61]
In our spring based project we are using conditional task registration. Right now we are facing the problem when we are disabling the Tasks.

In other words in database we still have record for the task and but in runtime there is no more registered implementation.

From my perspective there will be useful property or explicit function for removing / marking  unsable tasks. Because currently it is generating a lot of redundant log messages. When you need, for instance, disable specific task due to unsuccessful rollout. 

I'm happy to submit PR, but first would like to know your vision on this particular problem and if you want to give instruments in the library.

**Comment by kagkarlsson** [comment]
Yes "old" executions in the table will cause a bit of pain. I have thought about supporting some simple functionality where you easily can add tasks that should be "drained" for executions: 
```
Scheduler.create(...)
...
.drainTasks("my-old-task")
.build()
```

Is that ok for your use-case, or are you really looking to temporarily pausing a task?

For now you would have to create sort of a "No-op" implementation, i.e. still register the task, but with an empty execution-handler. Recurring-tasks to be drained need a modified completion-handler that just deletes the execution.

**Comment by kagkarlsson** [comment]
Thoughts? :)

**Comment by adamvelo** [comment]
My use case is a cluster of instances all running the same scheduled tasks that come from a config file. When a new version of the app is rolled out in a blue/green deployment and the new config file no longer contains some of the recurring tasks that the blue instances are still executing, I want the first new green instance that comes up to drain/cancel/delete the recurring tasks that are no longer valid. So some notation like:

Extra cancelOtherTasks boolean passed to startTasks defaulted to false
`Scheduler.create(dataSource).startTasks(tasks,true).build();`

or

`Scheduler.create(dataSource).startTasks(tasks).cancelOtherTasks().build();`

Or some other naming that makes more sense to you...

Something like that would be awesome! Currently I've got custom code that just deletes stuff directly from the db.

**Comment by ystarikovich** [comment]
I would prefer, honestly, as it was shown above to have one property to submit tasks with force option to use only tasks which you submitted to the Scheduler, something like this:

`Scheduler.create(dataSource).startTasks(tasks).forceSubmitTasks().build();`

I can't imagine scenario when you need to detach one or two tasks. In this case much easier will be to avoid registering it :)

**Comment by kagkarlsson** [comment]
Ok, I can see your point, "it just works". The reason it does not work like that by default is to make it more difficult to accidentally delete scheduled tasks, for example if you manage to deploy schedulers with a different set of "known tasks". One would delete tasks the other schedules.

```
Scheduler.create(dataSource)
  .startTasks(tasks)
  .removeUnresolvedTasks()
  .build();

```

I suspect that the simplest way of removing executions for unknown tasks is to have the `TaskResolver` add a no-op implementation if it fails to find an implementation. Not sure which would be best, remove all on startup or just dynamically add a handler that quietly does nothing for unknown tasks. Leaning towards no-op since it would avoid some edge-cases that might occur if an old scheduler just picked the execution we are deleting..

**Comment by adamvelo** [comment]
@kagkarlsson I have recurring tasks running (say) every 5 secs and then that job is removed from config. When the next scheduler is built and the removeUnknownTasks() is called... is that old job still executing every 5 secs but as a no op? When would the task be removed from the db table?

**Comment by kagkarlsson** [comment]
No the idea would be that the no-op task has en `ExecutionHandler` that does nothing but return `return new CompletionHandler.OnCompleteRemove();`

So the record in the tables would disappear as soon as its execution-time is reached (and will not be rescheduled)

**Comment by kagkarlsson** [comment]
Of course one solution does not have to exclude the other. How important is it for you to have the executions removed immediately?

**Comment by adamvelo** [comment]
Canceling on next run is fine for my use cases so that NoOp strategy works for me. Some INFO Level logging might be useful.

**Comment by kagkarlsson** [comment]
Yes INFO logging definitely 👍

**Comment by kagkarlsson** [comment]
Have started working on this one.

**Comment by kagkarlsson** [comment]
"Re-started" working on this one as my original idea was not good enough.

Current plan is the following:

When the scheduler fetches due executions/tasks, any unknown task-names are skipped and added to a list of "unresolved tasks". On the next fetches for due executions these "unresolved tasks" are excluded. 

Am then planning to add a config-option to the builder that will clear the records from the db after a certain amount of time.
```
.removeUnresolvedTasksAfter(Duration.ofDays(1))
```

This will prevent executions with unknown tasks from blocking other due executions. It will also make it less of on "error"-situation so there will be significantly less error-logging.

Still good @adamvelo @ystarikovich ?

**Comment by adamvelo** [comment]
@kagkarlsson sounds great 👍

**Comment by kagkarlsson** [comment]
Coming up in PR #80

**Comment by kagkarlsson** [comment]
Fixed in 6.3

**Comment by shyam-goyal** [comment]
@kagkarlsson We have a bunch of schedulers with different set of known tasks. Now one scheduler's housekeeper thread deletes tasks that are known to other schedulers. The only solution I can see is setting the deleteUnresolvedAfter a very large duration, so the unresolved tasks are never deleted in some near future.

 Is there some other way of disabling this behaviour ?

**Comment by kagkarlsson** [comment]
It is currently not supported to run multiple schedulers with different task-sets against the same table
