### ISSUE TITLE
Question - Use custom classes for Tasks

### ISSUE THREAD

**Issue by decebals** [kagkarlsson/db-scheduler#62]
Maybe the question is simple but for the moment I don't see a solution.
Right now, I use something like this to declare and schedule tasks:
```java
List<Task<?>> tasks = new ArrayList<>(1);
tasks.add(Tasks.recurring("mytask", Schedules.daily(LocalTime.of(23, 0, 0)))
    .execute((taskInstance, executionContext) -> {
        System.out.println("MyTask");
    }
}

scheduler = Scheduler.create(dataSource, tasks).tableName("scheduled_task").threads(3).build();
```

but I want something more dynamic.
The first request is that I want to put the logic for each task in a separate Java file. I don't to put all tasks in a single file.

```java
class FirstTask extends Task {
}

class SecondTask extends Task {
}
```
The second request is to persist all scheduled task in database like:
```
task1 (task name) -> "5 0 * * *"  (cron syntax)
task2 -> "3 0 * * *"
```

The idea is to have a table in UI with all scheduled tasks and to be able to edit easy this list (schedule new tasks, edit trigger, ...).

Is it possible?

**Comment by kagkarlsson** [comment]
> The first request is that I want to put the logic for each task in a separate Java file.

Sure, you are free to put the tasks wherever you like :), you could write tasks as you suggest. 
`Tasks.recurring(...)` is merely a helpful builder, you could also create a class that extends for example [RecurringTask](https://github.com/kagkarlsson/db-scheduler/blob/master/src/main/java/com/github/kagkarlsson/scheduler/task/helper/RecurringTask.java).

> The idea is to have a table in UI with all scheduled tasks and to be able to edit easy this list (schedule new tasks, edit trigger, ...).

This is not really possible in db-scheduler, the schedule lives with the task-implementation in the Java-code to keep the database-table(s) simple. For this kind of behavior you may want to have a look at Quartz. 

There is sort of a hack though, should you really want it.. In theory you could make a `CustomTask` that stores its `Schedule` as part of the task-data, you should then be able to edit the data via a UI. The problem will be if you have scheduled several instances of one type of task, and want to update the schedule for all instances reliably, there is no good way to do that.

**Comment by kagkarlsson** [comment]
Closing this question.
