### ISSUE TITLE
Question: Recovering from database connection errors

### ISSUE THREAD

**Issue by mvestola** [kagkarlsson/db-scheduler#64]
This project seems interesting and planning to use it. After reading the docs and some issues, I have one question about some corner case recovery which I did not find an answer.

Docs say: "When the execution of a recurring task has finished, a Schedule is consulted to determine what the next time for execution should be, and a future task-execution is created for that time (i.e. it is rescheduled)."

What happens if a recurring task is successfully finished but after that there is a temporary database or some connection / server failure when this future task-execution is created? If I have understood right, it tries to write a new row to `scheduled_tasks` table. But if there is a database connection error just at that point when new row is created to `scheduled_tasks` table, can it recover from this?

**Comment by kagkarlsson** [comment]
Good to hear :).

What happens roughly is:

1. Mark task-execution as "picked" so no other scheduler-instance will attempt to run it.
2. Delegate to ExecutionHandler
3. While the task is executing, another thread regularly updates a heartbeat on the row
4. a When execution is done, the `CompletionHandler` returned by the `ExecutionHandler` determines what happens next. For recurring tasks, the `CompletionHandler` reschedules the task-execution. It's a single operation that removes the "picked" flag and sets a future execution-time according to the schedule. => done
4. b Should the `ExecutionHandler` throw an exception during execution, the `FailureHandler` is run. For recurring tasks, it reschedules to the next time according to schedule.
4. c If the scheduler crashes or it fails to reschedule, the heartbeat-timestamp will become stale. Should that happen, the task-execution is a some point considered to be "dead" and the `DeadExecutionHandler` is run. For recurring tasks, it will just remove the "picked" flag and it will run again (which means idempotency is important).

**Comment by mvestola** [comment]
OK. Thanks for the response. That made it clear that it can recover from the temporary database connection issues.
