### ISSUE TITLE
Scheduler.create with java.sql.Connection

### ISSUE THREAD

**Issue by Cleiton-D** [kagkarlsson/db-scheduler#66]
I have a java.sql.Connection object, but I don't have the DataSource.
I would like to be able to create a Scheduler using java.sql.Connection

example:
<pre>final Scheduler scheduler = Scheduler
        .create(connection)
        .startTasks(hourlyTask)
        .threads(5)
        .build();</pre>

**Comment by kagkarlsson** [comment]
Hi,

Using only a `Connection` will not work since they are not meant to be long-lived. We need a `DataSource`, which is just a class that knows how to create a new `Connection` when it needs it.

**Comment by kagkarlsson** [comment]
🎉 This issue has been resolved in `v16.9.0` ([Release Notes](https://github.com/kagkarlsson/db-scheduler/releases/tag/v16.9.0))
