### ISSUE TITLE
Typo in log message "Creating scheduler with configuration"

### ISSUE THREAD

**Issue by mvestola** [kagkarlsson/db-scheduler#67]
There is a typo in log message when calling `LOG.info`. Thread count and polling interval are in wrong places in log message. I have configured scheduler to use polling interval 30 sec and thread count to 5 like this:

```
Scheduler
.create(dataSource)        
.pollingInterval(Duration.ofSeconds(30))
.startTasks(task)
.threads(5)
.build();
```

But it prints to log this:
```
INFO  com.github.kagkarlsson.scheduler.SchedulerBuilder Creating scheduler with configuration: threads=30, pollInterval=5s, heartbeat=300s enable-immediate-execution=false, table-name=scheduled_tasks, name=xxxx
```

So should switch these variables passed to  `LOG.info`:
```
waiter.getWaitDuration().getSeconds(),
executorThreads,
```

This place in code:  https://github.com/kagkarlsson/db-scheduler/blob/ca30dd73456770cc39712780fb8380d3dadc5894/db-scheduler/src/main/java/com/github/kagkarlsson/scheduler/SchedulerBuilder.java#L146

**Comment by kagkarlsson** [comment]
Thanks! Will fix :)
