### ISSUE TITLE
Scheduler start in Spring-Boot

### ISSUE THREAD

**Issue by zsmeier** [kagkarlsson/db-scheduler#70]
Hi Gustav, 
i have the problem in a Spring-Boot application, that the scheduler starts before the spring context loading is finished. Is there any out of the box way to start the scheduler threads only **after** the context is initialized? 
(The only way I found, is to rewrite the autoconfiguration using the ManualSchedulerBuilder as Builder, overwriting the _executeOnStartup_ method).

Is there any better/simple way to do this? No one had this issue before?

Thanks.

**Comment by kagkarlsson** [comment]
Hi! Could you try to explain why it is not allowed to start before the context is finished? Are not dependencies also spring beans?

**Comment by zsmeier** [comment]
Is just as I know, there is no guaranty that all the beans needed by the runnig task are initialized before the whole context is not initialized (concrete in our case Sleuth or Tracer). Of cource, i could make the creation of the task dependent of all the beans I need, but there is always something what I don't know.
It just would be safer, I think, to start the tasks execution when everything is up. Or do I miss something?

**Comment by kagkarlsson** [comment]
Btw, `ManualSchedulerBuilder` is intended for testing

**Comment by kagkarlsson** [comment]
There may be some area here that I am unfamiliar with (have not used Sleuth or Tracer). Could you give an example of the type of errors are you getting?

**Comment by zsmeier** [comment]
We use the db-scheduler to start some (spring) batch jobs. One "problem" is i.e. the scheduler start the batch job, which reads, processes and writes to the db. Each step information is logged to a logfile, but until the spring context is not ready, we miss the TraceIds and SpanId from the Log-Entries. It is not that bad of course, is just a trace/spanId can be very helpful on error finding.

The other issue is during our integretion test. We use H2 Memory DB for the tests, the scheduler starts the batch job but the db-tables used by the batch are still not created, so we get during the first job executions an sql exception saying that the batch table does not exists.

Anyway, we resolved the problem, having the executor skipping the lauch of the batch job, until the ContextReady Event from Spring is fired.
