### ISSUE TITLE
Replace EmbeddedPostres with TestContainers for integration tests

### ISSUE THREAD

**Issue by kagkarlsson** [kagkarlsson/db-scheduler#72]
Currently we are using EmbeddedPostgres as database for integration tests. It is failing sporadically among other things, so I think a good idea would be to replace it with [test-containers](https://www.testcontainers.org/).

**Comment by sa160690** [comment]
Hi @kagkarlsson, I can do this one.

**Comment by kagkarlsson** [comment]
That would be awesome!

**Comment by sa160690** [comment]
Hi @kagkarlsson, can you please assign this to me. Thanks

**Comment by kagkarlsson** [comment]
Sure :)

**Comment by kagkarlsson** [comment]
Fixed in 7.0
