### ISSUE TITLE
Task completion sometimes fails inside onCompleteReschedule

### ISSUE THREAD

**Issue by tarmo-lehtpuu** [kagkarlsson/db-scheduler#73]
We're running db-scheduler on 2 servers, with 1s polling interval and immediate execution enabled. I have about 10 jobs and from time to time some of them fail in the onCompleteReschedule step (5-10 times a day).

```
Failed while completing execution Execution: task=foo, id=recurring, executionTime=2019-11-14T09:00:00.454264Z, picked=true, pickedBy=bar-567f94488b-jmq9v, lastHeartbeat=2019-11-14T09:00:00Z, version=67910. Execution will likely remain scheduled and locked/picked. The execution should be detected as dead in PT4M, and handled according to the tasks DeadExecutionHandler.

java.lang.RuntimeException: Expected one execution to be updated, but updated 0. Indicates a bug.
	at com.github.kagkarlsson.scheduler.JdbcTaskRepository.rescheduleInternal(JdbcTaskRepository.java:196)
	at com.github.kagkarlsson.scheduler.JdbcTaskRepository.reschedule(JdbcTaskRepository.java:154)
	at com.github.kagkarlsson.scheduler.task.ExecutionOperations.reschedule(ExecutionOperations.java:38)
	at com.github.kagkarlsson.scheduler.task.CompletionHandler$OnCompleteReschedule.complete(CompletionHandler.java:50)
	at com.github.kagkarlsson.scheduler.Scheduler$PickAndExecute.complete(Scheduler.java:327)
	at com.github.kagkarlsson.scheduler.Scheduler$PickAndExecute.executePickedExecution(Scheduler.java:309)
	at com.github.kagkarlsson.scheduler.Scheduler$PickAndExecute.run(Scheduler.java:286)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:844)
```

**Comment by kagkarlsson** [comment]
Thanks for opening an issue. That sounds like a serious bug. 

You don't have any other operations that could affect the record in the database, ie. some manual rescheduling of the task or anything like that?

**Comment by kagkarlsson** [comment]
Will see if I can replicate the issue.

**Comment by tarmo-lehtpuu** [comment]
Hi, we don't manually mess with scheduled_tasks table in any way, it's just different pods running db-scheduler.

Running mariadb with Galera (if that helps)

**Comment by kagkarlsson** [comment]
Yeah I think that helps. :)  
Galera is a multi-master MySQL cluster? What type of transaction-isolation level are you using?

**Comment by kagkarlsson** [comment]
I am not familiar with Galera, but found some comments about transaction handling in Galera:
> When a transaction requires a lock on a certain row, a plain old MySQL server employs what is known as pessimistic locking. This means that the server will assume that, unless steps are taken to avoid it, some other client will surely also try to modify the row in question and cause a conflict. As such, if a lock is required by a transaction, MySQL prevents any other client from messing with that row until such time as the transaction is committed (or rolled back) and the lock is released. At that point the second transaction can obtain the lock, make its changes, and so on.

> Galera transactions also work like this but only on the local node. That’s the important thing. When it comes to other nodes in the cluster, Galera uses optimistic locking. This means that no checks are made with other nodes on the cluster when local locks are attained. Galera assumes that, once the transaction is committed and the other nodes are informed, everything will be okay and no conflicts will arise.

This is not compatible with db-scheduler that uses optimistic locking to guarantee that a row is handled by a single scheduler.

**Comment by tarmo-lehtpuu** [comment]
We are using READ_COMMITED. It could be somehow related to Galera yes, although it uses synchronous replication so it should work with optimistic locking.

**Comment by kagkarlsson** [comment]
How often are tasks executing? (what type of Schedule)

**Comment by kagkarlsson** [comment]
And how long are they running typically?

**Comment by kagkarlsson** [comment]
Are the queries loadbalanced between the nodes?

**Comment by kagkarlsson** [comment]
From your log it looks like two schedulers are picking the same execution. Which should not be possible. See [JdbcTaskRepository.pick(..)](https://github.com/kagkarlsson/db-scheduler/blob/master/db-scheduler/src/main/java/com/github/kagkarlsson/scheduler/JdbcTaskRepository.java#L203)

From what I understand in Galera, if two writes conflict, the last transaction to try and commit will be rolled back. That should be compatible with optimistic locking as you say. Will JDBC throw an `SQLException` if there was a write conflict?

**Comment by tarmo-lehtpuu** [comment]
All tasks are recurring, with intervals between 1-2 hours to 1 minute. And one task is even rescheduled every second, that might be a bit abusing db-scheduler, sorry :)

Some tasks run for 10-20 minutes, the one that runs every second usually runs for a few hundred ms. In practice the every second task runs every 2 seconds with 1s polling interval, which is OK.

The problem can appear with any of the tasks, even the longer running ones. Had to lower heartbeat-interval to 1m so it would not stay locked for 20m, right now it is still locked for 4 minutes (which is not great).

In Galera it shouldn't matter which DB node gets the query, they should all have same state. I can't see any JDBC level exceptions or Galera certification failures in this code path.

Config:

```
db-scheduler:
  enabled: true
  polling-interval: 1s
  immediate-execution-enabled: true
  delay-startup-until-context-ready: true
  heartbeat-interval: 1m
```

**Comment by kagkarlsson** [comment]
Ok, so even the long running ones.

I think it sounds very strange.. I have had the scheduler running at 10s
interval for several years in different types of application (though always
with a postgres db) without seeing that kind of error. Which is why I
wonder if there may be a difference in behavior for Galera..

Den fre 15 nov. 2019 kl 10:58 skrev Tarmo Lehtpuu <notifications@github.com

**Comment by tarmo-lehtpuu** [comment]
Could be something related with Galera indeed, I can actually try this in non Galera environment hopefully later this year, that would at least confirm the theory if it stops happening :)

Thank you for your time for looking into this :)

**Comment by kagkarlsson** [comment]
Ok, no problem. Let me know if you see it in vanilla mysql/maria.

Just curious, what is the use-case for having a recurring task with 1s schedule?

**Comment by tarmo-lehtpuu** [comment]
It's basically processing a queue from db, since db-scheduler also has mechanism to support only one node runs the task, didn't have to implement any locking. Probably not best use of db-scheduler but I liked the db based locking approach and it's clean and simple so I just used it instead of rolling my own :)

**Comment by kagkarlsson** [comment]
So every 1s it checks a database-table to see if there is something to do? Sounds like a valid use-case to me. We have some similar tasks

One alternative would be to treat db-scheduler as the queue, and schedule items directly to it (though you miss out on batching then, so that is assuming fairly low volume) and then you could either use `scheduler.triggerCheckForDueExecutions()` or `enableImmediateExecution` to get the "local" scheduler-instance to trigger the check directly

**Comment by kagkarlsson** [comment]
I will close this issue for now. Let me know if you are able to replicate it in a non-Galera environment.

**Comment by tarmo-lehtpuu** [comment]
Just FYI that removing Galera solved this issue, really not sure what the root cause was, maybe some sort of misconfiguration in Galera, but the problem is solved now.

Thanks :)

**Comment by kagkarlsson** [comment]
Good to hear! Thanks for reporting back!

Den tis 17 dec. 2019 kl 13:26 skrev Tarmo Lehtpuu <notifications@github.com

**Comment by paulosuzart** [comment]
Hey folks. I got the same error using PgSQL + `lock_and_fetch` strategy. Not sure if it's related to the strategy. PgSQL is just a regular Google Cloud SQL. I couldn't determine what was going on. What we noticed is that the exceptions happened at times of deployment. If we find any new information, we will share it here.

**Comment by yassenb** [comment]
We are having the same error with the same setup as @paulosuzart - Postgres 17 running in Google Cloud.

I think in our case it's related to a problem with rescheduling dead executions. One instance picks up a task to execute and is then restarted, leaving the task to be rescheduled. Not sure why the update does nothing though but I can think of several scenarios:
* Even though the instance has missed several heartbeat updates it finishes the task and removes it from the DB
* The instance that originally picked up the task does a heartbeat update while another instance tries to revive the task having read the old `version` so nothing is updated
* Two instances try to revive the task at the same time
