### ISSUE TITLE
[Question] max tasks per sec ?

### ISSUE THREAD

**Issue by avierr** [kagkarlsson/db-scheduler#76]
are there any performance metrics on how many tasks can be executed per second?

I have close to over a million tasks, the task in itself would just push a message on to a Queue and nothing else.

I am having to choose between Akka(using Timer) and your library(cos it is so much simpler).

**Comment by kagkarlsson** [comment]
I think I mention in the readme that db-scheduler is intended for low to medium execution volumes. Every execution will make two write roundtrips to the database and there are no batch-optimizations. I have not pushed it to the limit, but I think it might be somewhere around 1k executions per second, and probably limited by the database.

I would consider if it is possible to batch items up when scheduling them, i.e. scheduler a task with references to 100 items that should be pushed to the queue or something like that.
