### ISSUE TITLE
Question: Is it a possibility to get the time for last success execution for a task

### ISSUE THREAD

**Issue by decebals** [kagkarlsson/db-scheduler#77]
I see that the information is available in table (`LAST_SUCCESS` column) and I ask you if I can retrieve this information via API.

**Comment by kagkarlsson** [comment]
Yes, should be available. Check getFailingExecutions() for example (no computer atm). Have written alertrules and used that field

**Comment by decebals** [comment]
I am not sure that you understand my need.

![image](https://user-images.githubusercontent.com/1248311/71382733-dd5dc200-25e1-11ea-8d0f-7f06c2ec25f0.png)

The idea is that I need download data depending on the last success execution time of the task. So, I want only to resume the download process.

![image](https://user-images.githubusercontent.com/1248311/71382927-c8356300-25e2-11ea-8a06-2fb2c2d41067.png)

My expectation is to have a simple method in scheduler, something like `getLastSuccessExecution(taskId): Date`. Is it possible?

**Comment by decebals** [comment]
To add more explanation, my task download some data from `startDate` to `endDate`. Every time when the task is executed I want the `startDate` to be the last success execution of task and the `endDate` to be now (the moment when the task is executed). I hope that now is more clear what I want to obtain.

**Comment by kagkarlsson** [comment]
I see. I think you are better off storing the enddate instant as custom
task data that is updated each run

man. 23. des. 2019 kl. 23:26 skrev Decebal Suiu <notifications@github.com>:

**Comment by decebals** [comment]
My solution:
```java
Instant lastSuccess = executionContext.getExecution().lastSuccess;
```

**Comment by kagkarlsson** [comment]
If that works for you go ahead. I have not checked, but using this strategy I assume you will miss a short time-period between the `endDate` and `lastSuccess`/next `startDate`.

You could create a bit more advanced `RecurringTask` that update its state ( `task_data`) with the last `endDate`. See the example here: https://github.com/kagkarlsson/db-scheduler/blob/master/db-scheduler/src/test/java/com/github/kagkarlsson/scheduler/example/SchedulerMain.java#L44

The reschedule-operation can optionally take the new data to be stored for the execution/task, thus making it available on its next run.
