### ISSUE TITLE
Question: Is it possible to exclude end of week days (Saturday and Sunday)

### ISSUE THREAD

**Issue by decebals** [kagkarlsson/db-scheduler#78]
I want that my task to be executed only in the work days (Monday - Friday). Is it possible?

**Comment by decebals** [comment]
I solved my problem using a cron schedule like:
```java
Schedules.cron(""0 0 23 ? * MON-FRI""):
```

I want to give you a feedback related to embedding `cron-utils`'s resources (classes, i18n files, ...) in `db-scheduler.jar`. Personal I don't like this approach (to use the `shade` Maven plugin to hide one or more  dependencies). I prefer to see the dependency in `pom.xml`, in section `dependencies`, together with the version of this library.
For an application (runnable `jar`) to use `shade` Maven plugin make sense (to create a big/fat jar that contains all classes from all dependencies) but for a library I don't see a clear benefit. My two cents.

**Comment by kagkarlsson** [comment]
Great, I was going to suggest cron 👍

Using shading to avoid any dependency conflicts. Yeah, there are probably
opinions on both sides of the matter :)


lør. 28. des. 2019 kl. 00:11 skrev Decebal Suiu <notifications@github.com>:
