### ISSUE TITLE
Support for JPA or hibernate

### ISSUE THREAD

**Issue by georgemoralis** [kagkarlsson/db-scheduler#81]
Checked the project looks great.! Is it possible to add support for generic JPA or hibernate . I don't want to move to spring boot :(

**Comment by kagkarlsson** [comment]
Hi! Yeah, you can create the scheduler using the `SchedulerBuilder`. Supply it with the same `DataSource` you are using for JPA/Hibernate.

**Comment by kagkarlsson** [comment]
The Spring Boot support is just to make the configuration more convenient for those already Spring Boot users..

**Comment by kagkarlsson** [comment]
Let me know if you have trouble configuring it

**Comment by georgemoralis** [comment]
i guess i can take datasource from hibernate with the following

import org.hibernate.SessionFactory;
    import org.hibernate.engine.jdbc.connections.spi.ConnectionProvider;
    import javax.persistence.EntityManagerFactory;
    import javax.sql.DataSource;
    //...
    public static DataSource getDataSource(EntityManagerFactory entityManagerFactory) {
    ConnectionProvider cp = ((SessionFactory) entityManagerFactory).getSessionFactoryOptions()
            .getServiceRegistry()
            .getService(ConnectionProvider.class);
    return cp.unwrap(DataSource.class);
    }

but that infact is like faking hibernate . Since database table is not as entity i can't access data stored there for example if i want to query and display to user which tasks are scheduled

I think database table should exist as Entity class to be able to use with hibernate or JPA

**Comment by kagkarlsson** [comment]
I don't know how your app is wired, but you should not have to get the `DataSource` from hibernate. At some point in your code, Hibernate is fed a DataSource to use and you can just use that same `DataSource` and feed it to db-scheduler.

I don't think it is a good idea for any explicit Hibernate/JPA entity support i db-scheduler as it will bloat it, and it may leak details that should be encapsulated/hidden in db-scheduler (unresolved tasks, potentially paused, currently executing.. )

The thought is to use the `SchedulerClient` / `Scheduler` to get a list of executions in the table:
```
schedulerClient.getScheduledExecutions(myConsumer);
```

There are also methods for canceling future executions etc. Let me know if you feel any methods are missing :)

**Comment by kagkarlsson** [comment]
So in short, applications using db-scheduler should not interact with the table directly, only via the `Scheduler`/`SchedulerClient`. And if some functionality is missing there, please open a separate issue for that :)
