### ISSUE TITLE
Make Scheduler SHUTDOWN_WAIT configurable

### ISSUE THREAD

**Issue by alexvr** [kagkarlsson/db-scheduler#88]
Hi Gustav,

Thanks for building db-scheduler! It has been a pleasure implementing it in our system.

I would like to make a suggestion: 

The `SHUTDOWN_WAIT` constant in the [Scheduler class](https://github.com/kagkarlsson/db-scheduler/blob/19cc6d9c9373abbe21140de435473f62c61bd5dd/db-scheduler/src/main/java/com/github/kagkarlsson/scheduler/Scheduler.java#L40) defines that it will wait up to 30 minutes before it terminates the remaining tasks. It would be nice to make this duration configurable, so that it better suits the nature of the tasks.

I would like to hear your thoughts on this.

Regards, Alexander.

**Comment by kagkarlsson** [comment]
Hi! Thank you for your kind words :)

If I remember correctly, if `SHUTDOWN_WAIT` is reached, it means some execution will be aborted. That is not ideal as it will not be "unlocked" and need to be detected as "dead" before it is re-scheduled. Usually not a big problem though..

May I suggest that you check `executionContext.getSchedulerState().isShuttingDown()` and gracefully stop whatever the task is doing when a shutdown as been detected? 

Or is your problem that you really need the scheduler to run for longer than 30min?

**Comment by kagkarlsson** [comment]
@alexvr Do you still have a need to configurable `SHUTDOWN_WAIT´? (taking into consideration my comment above)

**Comment by kagkarlsson** [comment]
Fixed, see builder method `.shutdownMaxWait(Duration)`
