### ISSUE TITLE
Created two tasks but only one is stored in table

### ISSUE THREAD

**Issue by decebals** [kagkarlsson/db-scheduler#89]
I use Spring to instantiate the `Scheduler` with below code:
```java
@Bean
public Scheduler scheduler() {
    List<Task<?>> tasks = schedulerTasks(); // this method returns two tasks
    Scheduler scheduler = Scheduler
        .create(dataSource(), tasks)
        .tableName("scheduled_task")
        .threads(1)
        .build();

    return scheduler;
}
```
In `scheduled_task` database table only first task is present.
I tried to debug the code but without success. I cannot identify why the second task is not persisted/triggered.

The first task uses `Schedules.cron("0 0 23 ? * MON-FRI")` as schedule and the second task uses `Schedules.cron("0 0 2 ? * MON-FRI")`.

**Comment by decebals** [comment]
I forgot to specify that I use `Java 11` and DbScheduler `6.2.`

**Comment by kagkarlsson** [comment]
Hi, sorry for the late reply!

If you have recurring tasks that you want to start, you have to add them via the builder-method `startTasks`. Or is this one-time tasks?

**Comment by kagkarlsson** [comment]
`startTasks` makes sure the initial execution is stored in the table.

**Comment by decebals** [comment]
I changed the code according to your suggestions but I receive an error:
![image](https://user-images.githubusercontent.com/1248311/74765550-79c3de00-528c-11ea-9144-4936eb0d32af.png)

I use Java 11.

**Comment by kagkarlsson** [comment]
Your list is a bit too generic, it needs to match the `startTasks` signature:

`<T extends Task<?> & OnStartup>`

Change it to `List<RecurringTask>`  if you have only recurring ones.
