### ISSUE TITLE
More flexibility during auto configuration process

### ISSUE THREAD

**Issue by eRfO** [kagkarlsson/db-scheduler#95]
Hi guys,

Is possible to have the annotation @ConditionalOnMissingBean on all beans declared in auto configuration class DbSchedulerAutoConfiguration? In my case I need to override the DbSchedulerStarter bean adding my logic.

Thanks,
Michele

**Comment by kagkarlsson** [comment]
Curious question, what logic is you want to add?

**Comment by eRfO** [comment]
I'm using Apache Camel and I would like to start the scheduler only when the status of some routes is available. Now I solved my problem looping on a method that check if the status of a specific route is available. But I would listen to a specific event of the Apache Camel framework and then start the scheduler. That's all. Thank you.

**Comment by kagkarlsson** [comment]
Ok, sounds like an ok use-case. Working on something else atm, but PRs are welcome if needed soon :)

**Comment by kagkarlsson** [comment]
Not yet friends with github autoclosing issues when PR is merged 🤔 
Anyway, released now, in v6.8

**Comment by eRfO** [comment]
Tank you so much, I appreciate the work you are doing.
